src/frame/widgets/searchinput.cpp

some translations are not loaded.

fix: translate failed in searchinput widget

---

src/frame/modules/network/sections/wirelesssection.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1150

fix: keep the lenght of ssid among 1-32

---

src/frame/modules/display/rotatedialog.cpp
src/frame/modules/display/rotatedialog.h

https://github.com/linuxdeepin/internal-discussion/issues/1164

restore warning will show after screan rotated

---

src/frame/frame.cpp

on multi-screen and the screens have different device pixel scale ratio

fix: main window geometry is wrong

---

src/frame/modules/display/rotatedialog.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1278

fix(display): exit rotate disloag after press Esc key

---

src/frame/modules/network/accesspointwidget.cpp
src/frame/modules/network/accesspointwidget.h
src/frame/modules/network/wirelesspage.cpp

https://github.com/linuxdeepin/internal-discussion/issues/679

fix: wifi list sort algorithm

---

CMakeLists.txt
src/frame/modules/display/displayworker.cpp

debian会标记/etc/下所有的文件为冲突，所以需要这样处理一下。

chore: profile conflict

---

src/frame/modules/sound/soundeffectpage.cpp
translations/dde-control-center_en_US.ts

https://github.com/linuxdeepin/internal-discussion/issues/1330

fix(sound): missing page title

---

src/frame/modules/display/miracastsettings.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1358

fix(miracast): wrong display nodevice item

---

src/frame/modules/network/sections/ipvxsection.cpp
src/frame/modules/network/sections/ipvxsection.h

https://github.com/linuxdeepin/internal-discussion/issues/1427

fix: ipv4 subnet mask valid checkup

---

src/frame/frame.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1522

fix: crash when startup in terminal

---

src/frame/modules/display/displaywidget.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1406

refactor(Display): do not delete custom configuration file

---

src/frame/updatenotifier.cpp

https://github.com/linuxdeepin/internal-discussion/issues/1521

fix: Update notifications are not hidden

---

src/frame/modules/keyboard/keyboardmodule.cpp
src/frame/modules/keyboard/keyboardwork.cpp
src/frame/modules/keyboard/keyboardwork.h
src/frame/modules/keyboard/shortcutwidget.cpp
src/frame/modules/keyboard/shortcutwidget.h
translations/dde-control-center_en_US.ts

feat(shortcut): add restore defaults button

---

src/frame/modules/display/displaymodel.cpp
src/frame/modules/display/displaymodel.h
src/frame/modules/display/displaymodule.cpp
src/frame/modules/display/displayworker.cpp
src/frame/modules/display/monitorsettingdialog.cpp
src/frame/modules/display/monitorsground.cpp

自定义模式合并屏幕下调整分辨率，会退出合并模式

---

src/frame/modules/accounts/createpage.cpp
src/frame/modules/accounts/modifypasswordpage.cpp

fix(accounts): not hide error tip

---

src/frame/modules/mouse/mouseworker.cpp

chore: change mouse min move speed 3.2 to 2.8

---

src/frame/modules/accounts/accountsmodule.cpp
src/frame/modules/accounts/fingerworker.cpp
src/frame/modules/accounts/fingerworker.h

fix(fprintd): refresh device when enter user detail page again

---

src/frame/modules/systeminfo/logoitem.cpp
src/frame/widgets/titlevalueitem.cpp
src/frame/widgets/titlevalueitem.h

fix: long processor name screws up layout.

---

src/frame/dbuscontrolcenterservice.cpp
src/frame/frame.cpp

fix: dbus method 'rect' returns wrong results after screen rotation.

---

src/frame/widgets/switchwidget.cpp

fix: switch widget caption text overflows.

---

src/frame/widgets/switchwidget.cpp

fix: set word wrap on switch widget construction.

---

src/frame/modules/accounts/accountsdetailwidget.cpp
src/frame/modules/network/connectioneditpage.cpp
src/frame/modules/network/vpnpage.cpp

fix: incorrect layout of various pages.

---

src/frame/modules/accounts/accountsworker.cpp
src/frame/modules/accounts/modifypasswordpage.cpp
src/frame/modules/accounts/user.cpp
src/frame/modules/accounts/user.h

chore(accounts): adapt the user's status without nopassword

---

CMakeLists.txt
src/frame/CMakeLists.txt
src/frame/main.cpp
src/frame/navigation/navdelegate.cpp
src/frame/navigation/navdelegate.h
src/frame/navigation/navmodel.cpp
src/frame/navigation/navmodel.h
src/frame/window/constant.h
src/frame/window/mainwindow.cpp
src/frame/window/mainwindow.h

refactor: add window mode

---

src/frame/window/modules/personalization/personalizationgeneral.cpp

For the deepin version add window rounding settings
Log: For the deepin version add window rounding settings

feat: Adding Window Rounding Settings

---

src/frame/window/modules/personalization/personalizationgeneral.cpp

This reverts commit 8369a1f0b2f25f370aaa0ea79102b9748e978d9d.
Log: Can mirror source is not ready yet, it is not displayed yet

Revert "feat: 社区版开启智能镜像源"

---

src/frame/modules/personalization/personalizationmodel.cpp
src/frame/modules/personalization/personalizationmodel.h
src/frame/modules/personalization/personalizationwork.cpp
src/frame/modules/personalization/personalizationwork.h
src/frame/window/modules/personalization/personalizationgeneral.cpp
src/frame/window/modules/personalization/personalizationgeneral.h
src/frame/window/modules/personalization/personalizationmodule.cpp

Fix layout errors
Log: Fix layout errors in the community version of deepin

fix: Fix "Transparency slider" distortion by layout compression

---

.github/workflows/build.yaml

fix:   github action

---

src/frame/modules/personalization/personalizationmodel.cpp
src/frame/modules/personalization/personalizationmodel.h
src/frame/modules/personalization/personalizationwork.cpp
src/frame/modules/personalization/personalizationwork.h
src/frame/window/modules/personalization/personalizationgeneral.cpp
src/frame/window/modules/personalization/personalizationgeneral.h
src/frame/window/modules/personalization/personalizationmodule.cpp

Fix the bug that the status will be invalid after each modification of custom rounded corners, but after each logout or restart of the system.
Log: Fix Custom rounded corners flaw

fix: Fix Custom rounded corners flaw

---

CMakeLists.txt
com.deepin.dde.ControlCenter.service
dde-control-center-wapper
src/frame/main.cpp

refactor: remove wrapper

---

src/frame/modules/bluetooth/bluetoothworker.cpp
src/frame/modules/bluetooth/bluetoothworker.h
src/frame/window/modules/bluetooth/bluetoothmodule.cpp
src/frame/window/modules/bluetooth/bluetoothmodule.h
src/frame/window/modules/bluetooth/bluetoothwidget.cpp
src/frame/window/modules/bluetooth/bluetoothwidget.h

split thread
Log:
Change-Id: I386df4f0694eb7b0f271609c427aa7e81f08f22f

perf(bluetooth): move to low priority thread

---

src/frame/modules/bluetooth/bluetoothworker.cpp

Adapter threads are inconsistent
Log:
Bug: https://pms.uniontech.com/zentao/bug-view-56138.html
Bug: https://pms.uniontech.com/zentao/bug-view-56137.html

fix(bluetooth): multi thread error

---

dde-control-center.desktop

fix: cannot load extra paramenters

---

src/frame/modules/update/updatework.h
src/frame/window/modules/update/updatemodule.cpp

missing DISABLE_ACTIVATOR
Log:

fix: build failed

---

.github/workflows/build.yaml

feat: update github action

---

src/frame/window/modules/systeminfo/nativeinfowidget.cpp

hide version
Log: hide version on commonity
Task: https://pms.uniontech.com/zentao/task-view-57489.html

feat: hide version on commonity

---

.github/workflows/build.yaml

refactor: remove action notify

---

src/frame/window/modules/systeminfo/systeminfowidget.cpp

only deepin community version have
Log:

fix: hide end user license on other linux

---

src/frame/CMakeLists.txt
src/frame/window/mainwindow.cpp

Log: authentication module make error in other distribution
Task: https://github.com/linuxdeepin/developer-center/issues/2245

feat: add build flag to disable authentication module

---

debian/control
src/frame/CMakeLists.txt

添加 Qt5XkbCommonSupport 解决构建找不到头文件的错误
Log: 解决社区版环境下构建错误
Influence: 构建 打包
Change-Id: Ic3c245baf9860f0aa6df724627ae28a4e15518e9

fix: 解决社区版环境下构建错误

---

archlinux/PKGBUILD
archlinux/remove-auth.patch

add archlinux build

---

archlinux/PKGBUILD

missing Qt5WaylandClientConfig.cmake
Log:

fix: missing qt5-wayland package

---

debian/changelog

规范changelog，以便通过编译
Log: 规范changelog
Influence: 编译
Change-Id: I8d2f0452468d55809ddf30f0e9559af17772164c

chore: changelog去掉第一个-1

---

src/frame/window/modules/datetime/clockitem.cpp
src/frame/window/modules/datetime/formatsetting.cpp

feat: 控制中心新增短日期格式设置，使任务栏和锁屏界面按照设置的格式去显示
Log: 控制中心新增短日期格式显示
Task: https://pms.uniontech.com/task-view-174019.html
Influence: 控制中心短日期格式设置
Change-Id: If296c55a0e5e7ebbb04406014437a0cbce9cf689

feat: 控制中心新增短日期格式显示

---

configs/org.deepin.dde.control-center.datetime.json
src/frame/CMakeLists.txt
src/frame/modules/datetime/datetimemodel.cpp
src/frame/modules/datetime/datetimemodel.h
src/frame/modules/datetime/datetimework.cpp
src/frame/modules/datetime/datetimework.h
src/frame/window/modules/datetime/currencyformat.cpp
src/frame/window/modules/datetime/currencyformat.h
src/frame/window/modules/datetime/datetimemodule.cpp
src/frame/window/modules/datetime/formatsetting.cpp
src/frame/window/modules/datetime/formatsetting.h
src/frame/window/modules/datetime/numberformat.cpp
src/frame/window/modules/datetime/numberformat.h

1.新增时间日期-格式设置-新增数字和货币格式
2.添加dconfig控制，以及翻译显示
Log: 新增数字和货币格式
Task: https://pms.uniontech.com/task-view-154485.html###
Influence: 新需求
Change-Id: I8497e60b6e16d9653749d00e292905878df90df2

feat: 新增格式设置

---

src/frame/window/modules/sound/soundmodule.cpp
src/frame/window/modules/sound/speakerpage.cpp

补充云平台声音搜索支持
Log: 云平台声音搜索支持
Bug: https://pms.uniontech.com/bug-view-152867.html
Influence: 声音
Change-Id: I15d0778379dab4976249a391a62b99d93ccd61bb

fix(audio): 云平台声音搜索支持

---

src/frame/window/modules/datetime/datetimemodule.cpp

更新翻译后刷新数据
Log: 更新翻译后刷新数据
Influence: 搜索
Bug: https://pms.uniontech.com/bug-view-152951.html
Bug: https://pms.uniontech.com/bug-view-152957.html
Change-Id: I56ff9c4095cb0c76f49de6856863873ea57754b3

fix: 更新翻译后刷新数据

---

src/frame/modules/datetime/datetimework.cpp
src/frame/window/modules/datetime/numberformat.cpp
src/frame/window/modules/datetime/numberformat.h

两个账户设置不同语言,导致数据不同步问题
Log: 处理两个账户设置不同导致问题
Influence: 双账户语言不同导致问题
Bug: https://pms.uniontech.com/bug-view-152933.html
Change-Id: I5588f3131654bb37fe9ff1d3ed962ac6a29da20b

fix: 修改两个账户不同语言导致不同步问题

---

src/frame/window/modules/sound/microphonepage.cpp
src/frame/window/modules/sound/soundmodule.cpp

移除云平台输入设备和输出设备的搜索项
Log: 移除云平台输入设备和输出设备的搜索项
Bug: https://pms.uniontech.com/bug-view-152855.html
Influence: 声音
Change-Id: I165147314754a610867f9c91e6048a176bfe4f1e

fix(audio): 移除云平台输入设备和输出设备的搜索项

---

configs/org.deepin.dde.control-center.datetime.json
src/frame/window/modules/datetime/numberformat.cpp

增加“示例”配置显示
Log: 增加“示例”是否显示的配置
Influence: 格式设置配置
Bug: https://pms.uniontech.com/bug-view-152895.html
Change-Id: Ic79dddcf5571b49eecb221f27f7d029a01436279

fix: 增加“示例”配置显示

---

configs/org.deepin.dde.control-center.datetime.json
src/frame/window/modules/datetime/currencyformat.cpp
src/frame/window/modules/datetime/datetimemodule.cpp
src/frame/window/modules/datetime/numberformat.cpp

dsg以小写字母开头
Log: dsg配置以小写字母开头
Bug: https://pms.uniontech.com/bug-view-152895.html
Influence: 命名规范
Change-Id: I920b03efcb1e3460eaa13a26b736e316340f2071

fix: 规范dsg配置命名，首字母改成小写

---

src/frame/window/modules/datetime/currencyformat.cpp
src/frame/window/modules/datetime/datetimemodule.cpp
src/frame/window/modules/datetime/numberformat.cpp

添加货币格式标题搜索
Log: 添加货币格式标题搜索
Influence: 搜索
Task: https://pms.uniontech.com/task-view-177621.html
Change-Id: I57594dc0976d47832800fbb8602cbb219a8d45f3

fix: 添加货币格式标题搜索

---

src/frame/window/modules/datetime/currencyformat.cpp
src/frame/window/modules/datetime/datetimemodule.cpp
src/frame/window/modules/datetime/datetimemodule.h
src/frame/window/modules/datetime/formatsetting.cpp
src/frame/window/modules/datetime/formatsetting.h
src/frame/window/modules/datetime/numberformat.cpp

修改时间格式布局
Log: 修改时间格式布局
Influence: 时间格式布局
Bug: https://pms.uniontech.com/bug-view-152835.html
Change-Id: If4c8d92db1d98206d0230598738f655ae677c449

fix: 修改时间格式布局

---

configs/org.deepin.dde.control-center.update.json
src/frame/modules/update/updateiteminfo.cpp
src/frame/modules/update/updateiteminfo.h
src/frame/modules/update/updatework.cpp
src/frame/modules/update/updatework.h
src/frame/window/modules/display/displaymodule.cpp
src/frame/window/modules/update/systemupdateitem.cpp
src/frame/window/modules/update/updatesettingitem.cpp
src/frame/window/utils.h

修改获取日志的方式;
以前:从uos-release-note安装的日志文件中获取更新日志
现在:从通过http协议从服务器获取日志
Log: 从服务器获取更新日志
Task: https://pms.uniontech.com/task-view-174009.html
Influence: 更新日志展示
Change-Id: Id969ff0a04bf33e4c077e2bd139ae08cf8b18b45

feat: 从服务器获取更新日志

---

include/widgets/detailinfoitem.h
src/frame/widgets/detailinfoitem.cpp

原因：QLabel没有设置setOpenExternalLinks属性
Log: 修复详情点击超链接没有反应的问题
Bug: https://pms.uniontech.com/bug-view-153797.html
Influence: 点击更新详情中的超链接
Change-Id: I629bf9b10367e3e35a5f95211bc6ecb6f122c171

fix: 详情点击超链接没有反应

---

src/frame/window/modules/commoninfo/commoninfowork.cpp

兼容老的埋点服务,避免影响低版本兼容性
Log:
Bug: https://pms.uniontech.com/bug-view-154711.html
Influence: 用户体验计划
Change-Id: I491dcc8d03052e44cc2fd1c8fc2437e3a192a8cc

fix: 兼容旧的埋点服务

---

src/frame/window/modules/accounts/accountsdetailwidget.cpp
src/frame/window/modules/accounts/accountsdetailwidget.h
src/frame/window/modules/accounts/usergroupspage.cpp
src/frame/window/modules/accounts/usergroupspage.h

调整用户组相关UI界面显示，优化显示效果
Log: 解决控制中心用户组UI界面显示存在问题的问题
Bug: https://pms.uniontech.com/bug-view-154257.html
Influence: 控制中心用户组显示
Change-Id: I2314974beefa29788e0fa78a5df9c978099166b7

fix: 控制中心用户组UI界面显示存在问题

---

debian/control

不再推荐安装旧的埋点服务
Log: 不再推荐安装旧的埋点服务
Task: https://pms.uniontech.com/task-view-186689.html
Influence: 不再推荐安装旧的埋点服务
Change-Id: If6a7eb4db6f671216f55e90e06df139126ff9dbb

chore: 不再推荐安装旧的埋点服务

---

src/frame/modules/update/updatework.cpp
src/frame/modules/update/updatework.h
src/frame/window/modules/update/systemupdateitem.cpp
src/frame/window/modules/update/updatesettingitem.cpp

适配社区版更新日志，区分内测日志和正式版日志
Log: 适配社区版更新日志
Task: https://pms.uniontech.com/task-view-188181.html
Influence: 社区版更新日志
Change-Id: Id44cf7cf0ab922e13f45a601ea714dd9e5b1f316

feat: 适配社区版更新日志

---

src/frame/modules/sound/soundmodel.cpp
src/frame/modules/sound/soundmodel.h
src/frame/modules/sound/soundworker.cpp
src/frame/modules/sound/soundworker.h

华为输入的monitor stream 非 default source, 需要创建多个stream。
Log: 修复华为输入设备无反馈问题
Bug: https://pms.uniontech.com/bug-view-158213.html
Influence: 声音-输入-反馈音量
Change-Id: I8b8e417fc98f911f70dd6d338923e67fbb9b233a

fix(audio): 华为输入设备无反馈

---

src/frame/modules/update/updatework.cpp
src/frame/modules/update/updatework.h

存在下载或者安装时,不再调用检查更新
Log: 修复下载或安装时偶然触发检查更新问题
Bug: https://pms.uniontech.com/bug-view-155447.html
Influence: 检查更新
Change-Id: Ic091ba16e7fe9ee1b2148611ff48518a0b5caca1

fix: 修复下载或安装时偶然触发检查更新问题

---

src/frame/modules/update/updatework.cpp

fix: 解决内测渠道安装、卸载内测源失败的问题
在安装卸载内测源之前执行一次apt update
避免在无索引文件的情况下安装卸载失败
Log: 优化内测渠道开启流程
Bug: https://pms.uniontech.com/bug-view-155547.html

fix: 解决内测渠道安装、卸载内测源失败的问题

---

src/frame/modules/update/updatework.cpp

由于内测渠道是根据机器码做做唯一标识
重装系统后机器码不变,会导致无需再次申请就可直接加入内测
Log: 优化内测渠道加入流程

fix: 避免重装系统后,未申请就自动加入内测渠道

---

src/frame/window/modules/accounts/accountsdetailwidget.cpp
src/frame/window/modules/accounts/accountsdetailwidget.h

修改用户组功能，仅在专业版和服务器显示
Log: 修改用户组功能的显示范围
Bug: https://pms.uniontech.com/bug-view-156207.html
Influence: 账户-用户组，仅在专业版和服务器显示

fix(account): 修改用户组功能，仅在专业版和服务器显示

---

include/widgets/utils.h
src/frame/modules/accounts/accountsworker.cpp
src/frame/modules/accounts/accountsworker.h
src/frame/window/modules/accounts/securityquestionspage.cpp
src/frame/window/modules/accounts/securityquestionspage.h
src/reset-password-dialog/utils.h

应国密需求，控制中心使用sm3算法
Log: 控制中心使用sm3算法
Task: https://pms.uniontech.com/task-view-184563.html
Influence: 修改密码、密保问题、重置密码
Change-Id: I0293e63e3bb7132d81e59227ab8bea8bd8fa7402

feat: 控制中心使用sm3算法

---

src/frame/modules/update/updatework.cpp
src/frame/modules/update/updatework.h

该问题修复由lastore-daemon完成，移除新增的逻辑
This reverts commit 19d5765c
Change-Id: I346dd7e648e9e2d923bc1e479e6e01fb3d8b5df7

Revert "fix: 修复下载或安装时偶然触发检查更新问题"

---

archlinux/PKGBUILD

dde-network-utils replace to dde-network-core
Log:

chore: update makedepends

---

src/frame/modules/authentication/fingermodel.cpp

修改指纹录入状态提示
Log: 调整指纹录入提示
Task: https://pms.uniontech.com/task-view-198139.html
Influence: 指纹录入
Change-Id: I9d0c34be46f590d08982f50b0298ee72e3972570

feat: 调整指纹录入提示

---

src/frame/modules/personalization/personalizationwork.cpp

华为klv调用窗管接口loadEffect后，返回值是false，但实际上是设置成功了
修改将以前返回值改为用isEffectLoaded判断接口是否设置成功
Log: 规避窗管接口返回值错误问题
Influence: 窗口移动时启用透明特效功能
Bug: https://pms.uniontech.com/bug-view-164453.html
Change-Id: Ib047f4d206f3487af68b4d16d12c218db0f81155

fix: 使用isEffectLoaded的返回值确认窗管接口调用真实情况

---

src/frame/window/modules/systeminfo/privacypolicywidget.cpp
src/frame/window/modules/systeminfo/systeminfowidget.cpp

针对服务器版本，控制中心隐藏系统信息版本协议二级菜单，并修改对应隐私策略
Log: 服务器版本控制中心隐藏版本协议与隐私政策文案修改
Task: https://pms.uniontech.com/task-view-207089.html
Influence: 控制中心系统信息正常显示
Change-Id: I7a3d28d038a0ac9fd35a0c3e5b9719eb8ed65a92

feat: 控制中心隐藏版本协议与隐私政策文案修改

---

include/widgets/comboxwidget.h
src/frame/modules/personalization/personalizationmodel.cpp
src/frame/modules/personalization/personalizationmodel.h
src/frame/modules/personalization/personalizationwork.cpp
src/frame/modules/personalization/personalizationwork.h
src/frame/widgets/comboxwidget.cpp
src/frame/window/modules/personalization/personalizationgeneral.cpp
src/frame/window/modules/personalization/personalizationgeneral.h
src/frame/window/modules/personalization/personalizationmodule.cpp
src/frame/window/modules/personalization/perssonalizationthemewidget.cpp

解决虚拟机窗管接口获取数据异常问题
Log: 解决虚拟机问题
Influence: 虚拟机
Bug: https://pms.uniontech.com/bug-view-163031.html
Change-Id: Icc6a4c14721027f2aab7e3def2a4d4ea8f59b729

fix: 解决虚拟机窗管接口错误问题

---

include/interface/frameproxyinterface.h
src/frame/modules/personalization/model/fontsizemodel.cpp
src/frame/window/mainwindow.cpp
src/frame/window/mainwindow.h
src/frame/window/modules/personalization/personalizationfontswidget.cpp
src/frame/window/modules/personalization/personalizationfontswidget.h
src/frame/window/modules/personalization/personalizationmodule.cpp
src/frame/window/search/searchmodel.cpp
src/frame/window/search/searchmodel.h
src/frame/window/search/searchwidget.cpp
src/frame/window/search/searchwidget.h
src/frame/window/utils.h

跟随字体大小变化改变搜索数据
Log:
Influence: 字体大小变化，搜索数据显示
Bug: https://pms.uniontech.com/bug-view-164951.html
Change-Id: I8c759f799efaae54da3fb33a1b995d4510184be4

fix: 字体大小变化后，搜索数据需要更新

---

include/interface/frameproxyinterface.h
src/frame/window/mainwindow.cpp
src/frame/window/mainwindow.h
src/frame/window/modules/personalization/personalizationmodule.cpp
src/frame/window/search/searchmodel.cpp

修改了接口定义的头文件，会导致插件需要重新编译
Log: 插件编译问题
Influence: 编译
Bug: https://pms.uniontech.com/bug-view-164951.html
Change-Id: Iaeb6af3487add24f96ebf980fbbc97776300f91d

fix: 解决插件编译问题

---

src/frame/window/mainwindow.cpp
src/frame/window/mainwindow.h
src/frame/window/protocolfile.cpp

根据配置文件决定是否展示mil协议和是否使用sync模块
Log:
Task: https://pms.uniontech.com/task-view-214999.html
Influence: 最终用户许可协议修改和uosID版本
Change-Id: I43d5a8af6f9530c1bfb62981b5d28ddfc4417fa3

feat: mil合主线

---

configs/org.deepin.dde.control-center.power.json
src/frame/modules/power/powermodel.cpp
src/frame/modules/power/powermodel.h
src/frame/modules/power/powerworker.cpp
src/frame/modules/power/powerworker.h
src/frame/window/modules/power/usebatterywidget.cpp
src/frame/window/modules/power/usebatterywidget.h
src/frame/window/modules/power/useelectricwidget.cpp
src/frame/window/modules/power/useelectricwidget.h

增加待机时间颗粒度，修改待机时间默认值，配置支持修改
Log: 增加待机时间颗粒度
Task: https://pms.uniontech.com/task-view-212937.html
Influence: 电源管理时间设置

feat: 增加待机时间颗粒度

---

src/frame/window/modules/accounts/usergroupspage.cpp

由于等保功能做的并不完善，在退出等保后，相关用户组信息并没有进行清除
因此在开启等保或者退出等保后，我们需要其用户组编辑策略
Log: 调整等保三级用户组编辑策略
Task: https://pms.uniontech.com/task-view-212851.html
Change-Id: I4fe0b42d73803d9ca236d5b66339dff8bf3cf83b

feat: 调整等保三级用户组编辑策略

---

configs/org.deepin.dde.control-center.accounts.json
include/widgets/utils.h
src/frame/CMakeLists.txt
src/frame/modules/accounts/accounts.qrc
src/frame/modules/accounts/accountsworker.cpp
src/frame/modules/accounts/accountsworker.h
src/frame/modules/accounts/themes/common/icons/security_key_copy.svg
src/frame/window/modules/accounts/accountsdetailwidget.cpp
src/frame/window/modules/accounts/accountsdetailwidget.h
src/frame/window/modules/accounts/accountsmodule.cpp
src/frame/window/modules/accounts/securitykeydisplaydialog.cpp
src/frame/window/modules/accounts/securitykeydisplaydialog.h
src/frame/window/utils.h
src/reset-password-dialog/CMakeLists.txt
src/reset-password-dialog/icons/unbind_dark.svg
src/reset-password-dialog/icons/unbind_light.svg
src/reset-password-dialog/passwordwidget.cpp
src/reset-password-dialog/passwordwidget.h
src/reset-password-dialog/resetpassworddialog.cpp
src/reset-password-dialog/resetpassworddialog.h
src/reset-password-dialog/resetpasswordworker.cpp
src/reset-password-dialog/resetpasswordworker.h
src/reset-password-dialog/securitykeywidget.cpp
src/reset-password-dialog/securitykeywidget.h
src/reset-password-dialog/utils.h

1.控制中心新增“启用安全密钥”开关；--done
2.展示安全密钥页面；--done
3.reset-password-dialog安全密钥功能开关；
4.加密、解密安全密钥；
Log: 新增功能-安全密钥重置密码
Influence: 没有网络时通过安全密钥修改密码
Task: https://pms.uniontech.com/task-view-212943.html
Change-Id: I2d9277a61c40d25b5d916f395895378c447a599c

feat: Add security key modify password

---

src/frame/window/modules/accounts/accountsdetailwidget.cpp
src/frame/window/modules/accounts/securitykeydisplaydialog.cpp
src/frame/window/modules/accounts/securityquestionspage.cpp
src/reset-password-dialog/resetpassworddialog.cpp
src/reset-password-dialog/securitykeywidget.cpp

更新ts文言错误的内容
Log: 更新翻译
Influence: 翻译
Task: https://pms.uniontech.com/task-view-212943.html
Change-Id: I757c5b26cf1059a1840bbaabf6f1496e6f6910e3

feat: update translation

---

src/frame/window/modules/commoninfo/developermodewidget.cpp

按产品要求，修复开启开发者模式提示文案
Log: 开发者模式离线开启优化,修改开启开发者模式提示文案
Task: https://pms.uniontech.com/task-view-222749.html
Influence: 修改开启开发者模式提示文案

feat: 修改开启开发者模式提示文案

---

src/frame/window/modules/accounts/securitykeydisplaydialog.cpp

增加安全密钥标题
修改dialog高度
Log: Add Security Keys title
Influence: 标题
Bug: https://pms.uniontech.com/bug-view-175905.html
Change-Id: Ibb8a6eff00ba6cea51be2bcbfcc901e5fe1c56f8

fix: Add Security Keys title

---

src/frame/window/modules/personalization/personalizationthemelist.cpp

按UI要求适当调整图标和光标主题界面左边距大小
Log: 按UI要求适当调整图标和光标主题界面左边距大小
Bug: https://pms.uniontech.com/bug-view-173633.html
Influence: 按UI要求适当调整图标和光标主题界面左边距大小

fix: 按UI要求适当调整图标和光标主题界面左边距大小

---

translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_cs.ts
translations/dde-control-center_da.ts
translations/dde-control-center_de.ts
translations/dde-control-center_en.ts
translations/dde-control-center_en_US.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_nl.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_sl.ts
translations/dde-control-center_sq.ts
translations/dde-control-center_tr.ts
translations/dde-control-center_ug.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts
translations/reset-password-dialog_az.ts

更新安全密钥翻译
Log: update translations
Influence: 翻译
Bug: https://pms.uniontech.com/bug-view-175905.html
Change-Id: I4354f5d00ecf23737699729b5f83550cddc23feb

fix: update translations

---

src/frame/modules/mouse/mousedbusproxy.cpp
src/frame/modules/mouse/mousedbusproxy.h
src/frame/modules/mouse/mousemodel.cpp
src/frame/modules/mouse/mousemodel.h
src/frame/modules/mouse/mouseworker.cpp
src/frame/modules/mouse/mouseworker.h
src/frame/window/modules/mouse/mousemodule.cpp
src/frame/window/modules/mouse/touchpadsettingwidget.cpp
src/frame/window/modules/mouse/touchpadsettingwidget.h

触控板通用开关控制中心适配
Log: 触控板通用开关控制中心适配
Task: https://pms.uniontech.com/task-view-222751.html
Influence: 触控板
Change-Id: I44763706adc404e99e8aafeb51fba8a41017b576

feat: 触控板通用开关控制中心适配

---

src/frame/modules/mouse/mousedbusproxy.cpp
src/frame/modules/mouse/mousedbusproxy.h
src/frame/modules/mouse/mousemodel.cpp
src/frame/modules/mouse/mousemodel.h
src/frame/modules/mouse/mouseworker.cpp
src/frame/modules/mouse/mouseworker.h
src/frame/window/modules/mouse/mousemodule.cpp
src/frame/window/modules/mouse/touchpadsettingwidget.cpp
src/frame/window/modules/mouse/touchpadsettingwidget.h

触控板通用开关控制中心适配
Log: 触控板通用开关控制中心适配
Task: https://pms.uniontech.com/task-view-222751.html
Influence: 触控板
Change-Id: I44763706adc404e99e8aafeb51fba8a41017b576 (cherry picked from commit https://github.com/linuxdeepin/dde-control-center/commit/dcfd45c5aa22c14ae8589dda1f799268be376434)

触控板通用开关控制中心适配

---

translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_cs.ts
translations/dde-control-center_da.ts
translations/dde-control-center_de.ts
translations/dde-control-center_en.ts
translations/dde-control-center_en_US.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_nl.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_sl.ts
translations/dde-control-center_sq.ts
translations/dde-control-center_tr.ts
translations/dde-control-center_ug.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts
translations/dialogs_pt_BR.ts
translations/reset-password-dialog_pt_BR.ts

更新翻译
Log: 更新翻译
Task：https://pms.uniontech.com/task-view-222751.html 
Influence: 翻译
Change-Id: I37c52a36675c912786dcce36443db39832da7328

feat: 更新翻译

---

src/frame/window/modules/accounts/securitykeydisplaydialog.cpp

增加复制成功提示
Log: 增加复制成功提示
Bug: https://pms.uniontech.com/bug-view-175965.html
Influence: 提示
Change-Id: Ie9d18f9a94d73ff668c1df5904670fa4196532e0

fix:  添加复制成功提示

---

translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_cs.ts
translations/dde-control-center_da.ts
translations/dde-control-center_de.ts
translations/dde-control-center_en.ts
translations/dde-control-center_en_US.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_nl.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_sl.ts
translations/dde-control-center_sq.ts
translations/dde-control-center_tr.ts
translations/dde-control-center_ug.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts
translations/reset-password-dialog_cs.ts

增加复制成功提示翻译
Log: 增加复制成功提示翻译
Bug: https://pms.uniontech.com/bug-view-175965.html
Influence: 提示翻译
Change-Id: Ieeebd04e38497dd23d378e465190d0324a75d01b

fix:  添加复制成功提示翻译

---

src/frame/window/modules/authentication/addirisinfodialog.cpp

未正常设置录入框widget
Log: 虹膜录入修复
Bug: https://pms.uniontech.com/task-view-232291.html
Influence: 虹膜录入
Change-Id: I83a3f63664a405d944380c0c50118d9e209b46a1

fix: 修复虹膜录入不能正常显示录入框问题

---

src/frame/modules/systeminfo/systeminfowork.cpp
src/frame/window/mainwindow.cpp
src/frame/window/modules/notification/notificationmodule.cpp

优化程序启动速度
Log: 优化程序启动速度
Bug: https://pms.uniontech.com/bug-view-178945.html
Influence: 优化程序启动速度

fix: 优化程序启动速度

---

src/frame/modules/systeminfo/systeminfomodel.h
src/frame/modules/systeminfo/systeminfowork.cpp
src/frame/window/modules/commoninfo/commoninfowidget.cpp
src/frame/window/modules/commoninfo/commoninfowork.cpp
src/frame/window/modules/systeminfo/nativeinfowidget.cpp
src/frame/window/utils.h

修复发行版产品名和产品版本的显示
隐藏非 deepin 发行版“用户体验”，“版本”
Log：为非 deepin/uos 优化模块的启用或隐藏
Influence: 关于/系统信息，通用/用户体验计划

feat: 优化非 deepin/uos 下模块启用或隐藏

---

src/frame/modules/display/display.qrc
src/frame/modules/display/monitorproxywidget.cpp
src/frame/modules/display/themes/common/dcc-primary.svg

显示模块中显示器示意图主副屏差异化显示优化
Log: 显示模块中显示器示意图主副屏差异化显示优化
Task: https://pms.uniontech.com/task-view-212889.html
Influence: 主副屏差异化显示优化

feat: 显示模块中显示器示意图主副屏差异化显示优化

---

src/frame/modules/display/monitorproxywidget.cpp

显示模块中显示器示意图主副屏差异化显示优化,根据UI设计调整背景颜色和边框颜色
Log: 显示模块中显示器示意图主副屏差异化显示优化
Task: https://pms.uniontech.com/task-view-212889.html
Influence: 主副屏差异化显示优化

 feat: 显示模块中显示器示意图主副屏差异化显示优化,根据UI设计调整背景颜色和边框颜色

---

.tx/deepin.conf
debian/changelog

update changelog to 5.6.3
Log: update changelog to 5.6.3
Influence: 构建
Change-Id: I03f7138e22331666697764c24a79a50eb559f4d5

chore: update changelog to 5.6.3

---

.reuse/dep5
src/frame/modules/accounts/usermodel.cpp

LDAP账户的相关信息由域服务器管理，故隐藏处理
Log: 实现控制中心隐藏LDAP账户相关配置项
Task: https://pms.uniontech.com/task-view-235581.html
Influence: 控制中心LDAP账户页面显示
Change-Id: Ie3ab16b16f1ab61d908d45b3222dae537d8699c6

feat: 控制中心隐藏LDAP账户相关配置项

---

configs/org.deepin.dde.control-center.personalization.json
src/frame/modules/personalization/personalizationmodel.cpp
src/frame/modules/personalization/personalizationmodel.h
src/frame/modules/personalization/personalizationwork.cpp
src/frame/modules/personalization/personalizationwork.h
src/frame/window/modules/personalization/personalizationfontswidget.cpp
src/frame/window/modules/personalization/personalizationfontswidget.h
src/frame/window/modules/personalization/personalizationgeneral.cpp
src/frame/window/modules/personalization/personalizationgeneral.h
src/frame/window/modules/personalization/personalizationmodule.cpp
src/frame/window/utils.h

1、个性化模块添加界面模式设置
2、处理搜索数据和dconfig配置
3、处理紧凑模式开启或关闭时系统字体大小设置
Log: 个性化提供界面模式设置
Task: https://pms.uniontech.com/task-view-212923.html
Influence: 个性化提供界面模式设置

feat: 个性化提供界面模式设置

---

translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_cs.ts
translations/dde-control-center_da.ts
translations/dde-control-center_de.ts
translations/dde-control-center_en.ts
translations/dde-control-center_en_US.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_nl.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_sl.ts
translations/dde-control-center_sq.ts
translations/dde-control-center_tr.ts
translations/dde-control-center_ug.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

更新翻译文件
Log: 个性化提供界面模式设置
Task: https://pms.uniontech.com/task-view-212923.html
Influence: 个性化提供界面模式设置

feat: feat: 个性化提供界面模式设置,更新翻译文件

---

src/frame/window/modules/authentication/addirisinfodialog.cpp

成功未加翻译
Log: 虹膜录入优化
Bug: https://pms.uniontech.com/bug-view-182151.html
Influence: 虹膜录入
Change-Id: Id340ed5a351675550a9b09521aa91d06bcab3bda

fix: 修复虹膜录入失败后的界面部分未翻译问题

---

CMakeLists.txt

Log: plugin-test1 use dtkwidget but not include it

chore: fix plugin-test1

---

src/plugin-commoninfo/window/bootwidget.cpp

chore: fix misspelled function name

---

CMakeLists.txt

Log: add option for private plugins

chore: add option for private plugins

---

CMakeLists.txt

Log: cxxflags missing origin value

chore: cxxflags in CMakeLists.txt

---

CMakeLists.txt
README.md
src/frame/pluginmanager.cpp
src/plugin-adapterv20tov23/pluginmanagerv20.cpp

Log: add option to set module install path

feat: dont use hardcode for module path

---

src/plugin-accounts/window/avatarwidget.cpp

use smooth not fast
Log: fix vage icon
issue链接：https://github.com/linuxdeepin/developer-center/issues/3593

fix: vage icon in plugin-accounts

---

.github/workflows/backup-to-gitlab.yml
.github/workflows/call-chatOps.yml
.github/workflows/call-clacheck.yml
.github/workflows/call-commitlint.yml
.github/workflows/call-license-check.yml
.github/workflows/cppcheck.yml

bring back some basic ci
Log: call-commitlint and chatops ci
Influence: github actions
Change-Id: Iad29b9379799b9b6bd1b794d247fb1e57928da41

添加除了build以外的基本的ci

---

.github/workflows/call-auto-tag.yml
.github/workflows/call-build-deb.yml
.github/workflows/call-build-distribution.yml
.github/workflows/call-tag-build.yml

add build ci
Log: add build ci

chore: add buildci

---

CMakeLists.txt
debian/rules

Log:
use MODULE_INSTALL_DIR as install target
set module path /usr/lib in debian/rules
remove duplicate -mieee

feat: use MODULE_INSTALL_DIR as install target

---

archlinux/PKGBUILD
debian/dde-control-center.install
debian/rules

add buildpackage
Log: buildpackage

chore: buildpackage ci

---

CMakeLists.txt

chore: fix dcc-interface install dir

---

CMakeLists.txt
debian/rules

add sovname for dcc-interface and dcc-widget
Log: sovname

chore: add sovername

---

debian/dde-control-center-dev.install
debian/dde-control-center.install

fix: soname install

---

src/frame/pluginmanager.cpp

chore: load modules in the old modules directory

---

src/frame/mainmodule.cpp

Log: fix the design of center listview
issue: https://github.com/linuxdeepin/developer-center/issues/3597

fix: align of center widget

---

src/plugin-update/operation/updatework.cpp

chore: use std::sort not qsort

---

.reuse/dep5
.tx/deepin.conf
CMakeLists.txt
debian/changelog

chore: update changelog

---

src/widgets/titledslideritem.cpp

seems they foget to set the lable value on title
Log: bring back value on title
resolve: https://github.com/linuxdeepin/developer-center/issues/3737

fix: title slider item

---

src/frame/pluginmanager.cpp

Correct a typo in pluginmanager.cpp

chore: correct a typo in pluginmanager.cpp

---

src/frame/main.cpp
src/frame/pluginmanager.cpp

1. just check dbus option to start
2. fix the logic of async load module
3. fix the commandline option of dbus Log: async bug
resolve: https://github.com/linuxdeepin/developer-center/issues/3606

fix: fix the bug of async

---

.clang-format
.reuse/dep5

Log: add clang-format for edit

chore: add clang-format

---

include/interface/hlistmodule.h
include/interface/moduleobject.h
include/interface/namespace.h
include/interface/pagemodule.h
include/interface/plugininterface.h
include/interface/vlistmodule.h

chore: add explicit to strict the construction

---

src/plugin-display/window/scalingwidget.cpp
src/plugin-mouse/window/generalsettingwidget.cpp
src/plugin-personalization/window/personalizationdesktopmodule.cpp
src/plugin-personalization/window/personalizationthememodule.cpp
src/plugin-power/window/generalmodule.cpp
src/widgets/titledslideritem.cpp

我完全搞错了，这个title应该是使用时候设置，因为实际上这里的需求千奇百怪，不是仅仅百分比

fix: titledslideritem title

---

src/plugin-personalization/window/personalizationthememodule.cpp

fix: textsetting title

---

src/plugin-personalization/window/personalizationthememodule.cpp

resolve: https://github.com/linuxdeepin/developer-center/issues/3866
active的颜色错了

chore: wrong active color

---

src/plugin-personalization/window/widgets/personalizationthemelist.cpp

Log: don't use id, use Name as title
Task: https://github.com/linuxdeepin/dde-control-center/issues/1243

feat: use Name as icon title

---

src/plugin-notification/window/notificationmodule.cpp

resolve: https://github.com/linuxdeepin/developer-center/issues/3735
这个用的方法太诡异了，一开始都没有发现。。当然还是要重写最好

fix: notifypage align

---

src/interface/tabview.cpp

Selected tab highlight area is covered by next tab. rectForIndex is incorrect. Adjust position to avoid cover.
Log: fix selected tab highlight area is clipped

fix: selected tab highlight area is clipped

---

src/frame/main.cpp
src/frame/mainwindow.cpp
src/frame/mainwindow.h
src/frame/pluginmanager.cpp
src/frame/pluginmanager.h
src/frame/utils.h

for plugin developer to develop plugin
Log: add debug flag

feat: add debug flag

---

src/frame/pluginmanager.cpp

Log: donot check it again, it is done in main

chore: remove useless line

---

src/plugin-systeminfo/window/systeminfomodule.cpp

修复非deepin发行版上显示鉴权选项的bug,
修复非deepin发行版上没有计算机名的bug

fix: systeminfo not show on archlinux etc, and authorization show

---

CMakeLists.txt
debian/changelog

chore: changelog update and format

---

translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_ug.ts
translations/dde-control-center_zh_CN.ts

pull translations and fix wrong translation in zh_CN
resolve https://github.com/linuxdeepin/developer-center/issues/3946

chore: update translations

---

translations/dde-control-center_zh_CN.ts

Log: update translation of time page
resolve: https://github.com/linuxdeepin/developer-center/issues/3960

chore: update translation of time page

---

src/plugin-update/operation/updatework.cpp
src/plugin-update/window/updatectrlwidget.cpp

resolve: https://github.com/linuxdeepin/developer-center/issues/4008

fix: check update will not update the status of battery

---

src/plugin-accounts/window/avatarlistframe.cpp
src/plugin-accounts/window/avatarlistwidget.cpp

优化账户头像个性化设置英文文案
Log: 优化账户头像设置英文文案
Influence: 控制中心账户头像设置

chore: 优化账户头像设置英文文案

---

CMakeLists.txt
src/plugin-update/operation/common.h
src/plugin-update/operation/updatedbusproxy.cpp
src/plugin-update/operation/updatedbusproxy.h
src/plugin-update/operation/updatejobdbusproxy.cpp
src/plugin-update/operation/updatemodel.cpp
src/plugin-update/operation/updatemodel.h
src/plugin-update/operation/updatework.cpp
src/plugin-update/operation/updatework.h
src/plugin-update/window/updateplugin.cpp
src/plugin-update/window/updateplugin.h
src/plugin-update/window/updatesettingsmodule.cpp
src/plugin-update/window/updatesettingsmodule.h
src/plugin-update/window/widgets/internalbuttonitem.cpp
src/plugin-update/window/widgets/internalbuttonitem.h
src/plugin-update/window/widgets/systemupdateitem.cpp

support internal channel
resolve : https://github.com/linuxdeepin/developer-center/issues/3818

feat: support internal channel

---

src/plugin-systeminfo/window/systeminfomodule.cpp

chore: remove translate for copyright

---

CMakeLists.txt
debian/changelog

chore: bump version

---

.editorconfig
.reuse/dep5
CMakeLists.txt
docs/CMakeLists.txt

chore: add editorconfig

---

CMakeLists.txt

Log: make all install use gnuinstall dirs

fix: missing gnuinstall for some files

---

CMakeLists.txt
tests/frame/main.cpp
tests/interface/main.cpp
tests/plugin-commoninfo/main.cpp
tests/plugin-keyboard/main.cpp
tests/plugin-mouse/main.cpp
tests/plugin-notification/main.cpp
tests/plugin-systeminfo/main.cpp
tests/widgets/main.cpp

Since asan is quiet anoying, so set an option for it
Log: set an optional for asan

chore: set an optional for asan

---

src/plugin-personalization/window/personalizationdesktopmodule.cpp

Log: change the display for wm radius
resolve: https://github.com/linuxdeepin/developer-center/issues/4121

chore: change the display for wm radius

---

src/plugin-accounts/window/avatarlistframe.cpp

chore: fix build deb error

---

CMakeLists.txt
debian/changelog

* release dde-control-center 6.0.16
Log:

chore: bump version to 6.0.16

---

CMakeLists.txt
debian/control
docs/CMakeLists.txt

feat: add document package

---

CMakeLists.txt

Log: sometimes we need read path divergent install path

feat: read path form READ_DIR instead of INSTALL_DIR

---

CMakeLists.txt
debian/changelog

chore: bump version to 6.0.17

---

src/interface/moduledatamodel.cpp

hidden object also should pass
Log: insert logic adjust

chore: insert logic adjust

---

debian/dde-control-center.install

chore: fix docpackage

---

CMakeLists.txt
src/frame/pluginmanager.cpp
src/plugin-adapterv20tov23/adapterv20tov23plugin.cpp
src/plugin-adapterv20tov23/adapterv20tov23plugin.h

追加assert,
将加载翻译移动到控制中心本身，
修复插件module在子线程

fix qt assert coredump

---

src/plugin-datetime/window/timesettingmodule.cpp
src/plugin-systeminfo/window/systeminfomodule.cpp
src/plugin-systeminfo/window/utils.h

future should set after connect
QString args should use all
Log: fix qt warning

fix: qt warning

---

docs/v23-dcc-interface.zh_CN.md

chore: add readme for doxygen index.html

---

src/plugin-defaultapp/operation/defappworker.cpp
src/plugin-defaultapp/operation/mimedbusproxy.cpp
src/plugin-defaultapp/operation/mimedbusproxy.h
src/plugin-defaultapp/window/widgets/addbuttonwidget.h

after set the item. the categgory not do setDefault action
Log:

fix: defapp not change after leave and return

---

src/plugin-update/operation/updatework.cpp

Log: adjust internal channel logic

chore: internal channel logic adjust

---

src/plugin-update/operation/updatemodel.cpp

Log: updatemodelinfo maybe can be nullptr

fix: nullptr connect to signal

---

src/plugin-power/operation/powerdbusproxy.cpp
src/plugin-power/operation/powerdbusproxy.h

use dccDBusInterface instead
Log: fix powerplugin send noneexit signal

fix: powerplugin send noneexit signal

---

src/plugin-update/operation/updatework.cpp

change it to `maybe` to `may be`
Log: change the translate of update

chore: change the translate of update

---

debian/changelog

chore: bump version to 6.0.19

---

CMakeLists.txt

Log: D_FORTITY_SOURCE -> D_FORTIFY_SOURCE

fix: fix typo for SAFE_COMPILER

---

src/plugin-keyboard/window/kblayoutsettingwidget.cpp
src/plugin-keyboard/window/kblayoutsettingwidget.h
src/plugin-keyboard/window/systemlanguagewidget.cpp
src/plugin-keyboard/window/systemlanguagewidget.h

Log: use dcclistview instead
Resolve: https://github.com/linuxdeepin/developer-center/issues/4186

fix: keyboard when add new item size wrong

---

CMakeLists.txt

Log: set REQUIRED for DaReader

chore: set REQUIRED for DaReader

---

CMakeLists.txt

not set safe compiler to debug
add extra check to cmake
Log: adjust cmake

chore: adjust cmake

---

src/plugin-keyboard/window/kblayoutsettingwidget.cpp
src/plugin-keyboard/window/kblayoutsettingwidget.h
src/plugin-keyboard/window/systemlanguagewidget.cpp
src/plugin-keyboard/window/systemlanguagewidget.h

Log: not insert button to StandItem

fix: not insert button to DStandardItem

---

src/plugin-systeminfo/operation/systeminfomodel.cpp

Log: just show availiable memory

chore: just show availiable memory

---

CMakeLists.txt

Log: mark libdeepin_pw_check required

feat(cmake): mark libdeepin_pw_check as REQUIRED

---

src/plugin-accounts/operation/accountsdbusproxy.h
src/plugin-accounts/operation/userdbusproxy.h
src/plugin-datetime/window/timesettingmodule.h
src/plugin-display/window/multiscreenwidget.h
src/plugin-power/window/useelectricmodule.h
src/plugin-touchscreen/operation/monitordbusproxy.h

Log: these function undefineed

fix: clear up undefineed symbol

---

include/widgets/accessibleinterface.h
include/widgets/detailinfoitem.h
include/widgets/utils.h
src/frame/accessible.h
src/frame/mainwindow.cpp
src/interface/moduledatamodel.cpp
src/plugin-adapterv20tov23/frameproxyv20.cpp
src/plugin-bluetooth/window/adaptermodule.cpp
src/plugin-display/operation/displayworker.cpp
src/plugin-display/operation/machine.h
src/plugin-display/operation/monitor.h
src/plugin-keyboard/window/shortcutsettingwidget.h
src/plugin-notification/window/notificationmodule.cpp
src/plugin-personalization-dock/window/dockplugin.cpp
src/plugin-personalization/window/personalizationdesktopmodule.cpp
src/plugin-personalization/window/personalizationplugin.cpp
src/plugin-personalization/window/personalizationthememodule.cpp
src/plugin-personalization/window/widgets/globalthemelistview.cpp
src/plugin-power/window/generalmodule.cpp
src/plugin-power/window/usebatterymodule.cpp
src/plugin-power/window/useelectricmodule.cpp
src/plugin-update/operation/updatework.cpp
src/widgets/settingsitem.cpp
tests/plugin-test1/testplugin.cpp

fix: waring by gcc

---

src/plugin-accounts/window/accountsmodule.cpp

fix: warning by gcc

---

src/plugin-datetime/window/widgets/timezone.cpp
src/plugin-datetime/window/widgets/timezone.h

Log: support tzdir variable
resolve: https://github.com/linuxdeepin/dde-control-center/issues/1337

feat: support tzdir variable

---

src/frame/utils.h
src/plugin-power/window/utils.h
src/plugin-systeminfo/window/utils.h
src/plugin-update/operation/common.h

const variable should be marked inline in header
Log: variable in header marked inline

chore: const variable in header

---

src/plugin-commoninfo/window/commoninfomodule.cpp
src/plugin-systeminfo/window/systeminfomodule.cpp
src/plugin-systeminfo/window/utils.h

not show unused page if not deepin

 fix: not show unused page if not deepin 

---

src/frame/listitemdelegate.cpp
src/frame/listitemdelegate.h
src/interface/moduledatamodel.cpp

support hover and adjust the resize logic
resolve: https://github.com/linuxdeepin/developer-center/issues/4366

ListItem name support hover

---

src/plugin-systeminfo/window/systeminfomodule.cpp
src/plugin-systeminfo/window/systeminfomodule.h

Log:
resolve: https://github.com/linuxdeepin/developer-center/issues/4403

feat: add systeminfo message for graphicsplatform

---

translations/dde-control-center_en_US.ts
translations/dde-control-center_lt.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

chore: sync translations

---

include/widgets/dccdbusinterface.h
src/plugin-bluetooth/operation/bluetoothdbusproxy.cpp
src/plugin-bluetooth/operation/bluetoothdbusproxy.h
src/plugin-commoninfo/operation/commoninfoproxy.cpp
src/plugin-commoninfo/operation/commoninfoproxy.h
src/plugin-display/operation/displaydbusproxy.cpp
src/plugin-display/operation/displaydbusproxy.h
src/plugin-display/operation/machinedbusproxy.cpp
src/plugin-display/operation/machinedbusproxy.h
src/plugin-keyboard/operation/keyboarddbusproxy.cpp
src/plugin-keyboard/operation/keyboarddbusproxy.h
src/plugin-privacy/operation/privacysecuritydbusproxy.cpp
src/plugin-privacy/operation/privacysecuritydbusproxy.h
src/plugin-sound/operation/sounddbusproxy.cpp
src/plugin-sound/operation/sounddbusproxy.h
src/plugin-systeminfo/operation/systeminfodbusproxy.cpp
src/plugin-systeminfo/operation/systeminfodbusproxy.h
src/plugin-update/operation/updatedbusproxy.cpp
src/plugin-update/operation/updatedbusproxy.h
src/plugin-update/operation/updatejobdbusproxy.cpp
src/plugin-update/operation/updatejobdbusproxy.h
src/plugin-wacom/operation/wacomdbusproxy.cpp
src/plugin-wacom/operation/wacomdbusproxy.h

it is in dtkcore and be better maintained, so depercate it
Log: depercate DCCDBusInterface

BREAKING CHANGE: depercate DCCDBusInterface

---

src/plugin-accounts/operation/accountsdbusproxy.cpp
src/plugin-accounts/operation/accountsdbusproxy.h
src/plugin-accounts/operation/securitydbusproxy.cpp
src/plugin-accounts/operation/securitydbusproxy.h
src/plugin-accounts/window/accountsmodel.cpp
src/plugin-accounts/window/avatarlistframe.cpp
src/plugin-adapterv20tov23/pluginmanagerv20.cpp
src/plugin-bluetooth/window/bluetoothdevicemodel.cpp
src/plugin-display/window/collaborativelinkwidget.cpp
src/plugin-display/window/displaymodule.cpp
src/plugin-display/window/rotatewidget.cpp
src/plugin-sound/window/microphonepage.cpp
src/plugin-sound/window/soundplugin.cpp
src/plugin-touchscreen/operation/touchscreenmodel.cpp
src/plugin-touchscreen/operation/touchscreenproxy.cpp
src/plugin-touchscreen/operation/touchscreenproxy.h
src/plugin-touchscreen/window/touchscreenmodule.cpp

fix missing compiler warining

---

src/plugin-authentication/window/widgets/face/addfaceinfodialog.cpp
src/plugin-sound/operation/sounddbusproxy.cpp
src/plugin-sound/window/microphonepage.cpp
src/plugin-sound/window/speakerpage.cpp

Log: fix some warning by qt
cannot set multiple layout to widget
cannot insert widget to index that is not existed

chore: fix some warning by qt

---

src/frame/mainmodule.cpp
src/interface/hlistmodule.cpp

adjust the margin of mainpage and hlistmodule
Log: fix margin of page
resolve: https://github.com/linuxdeepin/developer-center/issues/4480

fix(ui): margin of page

---

CMakeLists.txt
debian/changelog

bump version and  fix changelog typo

chore: bump version to 6.0.21

---

src/frame/mainmodule.cpp

margin should be (top, bottom): 10, (left ,right): 0
before they are all set to 0
Log: fix ui

fix(ui): margin or mainmodule

---

src/frame/mainmodule.cpp
src/interface/moduledatamodel.cpp
src/interface/moduledatamodel.h
tests/plugin-test1/testplugin.cpp

Log: use fontMetrics to get text length

chore: use fontMetrics to get text length

---

src/plugin-mouse/operation/mousedbusproxy.cpp
src/plugin-mouse/window/generalsettingwidget.cpp

wrong use of inputdevice dbus, adjust show
Log:
fix: https://github.com/linuxdeepin/developer-center/issues/4626

fix(mouse): speed show

---

src/plugin-update/window/updatesettingsmodule.h

fix: unrealized func

---

translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

Log:
resolve: https://github.com/linuxdeepin/developer-center/issues/4660

chore(aboutsystem): update translate

---

include/interface/hlistmodule.h
include/interface/moduleobject.h
include/interface/pagemodule.h
include/interface/vlistmodule.h
src/interface/hlistmodule.cpp
src/interface/moduleobject.cpp
src/interface/pagemodule.cpp
src/interface/vlistmodule.cpp

in cpp20, struct can use as AStruct { .name = "ss" }, although this project use 17, but a struct can storage more message, this I think will make it easy to construct a moduleobject
Log: use struct to describe init

feat(moduleobject): use struct to describe init

---

src/plugin-authentication/window/widgets/face/faceinfowidget.cpp

fix: cannot find DGuiApplicationHelper

---

src/plugin-systeminfo/window/privacypolicywidget.cpp
src/plugin-systeminfo/window/systeminfomodule.cpp

fix(systeminfo): on archlinux show UnionTech

---

src/frame/pluginmanager.cpp
src/plugin-accounts/window/accountsmodule.cpp
src/plugin-datetime/window/datetimeplugin.cpp
src/plugin-defaultapp/window/defappplugin.cpp
src/plugin-mouse/window/mousemodule.cpp
src/plugin-notification/window/notificationmodule.cpp
src/plugin-personalization/window/personalizationplugin.cpp
src/plugin-power/window/powerplugin.cpp
src/plugin-sound/window/soundplugin.cpp
src/plugin-systeminfo/window/systeminfomodule.cpp
src/plugin-update/window/updateplugin.cpp

Log: update description of modules

chore: update description of modules

---

src/frame/pluginmanager.cpp
src/plugin-authentication/window/authenticationplugin.cpp
src/plugin-keyboard/window/keyboardmodule.cpp
src/plugin-power/window/usebatterymodule.cpp

Update description early.
filter empty description.
Issue: https://github.com/linuxdeepin/developer-center/issues/4615

fix: Plugin's description display error

---

translations/dde-control-center_en.ts
translations/dde-control-center_zh_CN.ts

update translate
Log:
Resolve: https://github.com/linuxdeepin/developer-center/issues/4772

chore: update translate

---

src/plugin-datetime/window/widgets/timezone.cpp

Log: add miss separator for filepath

fix: add miss separator for filepath

---

src/plugin-mouse/operation/mousedbusproxy.cpp
src/plugin-mouse/operation/mousedbusproxy.h
src/plugin-mouse/operation/mousemodel.cpp
src/plugin-mouse/operation/mousemodel.h
src/plugin-mouse/operation/mouseworker.cpp
src/plugin-mouse/operation/mouseworker.h
src/plugin-mouse/window/mousemodule.cpp
src/plugin-mouse/window/mousemodule.h
src/plugin-mouse/window/touchpadsettingwidget.cpp
src/plugin-mouse/window/touchpadsettingwidget.h

enable user to disable their touchpad if needed
Log:
resolve: https://github.com/linuxdeepin/developer-center/issues/4596

feat(MousePlugin): enable disabletouchpad anytime

---

src/frame/pluginmanager.cpp
src/interface/moduleobject.cpp
src/plugin-power/operation/powerworker.cpp

这个组件是在读取是否存在battery后才显示出来的，一开始没有显示
这个pr做了两件事，第一在battery组件work一开始就设置了是否存在电池，保证初始化时候就显示
将生成description的工作从pluginmanager移动到objectmodule里面

fix battery child module not show

---

include/interface/moduleobject.h
src/interface/moduleobject.cpp

Log: as title
resolve: https://github.com/linuxdeepin/developer-center/issues/4870

fix: child visible changed description not changed

---

src/plugin-accounts/window/accountsmodule.cpp
src/plugin-accounts/window/createaccountpage.cpp

chore: account to user

---

src/plugin-update/operation/updatework.cpp
src/plugin-update/operation/updatework.h
src/plugin-update/window/updateplugin.cpp

Log:
https://github.com/linuxdeepin/developer-center/issues/5002

chore: move take time operation to first active

---

src/plugin-personalization/window/personalizationthememodule.cpp

fix: cannot get dark png on theme shown

---

src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/window/personalizationthememodule.cpp

fix: use changed signal to handle refresh theme

---

translations/dde-control-center_zh_CN.ts

chore: fix translations

---

CMakeLists.txt
debian/changelog

chore: bump version to 6.0.22

---

src/plugin-accounts/window/accountsmodule.cpp
src/plugin-accounts/window/avatarlistframe.cpp
src/plugin-accounts/window/avatarlistwidget.cpp
src/plugin-accounts/window/avatarlistwidget.h

this cause it can be show many times
Log:

fix: avatarlistDialog is not modal

---

src/frame/main.cpp
src/frame/pluginmanager.cpp
src/plugin-adapterv20tov23/pluginmanagerv20.cpp
src/plugin-bluetooth/operation/bluetoothadapter.cpp
src/plugin-bluetooth/operation/bluetoothworker.cpp
src/plugin-bluetooth/window/bluetoothmodule.cpp
src/plugin-commoninfo/operation/commoninfowork.cpp
src/plugin-datetime/operation/datetimedbusproxy.cpp
src/plugin-datetime/operation/datetimeworker.cpp
src/plugin-datetime/window/timesettingmodule.cpp
src/plugin-defaultapp/operation/defappworker.cpp
src/plugin-defaultapp/window/defappdetailwidget.cpp
src/plugin-display/operation/displayworker.cpp
src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-sound/operation/soundmodel.cpp
src/plugin-sound/operation/soundworker.cpp
src/plugin-update/operation/updatemodel.cpp
src/plugin-update/operation/updatework.cpp
src/plugin-update/window/updatectrlwidget.cpp
src/plugin-update/window/updateplugin.cpp
src/plugin-wacom/window/wacommodule.cpp

I want to add category for log
this can make log more readable
Log:

chore: move some log to categrade log

---

src/plugin-display/window/collaborativelinkwidget.cpp

fix: make combox enable the same as swtichbtn

---

translations/dde-control-center_zh_CN.ts

修改所有“帐户”为“用户”
在创建用户界面中：为“New User”添加翻译“新用户”、为“User Type”添加翻译“用户类型”

chore: update translations “帐户” -> “用户”

---

src/interface/moduleobject.cpp
src/plugin-bluetooth/window/bluetoothmodule.cpp
src/plugin-display/window/displaymodule.cpp

fix: display show logic and update description

---

src/plugin-systeminfo/operation/systeminfomodel.cpp
src/plugin-systeminfo/operation/systeminfomodel.h
src/plugin-systeminfo/operation/systeminfowork.cpp
src/plugin-systeminfo/window/systeminfomodule.cpp
src/plugin-systeminfo/window/utils.h

chore: tidy up show license function

---

src/plugin-accounts/window/avatarlistframe.cpp
src/plugin-accounts/window/avatarlistframe.h
src/plugin-accounts/window/avatarlistview.cpp
src/plugin-accounts/window/avatarlistview.h
src/plugin-defaultapp/window/widgets/addbuttonwidget.cpp
src/plugin-defaultapp/window/widgets/addbuttonwidget.h

chore: not init a filedialog in constructor

---

src/interface/tabview.cpp

chore: remove setSelection

---

src/plugin-commoninfo/window/commoninfomodule.cpp

chore: adjust the description of generalsettings

---

src/plugin-systeminfo/window/systeminfomodule.cpp

chore: change wayland to Wayland

---

CMakeLists.txt
debian/changelog

chore: update version to 6.0.23

---

src/plugin-accounts/window/avatarlistwidget.cpp

active persion of avadialog first
Log:

fix: focus first index in plugin-accounts dialog

---

src/plugin-update/operation/updatemodel.cpp
src/plugin-update/operation/updatemodel.h
src/plugin-update/operation/updatework.cpp
src/plugin-update/operation/updatework.h
src/plugin-update/window/updatesettingsmodule.cpp

chore: support linglong update

---

src/plugin-accounts/window/avatarlistview.cpp
src/plugin-accounts/window/avatarlistview.h
src/plugin-accounts/window/avatarlistwidget.cpp
src/plugin-accounts/window/avatarlistwidget.h

element in one page should not be scrollable,
tidy up code in avatarlistview, to reduce nesting
Log:

fix(avadialog): to fit the request from ui

---

CMakeLists.txt
debian/changelog

chore: publish 6.0.24

---

src/plugin-update/window/updatesettingsmodule.cpp

move the switcher of linglong timer to Update Settings
Log:

chore: move up linglong timer switcher

---

translations/dde-control-center_zh_CN.ts

chore: bring back translations

---

src/plugin-accounts/window/createaccountpage.cpp

用户名密码检查部分逻辑微调， alert message 不需要专门指定 parentwidget
Issue: https://github.com/linuxdeepin/developer-center/issues/5333

fix: password alert message position error

---

src/plugin-update/operation/updatework.cpp

chore: do not need to sort update log anymore

---

src/plugin-datetime/window/regionanddatemodule.cpp

Region-settings's implement can't work
Issue: https://github.com/linuxdeepin/developer-center/issues/5523

chore: Hide Region-Settings view

---

src/interface/pagemodule.cpp
src/interface/vlistmodule.cpp

chore: when page width is not big, show hscrollbar

---

src/plugin-update/window/widgets/internalbuttonitem.cpp

chore: remove colon

---

debian/changelog

chore: publish new release

---

src/plugin-update/operation/updatedbusproxy.cpp
src/plugin-update/operation/updatedbusproxy.h
src/plugin-update/operation/updatework.cpp

chore: get machineId from dbus

---

src/frame/mainmodule.cpp

remove the call setSidebarExpanded
Issue: https://github.com/linuxdeepin/developer-center/issues/5297

fix: sidebar expand/collapse status error

---

CMakeLists.txt
debian/changelog
src/interface/tabview.cpp

fix: tabview height is very large at the beginning

---

src/plugin-datetime/window/regionanddatemodule.h

fix: remove unimplemented func

---

CMakeLists.txt
debian/changelog

fix: debian warning

---

translations/dde-control-center_zh_CN.ts

Issue: https://github.com/linuxdeepin/developer-center/issues/5694 Log:

fix: wrong cn translation

---

src/plugin-personalization/window/widgets/globalthemelistview.cpp

feat(persionalization): always put custom the end

---

src/plugin-power/operation/powerdbusproxy.cpp
src/plugin-power/operation/powerdbusproxy.h
src/plugin-power/operation/powermodel.cpp
src/plugin-power/operation/powermodel.h
src/plugin-power/operation/powerworker.cpp
src/plugin-power/window/generalmodule.cpp

feat: hide wakeupsetting when nopasswd

---

src/plugin-sound/operation/sounddbusproxy.cpp
src/plugin-sound/operation/sounddbusproxy.h
src/plugin-sound/operation/soundmodel.cpp
src/plugin-sound/operation/soundmodel.h
src/plugin-sound/operation/soundworker.cpp
src/plugin-sound/operation/soundworker.h
src/plugin-sound/window/soundplugin.cpp
translations/dde-control-center_en.ts
translations/dde-control-center_zh_CN.ts

feat: allow set pausePlayer availablity

---

src/plugin-power/window/generalmodule.cpp
translations/dde-control-center_en.ts
translations/dde-control-center_zh_CN.ts

 chore: change the display text for wake up setting 

---

src/plugin-accounts/window/avatarlistwidget.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/5898 Log:

fix: wrong use of setCurrentWidget

---

debian/changelog

chore: beta3 season1 tag for dde-control-center

---

translations/dde-control-center_zh_CN.ts

fix translation error about region format
Log: fix translation error

fix: translation error

---

archlinux/PKGBUILD

fix(obs): remove useless deps of archlinux

---

src/frame/main.cpp
src/plugin-update/window/widgets/resultitem.cpp

chore: remove deprecated function

---

src/plugin-datetime/window/widgets/file_util.cpp
src/plugin-datetime/window/widgets/file_util.h
src/plugin-datetime/window/widgets/popup_menu.cpp
src/plugin-datetime/window/widgets/popup_menu.h
src/plugin-datetime/window/widgets/popup_menu_delegate.cpp
src/plugin-datetime/window/widgets/popup_menu_delegate.h
src/plugin-datetime/window/widgets/tooltip_pin.cpp
src/plugin-datetime/window/widgets/tooltip_pin.h

Log:
Issue: https://github.com/linuxdeepin/developer-center/issues/5979

fix: radius of menu of map

---

src/plugin-datetime/window/widgets/timezonechooser.cpp

Log:
Issue: https://github.com/linuxdeepin/developer-center/issues/5980

fix: dialog close btn

---

translations/datetime_country_en.ts
translations/datetime_language_zh_CN.ts

chore: trim translations in ts

---

src/interface/vlistmodule.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/5683 Log:

feat: make the size of splitter be remembered

---

src/plugin-datetime/operation/datetimeworker.cpp
src/plugin-datetime/operation/regionproxy.cpp
src/plugin-datetime/operation/regionproxy.h

fix: load translate when first active

---

src/plugin-datetime/window/regionmodule.cpp

access wild pointer
Issue: https://github.com/linuxdeepin/developer-center/issues/6004

fix: crash when clicked region

---

CMakeLists.txt
debian/changelog

chore: release new tag

---

src/interface/vlistmodule.cpp

Log: it this widgets is not used, it should be deleted

fix: widgets will increase in vlistmodule

---

CMakeLists.txt
misc/DdeControlCenterConfig.cmake.in

chore: bettercmake

---

src/plugin-datetime/window/timezonemodule.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/6035 Log:

chore: use daemon systemzone to filter

---

CMakeLists.txt

fix: cmake ut missing include

---

src/plugin-datetime/window/regionmodule.cpp

change country to region
Log: modify text about region

chore: modify text about region

---

CMakeLists.txt
debian/control
tests/widgets/main.cpp

feat: run test when compile

---

src/plugin-defaultapp/operation/defappworker.cpp

fix: is desktop is marked nodisplay, not show it

---

src/frame/pluginmanager.cpp

chore: in log show the failed plugin also

---

CMakeLists.txt
archlinux/PKGBUILD
debian/control
src/plugin-defaultapp/operation/defappworker.cpp
src/plugin-defaultapp/operation/defappworker.h
src/plugin-defaultapp/operation/mimedbusproxy.cpp
src/plugin-defaultapp/operation/mimedbusproxy.h
src/plugin-defaultapp/window/defappplugin.cpp
src/plugin-defaultapp/window/widgets/category.h

chore: set defaultterminal with qgsettings

---

CMakeLists.txt
src/plugin-sound/operation/sounddbusproxy.cpp
src/plugin-sound/operation/sounddbusproxy.h
src/plugin-sound/operation/soundmodel.cpp
src/plugin-sound/operation/soundmodel.h
src/plugin-sound/operation/soundworker.cpp
src/plugin-sound/operation/soundworker.h
src/plugin-sound/window/advancedsettingmodule.cpp
src/plugin-sound/window/advancedsettingmodule.h
src/plugin-sound/window/soundplugin.cpp
translations/dde-control-center_en.ts
translations/dde-control-center_zh_CN.ts

add audio server switch support
Issue:https://github.com/linuxdeepin/developer-center/issues/5819
Log: add audio server switch support

feat: add audio server switch support

---

src/plugin-accounts/window/avataritemdelegate.cpp
src/plugin-accounts/window/avataritemdelegate.h
src/plugin-accounts/window/avatarlistview.cpp
src/plugin-accounts/window/avatarlistview.h
src/plugin-accounts/window/avatarlistwidget.cpp
src/plugin-accounts/window/avatarlistwidget.h

feat: allow remove custom icon

---

README.md
docs/v23-dcc-interface.zh_CN.md

chore: update doc and README

---

misc/configs/common/org.deepin.region-format.json
src/plugin-datetime/operation/datetimeworker.cpp
src/plugin-datetime/operation/datetimeworker.h
src/plugin-datetime/operation/regionproxy.cpp
src/plugin-datetime/operation/regionproxy.h
src/plugin-datetime/window/regionmodule.cpp
src/plugin-datetime/window/widgets/customregionformatdialog.cpp
src/plugin-datetime/window/widgets/regionformatdialog.cpp

save field day (Monday...) in config as int type
Log: change the storage type of field day

chore: store field day as int type

---

src/plugin-datetime/operation/regionproxy.cpp
src/plugin-datetime/window/regionmodule.cpp
src/plugin-datetime/window/regionmodule.h
src/plugin-datetime/window/widgets/regionformatdialog.cpp

Change to the case that storing value (country & language) in English
Issue: https://github.com/linuxdeepin/developer-center/issues/6074

fix: store value (country & language) in Translation

---

CMakeLists.txt

chore: export link should be linked with public

---

src/plugin-datetime/operation/datetimemodel.cpp
src/plugin-datetime/operation/datetimemodel.h
src/plugin-datetime/operation/datetimeworker.cpp
src/plugin-datetime/window/regionmodule.cpp
src/plugin-datetime/window/widgets/customregionformatdialog.cpp

custom format dialog initialize correctly
Issue: https://github.com/linuxdeepin/developer-center/issues/5973

fix: custom format dialog initialize error

---

src/plugin-power/window/usebatterymodule.cpp

it does not need background
Log:
Issue: https://github.com/linuxdeepin/developer-center/issues/6272

fix: silder of battery have background

---

src/widgets/detailinfoitem.cpp

feat: detailinfoitem link hide when no link

---

src/plugin-datetime/window/widgets/timezoneitem.cpp

fix: if there is no cityname, show name

---

src/plugin-defaultapp/window/defappplugin.cpp

warning by clangd, so make some adjust
Log:

chore(defappplugin): adjust arg init order

---

src/plugin-bluetooth/window/bluetoothdevicemodel.cpp
src/plugin-sound/operation/soundmodel.h
src/plugin-sound/window/soundeffectspage.h

fix: build error on new dtk

---

CMakeLists.txt
debian/changelog

chore: new release for 6.0.35

---

src/plugin-datetime/operation/datetimeworker.cpp
src/plugin-datetime/operation/regionproxy.cpp

wrong format of qstring
Log:
Issue: https://github.com/linuxdeepin/developer-center/issues/6309

fix: display of region is error

---

src/plugin-datetime/window/regionmodule.cpp
src/plugin-datetime/window/widgets/customregionformatdialog.cpp
src/plugin-datetime/window/widgets/regionformatdialog.cpp
translations/dde-control-center_en.ts
translations/dde-control-center_zh_CN.ts

chore: change text of regionmodule

---

src/plugin-datetime/window/widgets/timezone.h
src/plugin-datetime/window/widgets/timezoneitem.cpp

Log: 修改系统时区中关于时间标准的文字描述：GMT -> UTC
Issues: https://github.com/linuxdeepin/developer-center/issues/6325

chore: Modify the textual description of the system time: GMT -> UTC

---

debian/control
debian/copyright
debian/dde-control-center.triggers
debian/source/lintian-overrides

fix: debian control

---

src/plugin-datetime/window/widgets/timezonechooser.cpp

fix: map dialog radius not follow system

---

src/plugin-bluetooth/window/bluetoothdevicemodel.cpp

chore: find icon from system first

---

include/widgets/settingsgroup.h
src/widgets/settingsgroup.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/4261 Log:

fix: settingsgroup in scrollarea not resize

---

src/plugin-accounts/window/modifypasswdpage.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/6449 Log:

fix: bring back close button for password dialog

---

src/plugin-update/operation/updatework.cpp

fix: update status need to update first

---

CMakeLists.txt
archlinux/PKGBUILD
debian/control
src/plugin-datetime/window/regionmodule.cpp
src/plugin-datetime/window/regionmodule.h
src/plugin-datetime/window/widgets/regionformatdialog.cpp

feat: region use icu instead

---

src/plugin-commoninfo/window/bootwidget.cpp

chore: add log to plugin-commoninfo

---

src/plugin-keyboard/operation/shortcutmodel.cpp

chore: add new shotcut

---

src/plugin-datetime/window/regionmodule.cpp

chore: hide region area

---

src/plugin-power/window/generalmodule.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/6056 Log:

chore: tips of plugin-power should in smaller size

---

src/widgets/switchwidget.cpp

Issues linuxdeepin/developer-center#5343

feat: show tooltip when SwitchLabel text is elided

---

src/plugin-update/operation/updatework.cpp
src/plugin-update/operation/updatework.h

Issue: https://github.com/linuxdeepin/developer-center/issues/4193 Log:

feat: check packages in future

---

src/plugin-accounts/window/avatarlistwidget.cpp

fix: now custom picture page should be 4

---

src/plugin-accounts/window/avatarlistwidget.cpp

fix: after add custom picture, switch to page four

---

src/plugin-accounts/window/avatarlistview.cpp

fix: when delete a picture, customindex update

---

src/plugin-accounts/window/avatarlistview.cpp

fix: last custom image should not be deleted

---

src/plugin-datetime/operation/datetimeworker.cpp
src/plugin-datetime/operation/datetimeworker.h
src/plugin-datetime/window/regionmodule.cpp

feat: set locale.conf when set region

---

src/plugin-datetime/operation/datetimeworker.cpp

fix: after set region, label value is not update

---

src/plugin-datetime/operation/datetimeworker.cpp
src/plugin-datetime/window/regionmodule.cpp

not do it when set dconfig
Log:

fix: set region and update model

---

src/plugin-accounts/window/avatarlistview.cpp

fix: count of icon is wrong

---

src/plugin-defaultapp/operation/defappworker.cpp

Issues linuxdeepin/developer-center#6692

fix(defapp): the program name is not displayed correctly

---

CMakeLists.txt
src/frame/listview.cpp
src/frame/main.cpp
src/frame/pluginmanager.cpp
src/interface/tabview.cpp
src/plugin-accounts/window/securitylevelitem.cpp
src/plugin-authentication/window/faceiddetailwidget.cpp
src/plugin-authentication/window/fingerdetailwidget.cpp
src/plugin-authentication/window/irisdetailwidget.cpp
src/plugin-authentication/window/widgets/authenticationinfoitem.cpp
src/plugin-authentication/window/widgets/face/faceinfowidget.cpp
src/plugin-authentication/window/widgets/finger/fingerinfowidget.cpp
src/plugin-datetime/window/timesettingmodule.cpp
src/plugin-display/operation/displayworker.cpp
src/plugin-display/operation/types/touchscreeninfolist_v2.cpp
src/plugin-display/operation/types/touchscreeninfolist_v2.h
src/plugin-display/window/resolutionwidget.cpp
src/plugin-display/window/treecombox.cpp
src/plugin-sound/window/microphonepage.cpp
src/plugin-sound/window/speakerpage.cpp
src/plugin-systeminfo/window/hostnameitem.cpp
src/plugin-touchscreen/operation/types/touchscreeninfolist_v2.cpp
src/plugin-touchscreen/operation/types/touchscreeninfolist_v2.h
src/plugin-update/operation/common.h
src/plugin-update/operation/updatework.h
tests/plugin-keyboard/ut_customedit.cpp
tests/plugin-update/main.cpp
tests/plugin-update/ut_common.cpp

remove will removed interface, remove useless headers someother things
Log:

chore: tidyup

---

src/plugin-accounts/window/avatarlistview.cpp
src/plugin-accounts/window/avatarlistview.h

feat: avatarlistview can handle tab

---

src/plugin-datetime/operation/regionproxy.cpp
src/plugin-datetime/window/regionmodule.cpp
src/plugin-datetime/window/widgets/regionformatdialog.cpp
src/plugin-datetime/window/widgets/regionformatdialog.h

initialize language and locale in dialog
Issue: https://github.com/linuxdeepin/developer-center/issues/5999

fix: Language and locale are not initialized

---

CMakeLists.txt
src/plugin-datetime/operation/datetimeworker.cpp
src/plugin-datetime/operation/datetimeworker.h

Issue: https://github.com/linuxdeepin/developer-center/issues/6741 Log:

fix: should not set illegal locale

---

CMakeLists.txt
debian/changelog

chore: bump version to 6.0.37

---

src/plugin-datetime/window/timesettingmodule.cpp

add missed include header
Log:

fix: ci broken because of missed header

---

src/plugin-accounts/window/accountsmodel.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/6447 Log:

feat: make display of account list show in center

---

CMakeLists.txt
debian/changelog

chore: bump verison to 6.0.38

---

.reuse/dep5
CMakeLists.txt
debian/dde-control-center.install
misc/org.deepin.dde.controlcenter.metainfo.xml

Issue: https://github.com/linuxdeepin/developer-center/issues/6883 Log:

chore: add metainfo of dde

---

src/plugin-datetime/operation/regionproxy.cpp

feat: add new custom date format

---

src/plugin-update/operation/common.h
src/plugin-update/operation/updatemodel.cpp
src/plugin-update/operation/updatework.cpp
src/plugin-update/window/updatectrlwidget.cpp
src/plugin-update/window/widgets/updatesettingitem.cpp
translations/dde-control-center_en.ts
translations/dde-control-center_zh_CN.ts

feat: if disk space is full, show the reason

---

src/plugin-update/window/widgets/updatecontrolpanel.cpp

set the fixed width of label and process bar from 100 to 150
Log:

chore(update): little change of the process widgets

---

translations/datetime_country_de.ts
translations/datetime_country_es.ts
translations/datetime_country_id.ts
translations/datetime_country_pt_BR.ts
translations/datetime_language_az.ts
translations/datetime_language_pt_BR.ts
translations/dde-control-center_de.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_sk.ts
translations/keyboard_language_pt_BR.ts

chore: sync translation

---

src/plugin-accounts/window/avatarlistview.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/6694 Log:

feat: do not limit custom avatar count

---

CMakeLists.txt
debian/changelog

chore: bump version to 6.0.39

---

src/interface/pagemodule.cpp

restrict it to the same width of scrollarea
Issue: https://github.com/linuxdeepin/developer-center/issues/6704 Log:

fix: extra button maybe too wide

---

src/plugin-update/operation/updatework.cpp

fix: should wait for http event finished then next

---

src/plugin-notification/window/notificationmodule.cpp

chore(notify): qdebug record app added or removed

---

CMakeLists.txt
debian/changelog

chore: bump version to 6.0.40

---

src/plugin-datetime/operation/regionproxy.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/6995 Log:

fix: date format

---

CMakeLists.txt
debian/changelog

chore: bump version to 6.0.41

---

.gitignore
.reuse/dep5
CMakeLists.txt
LICENSES/MIT.txt
debian/changelog
debian/control
src/plugin-display/operation/displayworker.cpp
src/plugin-display/operation/displayworker.h
src/plugin-display/operation/monitor.cpp
src/plugin-display/operation/monitor.h
src/plugin-display/wayland/gammaeffects/DFGammaEffects.hpp
src/plugin-display/wayland/gammaeffects/GammaEffects.cpp
src/plugin-display/wayland/gammaeffects/color_math.cpp
src/plugin-display/wayland/gammaeffects/color_math.hpp
src/plugin-display/wayland/libwayqt/GammaControl.cpp
src/plugin-display/wayland/libwayqt/GammaControl.hpp
src/plugin-display/wayland/libwayqt/Output.cpp
src/plugin-display/wayland/libwayqt/Output.hpp
src/plugin-display/wayland/libwayqt/OutputManager.cpp
src/plugin-display/wayland/libwayqt/OutputManager.hpp
src/plugin-display/wayland/libwayqt/Registry.cpp
src/plugin-display/wayland/libwayqt/Registry.hpp
src/plugin-display/wayland/libwayqt/TreeLandOutputManager.cpp
src/plugin-display/wayland/libwayqt/TreeLandOutputManager.hpp
src/plugin-display/wayland/libwayqt/WayQtUtils.cpp
src/plugin-display/wayland/libwayqt/WayQtUtils.hpp
src/plugin-display/wayland/libwayqt/protocols/treeland-output-management.xml
src/plugin-display/wayland/libwayqt/protocols/wlr-gamma-control-unstable-v1.xml
src/plugin-display/wayland/libwayqt/protocols/wlr-output-management-unstable-v1.xml
src/plugin-display/window/multiscreenwidget.cpp

log: support wlr output management and treeland output management

feat: make plugin-display works in treeland

---

src/frame/pluginmanager.cpp

log: DDE_CURRENT_COMPOSITER -> DDE_CURRENT_COMPOSITOR

fix: typo compositor

---

src/plugin-keyboard/window/customcontentdialog.cpp
src/plugin-keyboard/window/customcontentdialog.h

Issues: linuxdeepin/developer-center#7089

fix(CustomShortcut): file chooser is opened when Enter pressed

---

src/plugin-keyboard/window/customcontentdialog.cpp

Issues: linuxdeepin/developer-center#7109

fix: wrong tab index

---

src/plugin-defaultapp/operation/defappworker.cpp
src/plugin-defaultapp/operation/mimedbusproxy.cpp
src/plugin-defaultapp/operation/mimedbusproxy.h

Issue: https://github.com/linuxdeepin/developer-center/issues/7164 Log:

fix: set all mime type

---

src/plugin-update/operation/updatework.cpp

chore: mask linglong-upgrade.service together

---

CMakeLists.txt
debian/changelog
src/frame/listitemdelegate.cpp
src/frame/listview.cpp
src/frame/mainmodule.cpp
src/frame/mainwindow.cpp

tweak UI to adapt to sidebar blur
Log:

chore: Tweak UI to adapt to sidebar blur

---

src/plugin-personalization/window/widgets/personalizationthemelist.cpp

Issues: linuxdeepin/developer-center#7259

fix(PersonalizationThemeList): wrong margins

---

src/interface/pagemodule.cpp

restrict to a smaller fixed size
issue: https://github.com/linuxdeepin/developer-center/issues/6704
Log: The width of bottom button is too long

fix: The width of bottom button is too long

---

include/interface/moduleobject.h
src/frame/mainmodule.cpp
src/frame/mainmodule.h
src/frame/mainwindow.cpp
src/interface/moduleobject.cpp

correct the spell(defult)
Log: fix the typo (defult)

fix: typo (defult)

---

include/interface/moduleobject.h
src/frame/mainmodule.cpp
src/frame/mainmodule.h
src/frame/mainwindow.cpp
src/interface/moduleobject.cpp

This reverts commit b7ecef458a760811a9579da4b55e7d1c5e669ce1.

Revert "fix: type(defult)"

---

debian/changelog

chore: Bump version to 6.0.45

---

src/plugin-power/window/usebatterymodule.cpp

change to get data from model
Issue: https://github.com/linuxdeepin/developer-center/issues/7171

fix: flash when switch subpages

---

debian/changelog
src/plugin-power/operation/powerdbusproxy.cpp

update version
Log: bump version to 6.0.46

chore: Bump version to 6.0.46

---

debian/changelog

chore: bump version to 6.0.47

---

src/plugin-personalization/window/widgets/globalthemelistview.cpp

tab indicator radius  6  ==> 3
tab indicator spacing 40 ==> 6
Issue: https://github.com/linuxdeepin/developer-center/issues/7139

chore: tab indicator radius tweak

---

src/plugin-personalization-dock/window/dockplugin.cpp
src/plugin-personalization-dock/window/dockplugin.h

remove "show recent apps in dock" option
Issue: https://github.com/linuxdeepin/developer-center/issues/7708

chore: remove show recent apps in dock settings

---

debian/changelog

chore: bump version to 6.0.48

---

src/plugin-datetime/window/regionmodule.cpp
src/plugin-datetime/window/widgets/regionformatdialog.cpp

remove space
Log: https://github.com/linuxdeepin/developer-center/issues/7729

fix: space between lang and country

---

src/plugin-personalization-dock/window/dockplugin.cpp

disable items about top, left and right position
disable the item about hiding dock by context
Issue: https://github.com/linuxdeepin/developer-center/issues/7881

fix: adjust configure for dock module temporarily

---

src/plugin-personalization-dock/window/dockplugin.cpp
translations/dde-control-center_en.ts
translations/dde-control-center_zh_CN.ts

Mode ==> Alignment
Fashion mode   ==> Align center
Efficient mode ==> Align left
Issue: https://github.com/linuxdeepin/developer-center/issues/8003

chore: dock translation update

---

debian/changelog

chore: bump version to 6.0.49

---

CMakeLists.txt
archlinux/PKGBUILD
debian/control
debian/dde-control-center.install
misc/org.deepin.dde.ControlCenter1.service.in
misc/systemd/dde-control-center.service.in

use systemd service instead of dbus activate
log: as title

feat: dbus activation adapt to AM

---

src/plugin-keyboard/operation/keyboardwork.cpp
src/plugin-keyboard/operation/keyboardwork.h

shouldn't set locale configure when switching language
Log:

fix: wrong time format

---

src/plugin-power/window/generalmodule.cpp

Place the title and description text in one item
Issue: https://github.com/linuxdeepin/developer-center/issues/8046

feat: Update performance mode listview style

---

debian/changelog

chore: bump version to 6.0.51

---

include/widgets/detailinfoitem.h
src/plugin-update/operation/common.h
src/plugin-update/window/widgets/updatecontrolpanel.cpp
src/plugin-update/window/widgets/updatecontrolpanel.h
src/widgets/detailinfoitem.cpp

Manually changing the text color in HTML
Issue: https://github.com/linuxdeepin/developer-center/issues/7996

fix: upgrade information mismatch with dark mode

---

debian/changelog

chore: bump version to 6.0.52

---

debian/changelog

chore: Bump version to 6.0.53

---

misc/configs/org.deepin.dde.control-center.update.json
src/plugin-update/operation/updatedbusproxy.cpp
src/plugin-update/operation/updatework.cpp

是否备份可以配置了！
顺便修复内存泄漏和属性调用调用错误的问题。。

feat: add auto backup config for udpate

---

src/plugin-personalization/window/personalizationdesktopmodule.cpp
translations/dde-control-center_en.ts
translations/dde-control-center_zh_CN.ts

modify transparent text
Issue: https://github.com/linuxdeepin/developer-center/issues/8543

fix: modify transparent text

---

src/plugin-update/operation/updatemodel.cpp
src/plugin-update/operation/updatemodel.h
src/plugin-update/operation/updatework.cpp
src/plugin-update/operation/updatework.h
src/plugin-update/window/updatectrlwidget.cpp
src/plugin-update/window/updatesettingsmodule.cpp
src/plugin-update/window/updatesettingsmodule.h
src/plugin-update/window/widgets/updatecontrolpanel.cpp
src/plugin-update/window/widgets/updatecontrolpanel.h
src/plugin-update/window/widgets/updatesettingitem.cpp
src/plugin-update/window/widgets/updatesettingitem.h
translations/dde-control-center_en.ts
translations/dde-control-center_zh_CN.ts

- 增加备份更新选项
- 未开启备份更新时增加弹窗提示
- 去掉重复的下载并安装按钮
- 全部更新文案改为下载更新
- 隐藏自动安装选项
Issue: https://github.com/linuxdeepin/developer-center/issues/8626

feat: add backup updates ui

---

src/frame/mainwindow.cpp

back button too small to click

chore: back button size tweak

---

debian/changelog

release 6.0.55
Log: bump version to 6.0.55

chore: bump version to 6.0.55

---

src/plugin-datetime/window/widgets/timezonechooser.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/8061

fix: lineedit background invisible

---

src/plugin-keyboard/window/shortcutsettingwidget.cpp
translations/dde-control-center_en.ts
translations/dde-control-center_zh_CN.ts

Update translation
Issue: https://github.com/linuxdeepin/developer-center/issues/8798

chore: Update translation

---

src/plugin-defaultapp/operation/defappworker.cpp
src/plugin-defaultapp/window/defappdetailwidget.cpp

去掉默认程序设置中的「深度」前缀
Issues: linuxdeepin/developer-center#6692

chore: use GenericName if X-Deepin-Vendor is 'deepin'

---

misc/configs/org.deepin.dde.control-center.personalization.json
src/plugin-personalization/operation/personalizationworker.cpp

Add configuration to hide upstream theme Papirus
Issue: https://github.com/linuxdeepin/developer-center/issues/9024

feat: add configuration for hidden icon themes

---

src/plugin-datetime/window/regionmodule.cpp
src/plugin-datetime/window/widgets/regionformatdialog.cpp

修复赛德克语地区名称错误，应该为「赛德克语(中国台湾)」
Issues: linuxdeepin/developer-center#5997

fix: 规范地区名称

---

debian/changelog

release 6.0.57
Log: bump versio to 6.0.57

chore: bump version to 6.0.57

---

src/plugin-sound/operation/soundeffectsmodel.cpp
src/plugin-sound/operation/soundeffectsmodel.h
src/plugin-sound/operation/soundmodel.cpp
src/plugin-sound/operation/soundmodel.h
src/plugin-sound/operation/soundworker.cpp
src/plugin-sound/operation/soundworker.h
src/plugin-sound/qml/SoundEffectsPage.qml

声音模块中的系统生效页面功能完成
Log: 完善系统生效页面的功能

feat: 声音模块中的系统生效页面功能完成

---

CMakeLists.txt
include/interface/dccapp.h
src/frame/dccmanager.cpp
src/frame/dccmanager.h
src/frame/pluginmanager.cpp
src/frame/pluginmanager.h
src/interface/dccapp.cpp
src/interface/dccmodel.cpp
src/interface/dccobject.cpp
src/plugin-defaultapp/operation/defappmodel.cpp

Add thread processing to plugin modules
Log:

feat: Add thread processing to plugin modules

---

debian/changelog
src/plugin-personalization-dock/operation/dockdbusproxy.cpp
src/plugin-personalization-dock/operation/dockdbusproxy.h
src/plugin-personalization-dock/window/dockplugin.cpp
src/plugin-personalization-dock/window/dockplugin.h

pass the paths of icons instead of the pixmap of icons
Log:

chore: compatible to new dock

---

src/plugin-sound/CMakeLists.txt
src/plugin-sound/operation/port.cpp
src/plugin-sound/operation/port.h
src/plugin-sound/operation/soundDeviceData.cpp
src/plugin-sound/operation/soundDeviceData.h
src/plugin-sound/operation/soundDeviceModel.cpp
src/plugin-sound/operation/soundDeviceModel.h
src/plugin-sound/operation/soundmodel.cpp
src/plugin-sound/operation/soundmodel.h
src/plugin-sound/operation/soundworker.cpp
src/plugin-sound/operation/soundworker.h
src/plugin-sound/qml/MicrophonePage.qml
src/plugin-sound/qml/SoundDevicemanagesPage.qml
src/plugin-sound/qml/SoundEffectsPage.qml
src/plugin-sound/qml/SpeakerPage.qml

The device management module function in the sound module is completed and the entire module spacing is adjusted.
Log:

feat: Sound module function improvement and interface spacing adjustment

---

src/plugin-sound/operation/soundmodel.cpp
src/plugin-sound/operation/soundmodel.h
src/plugin-sound/operation/soundworker.cpp
src/plugin-sound/qml/MicrophonePage.qml
src/plugin-sound/qml/SoundDevicemanagesPage.qml
src/plugin-sound/qml/SpeakerPage.qml

Mainly adjust the spacing and background of the input and output interfaces, and fix the problem of hiding other input settings when there is no input device
Log:

feat: Adjustment of the sound module interface spacing and background

---

debian/changelog

bump version to 6.0.59
Log: bump version to 6.0.59

chore: bump version to 6.0.59

---

debian/changelog

bump version to 6.0.60
Log: bump version to 6.0.60

chore: bump version to 6.0.60

---

src/plugin-personalization-dock/window/dockplugin.cpp

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10183
Influence: can set dock smart-hide

fix: can set dock smart-hide state

---

debian/changelog

bump version to 6.0.61
Log: bump version to 6.0.61

chore: bump version to 6.0.61

---

include/dccmodel.h
include/dccobject.h
qml/DccWindow.qml
qml/SecondPage.qml
src/dde-control-center/dccmanager.cpp
src/dde-control-center/frame/dccmodel.cpp
src/dde-control-center/frame/dccobject.cpp
src/dde-control-center/frame/plugin/DccEditorComponent.qml
src/dde-control-center/frame/plugin/DccGroupView.qml
src/dde-control-center/frame/plugin/DccItemComponent.qml
src/dde-control-center/frame/plugin/DccListViewBackground.qml
src/dde-control-center/frame/plugin/DccRightView.qml
src/dde-control-center/main.cpp
src/plugin-defaultapp/operation/defappmodel.cpp
src/plugin-defaultapp/qml/DetailItem.qml
src/plugin-defaultapp/qml/main.qml
src/plugin-mouse/operation/qrc/mouse.qrc
src/plugin-mouse/qml/Common.qml
src/plugin-mouse/qml/Mouse.qml
src/plugin-mouse/qml/Touchpad.qml
src/plugin-mouse/qml/main.qml
src/plugin-mouse/qml/mouse.qml

Adjust the interface of the mouse module
Log:

feat: Adjust the interface of the mouse module

---

src/dde-control-center/frame/dccmodel.cpp
src/dde-control-center/frame/plugin/DccEditorComponent.qml
src/dde-control-center/frame/plugin/DccMenuComponent.qml
src/plugin-sound/qml/DeviceListView.qml
src/plugin-sound/qml/SoundDevicemanagesPage.qml
src/plugin-sound/qml/SoundEffectsPage.qml
src/plugin-sound/qml/SpeakerPage.qml
src/plugin-sound/qml/main.qml
src/plugin-sound/qml/sound.qml

Adjust the interface of the sound module
Log:

feat: Adjust the interface of the sound module

---

src/plugin-sound/operation/soundmodel.h
src/plugin-sound/operation/soundworker.h
src/plugin-sound/qml/MicrophonePage.qml
src/plugin-sound/qml/SpeakerPage.qml
src/plugin-sound/qml/main.qml

feat: Adjust the sound input interface to adapt to the new framework of the control center

---

src/frame/completerview.cpp
src/frame/completerview.h
src/frame/searchwidget.cpp
src/frame/searchwidget.h

Modify the style of the search popup window
Log:

feat: Modify the style of the search popup window

---

src/frame/searchwidget.cpp

as title
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10398

fix: set search popup distance from searchLineEdit to 8

---

include/dccobject.h
qml/HomePage.qml
qml/SecondPage.qml
src/dde-control-center/controlcenterdbusadaptor.cpp
src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h
src/dde-control-center/frame/dccobject.cpp
src/dde-control-center/frame/plugin/DccEditorComponent.qml
src/dde-control-center/frame/plugin/DccItemComponent.qml
src/dde-control-center/frame/plugin/DccMenuComponent.qml
src/plugin-mouse/CMakeLists.txt

1.Implement item hiding and disabling functions
2.Delete the original window when switching window
Log:

feat: Implement item hiding and disabling functions

---

include/dccapp.h
qml/Crumb.qml
qml/DccWindow.qml
qml/HomePage.qml
qml/SecondPage.qml
src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h
src/dde-control-center/frame/dccapp.cpp
src/dde-control-center/frame/plugin/DccEditorComponent.qml
src/dde-control-center/frame/plugin/DccMenuComponent.qml
src/dde-control-center/navigationmodel.cpp
src/dde-control-center/navigationmodel.h

feat: Implement crumb control

---

src/plugin-defaultapp/qml/DetailItem.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

chore: Update translation files

---

include/dccapp.h
qml/Crumb.qml
qml/DccWindow.qml
qml/HomePage.qml
qml/SecondPage.qml
src/dde-control-center/controlcenterdbusadaptor.cpp
src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h
src/dde-control-center/frame/dccapp.cpp
src/dde-control-center/frame/dccmodel.cpp
src/dde-control-center/frame/dccobject.cpp
src/dde-control-center/frame/plugin/DccEditorComponent.qml
src/dde-control-center/frame/plugin/DccItemComponent.qml
src/dde-control-center/frame/plugin/DccLabel.qml
src/dde-control-center/frame/plugin/DccMenuComponent.qml

1. Adjust the homepage layout
2. Add ToolTip
Log:

feat: Adjust homepage layout

---

debian/changelog

bump version to 6.0.63
Log: bump version to 6.0.63

chore: bump version to 6.0.63

---

qml/DccWindow.qml
qml/HomePage.qml
qml/SecondPage.qml

- `Page` / `Pane` will eat mouse press event
- `Control` need hoverEnabled: false (from D.TitleBar)

fix: press and hold titlebar cannot move window

---

debian/changelog

bump version to 6.0.64
Log: bump version to 6.0.64

chore: bump version to 6.0.64

---

include/dccapp.h
include/dccobject.h
qml/DccWindow.qml
qml/HomePage.qml
qml/SearchBar.qml
qml/SecondPage.qml
src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h
src/dde-control-center/frame/dccmodel.cpp
src/dde-control-center/frame/dccobject.cpp
src/dde-control-center/frame/dccobject_p.h
src/dde-control-center/frame/plugin/DccEditorComponent.qml
src/dde-control-center/frame/plugin/DccItemComponent.qml
src/dde-control-center/frame/plugin/DccMenuComponent.qml
src/dde-control-center/frame/plugin/DccRightView.qml
src/dde-control-center/main.cpp

1.Improve the search interface
2.Implement search jump scrolling
Log:

feat: Improve the search interface

---

.reuse/dep5
CMakeLists.txt
dcc-old/CMakeLists.txt
dcc-old/src/frame/main.cpp
dcc-old/src/frame/pluginmanager.cpp
src/dde-control-center/dccmanager.cpp

Modify the translation file path to prevent conflicts between old and new version control center files
Log:

feat: Modify the translation file path

---

CMakeLists.txt
dcc-old/CMakeLists.txt
misc/dde-control-center.in
misc/translate_generation.sh

Translation file installation during packaging processing
Log:

feat: Dealing with packaging issues

---

CMakeLists.txt
dcc-old/src/plugin-systeminfo/operation/systeminfowork.cpp
qml/HomePage.qml
qml/SearchBar.qml
qml/SecondPage.qml
qml/plugins_v1.0/demo/demo.qml
qml/plugins_v1.0/system/system.qml
src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h
src/dde-control-center/frame/plugin/CMakeLists.txt
src/dde-control-center/frame/plugin/DccUtils.js
src/dde-control-center/pluginmanager.cpp
src/dde-control-center/pluginmanager.h
src/plugin-systeminfo/CMakeLists.txt
src/plugin-systeminfo/operation/systeminfointeraction.cpp
src/plugin-systeminfo/operation/systeminfointeraction.h
src/plugin-systeminfo/operation/systeminfowork.cpp
src/plugin-systeminfo/operation/utils.h
src/plugin-systeminfo/qml/main.qml
src/plugin-systeminfo/qml/systemInfo.qml

Use thread pool instead to dynamically load plugins based on configuration
Log:

feat: Implement dynamic loading of plugins

---

debian/changelog

chore: Bump version to 6.0.65

---

include/dccquickdbusinterface.h
src/dde-control-center/frame/dccquickdbusinterface.cpp
src/dde-control-center/frame/dccquickdbusinterface_p.h
src/dde-control-center/frame/plugin/src/dccqmlplugin.cpp
src/plugin-touchscreen/qml/main.qml
src/plugin-touchscreen/qml/touchscreen.qml

Export a dbus class for qml to use
Log:

feat: Add dbus class for qml

---

src/dde-control-center/frame/plugin/DccGroupView.qml

Set the default interval to 10
Log:

feat: Set the default interval to 10

---

include/dccquickdbusinterface.h
src/dde-control-center/dccmanager.cpp
src/dde-control-center/frame/dccquickdbusinterface.cpp
src/dde-control-center/frame/dccquickdbusinterface_p.h
src/plugin-touchscreen/qml/touchscreen.qml

Add the monitored Properties property to reduce data processing
Log:

feat: Optimize DBus class

---

src/dde-control-center/frame/plugin/DccTimeRange.qml

feat: Add DccTimeRange

---

dcc-old/src/plugin-personalization/operation/personalizationdbusproxy.cpp
dcc-old/src/plugin-personalization/operation/personalizationdbusproxy.h
dcc-old/src/plugin-personalization/operation/personalizationmodel.cpp
dcc-old/src/plugin-personalization/operation/personalizationmodel.h
dcc-old/src/plugin-personalization/operation/personalizationworker.cpp
dcc-old/src/plugin-personalization/operation/personalizationworker.h
dcc-old/src/plugin-personalization/window/personalizationdesktopmodule.cpp
dcc-old/translations/dde-control-center_zh_CN.ts
dcc-old/translations/dde-control-center_zh_HK.ts
dcc-old/translations/dde-control-center_zh_TW.ts
translations/dde-control-center.ts

As title
Log:
Task: https://pms.uniontech.com/task-view-362569.html

feat: add compact mode

---

dcc-old/src/plugin-update/operation/updatemodel.cpp
dcc-old/src/plugin-update/operation/updatemodel.h
dcc-old/src/plugin-update/operation/updatework.cpp
dcc-old/src/plugin-update/operation/updatework.h
dcc-old/src/plugin-update/window/updatesettingsmodule.cpp

Linglong app update transferred to deepin-app-store
Log: As title
Task: https://pms.uniontech.com/task-view-362429.html

feat: remove linglong update

---

dcc-old/src/plugin-personalization/window/personalizationdesktopmodule.cpp

As title
Log:
Task: https://pms.uniontech.com/task-view-362569.html

feat: hide compact mode

---

debian/changelog

release 6.0.66
Log: bump version to 6.0.66

chore: bump version to 6.0.66

---

src/dde-control-center/frame/plugin/SearchBar.qml

chore: export SearchBar

---

dcc-old/src/plugin-bluetooth/window/bluetoothdevicemodel.cpp

Bug: https://pms.uniontech.com/bug-view-271571.html
Log: incorrect bluetooth device icon theme type

fix: incorrect bluetooth device icon theme type

---

src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h
src/dde-control-center/frame/dccobject.cpp
src/dde-control-center/frame/dccobject_p.h
src/dde-control-center/pluginmanager.cpp
src/dde-control-center/pluginmanager.h
src/plugin-power/operation/powermodel.h
src/plugin-sound/operation/soundDeviceModel.h

Explicit deletion ensures the order of data deletion
Log:

feat: Modify the crash issue when exiting the control center

---

include/dccmodel.h
include/dccobject.h
qml/plugins_v1.0/system/system.qml
src/dde-control-center/controlcenterdbusadaptor.cpp
src/dde-control-center/dccmanager.cpp
src/dde-control-center/frame/dccmodel.cpp
src/dde-control-center/frame/dccobject.cpp
src/dde-control-center/frame/dccobject_p.h
src/dde-control-center/frame/plugin/DccCheckIcon.qml
src/dde-control-center/frame/plugin/DccEditorItem.qml
src/dde-control-center/frame/plugin/DccGroupView.qml
src/dde-control-center/frame/plugin/DccItem.qml
src/dde-control-center/frame/plugin/DccMenuEditorItem.qml
src/dde-control-center/frame/plugin/DccMenuItem.qml
src/dde-control-center/frame/plugin/DccRowView.qml
src/dde-control-center/frame/plugin/DccSettingsView.qml
src/dde-control-center/frame/plugin/DccTitleObject.qml
src/dde-control-center/pluginmanager.cpp

1. Implement dynamic weight modification and dynamic sorting
2. Add DccTitleObject
3. Add DccSetingsView processing settings interface
4. The default left and right margins are 10
Log:

feat: Implement dynamic weight modification and dynamic sorting

---

include/dccobject.h
qml/DccWindow.qml
qml/SecondPage.qml
src/dde-control-center/frame/dccobject.cpp
src/dde-control-center/frame/plugin/DccEditorItem.qml
src/dde-control-center/frame/plugin/DccGroupView.qml
src/dde-control-center/frame/plugin/DccItem.qml
src/dde-control-center/frame/plugin/DccListViewBackground.qml
src/dde-control-center/frame/plugin/DccMenuEditorItem.qml
src/dde-control-center/frame/plugin/DccRowView.qml
src/dde-control-center/frame/plugin/DccSettingsView.qml

Page control to parent object
Log:

feat: Page control to parent object

---

src/plugin-systeminfo/operation/systeminfodbusproxy.cpp
src/plugin-systeminfo/operation/systeminfodbusproxy.h
src/plugin-systeminfo/operation/systeminfomodel.cpp
src/plugin-systeminfo/operation/systeminfomodel.h
src/plugin-systeminfo/operation/systeminfowork.cpp
src/plugin-systeminfo/operation/systeminfowork.h
src/plugin-systeminfo/qml/NativeInfoPage.qml
src/plugin-systeminfo/qml/PrivacyPolicyPage.qml
src/plugin-systeminfo/qml/UserExperienceProgramPage.qml
src/plugin-systeminfo/qml/main.qml

Log: Fix issues related to system information
Bug: https://pms.uniontech.com/bug-view-274991.html
Bug: https://pms.uniontech.com/bug-view-274919.html
Bug: https://pms.uniontech.com/bug-view-274911.html

Fix: Fix issues related to system information

---

dcc-old/src/plugin-update/operation/mirrorsourceitem.cpp
dcc-old/src/plugin-update/operation/mirrorsourceitem.h
dcc-old/src/plugin-update/operation/qrc/update.qrc
dcc-old/src/plugin-update/operation/updatedbusproxy.cpp
dcc-old/src/plugin-update/operation/updatedbusproxy.h
dcc-old/src/plugin-update/operation/updatemodel.cpp
dcc-old/src/plugin-update/operation/updatemodel.h
dcc-old/src/plugin-update/operation/updatework.cpp
dcc-old/src/plugin-update/operation/updatework.h
dcc-old/src/plugin-update/window/mirrorswidget.cpp
dcc-old/src/plugin-update/window/mirrorswidget.h
dcc-old/src/plugin-update/window/updatesettingsmodule.cpp
dcc-old/src/plugin-update/window/updatesettingsmodule.h
dcc-old/translations/dde-control-center_zh_CN.ts
debian/control

Add smart mirror
Log:
Task: https://pms.uniontech.com/task-view-363661.html

feat: Add smart mirror

---

debian/changelog

release 6.0.67
Log: bump version to 6.0.67

chore: bump version to 6.0.67

---

debian/changelog

release 6.0.68
Log: bump version to 6.0.68

chore: bump version to 6.0.68

---

dcc-old/src/plugin-datetime/window/regionmodule.cpp
dcc-old/src/plugin-datetime/window/regionmodule.h
dcc-old/translations/dde-control-center_en.ts
dcc-old/translations/dde-control-center_zh_CN.ts

add the country feature
Bug: https://pms.uniontech.com/story-view-36709.html
Log:

chore: add the country feature

---

debian/changelog

Release 6.0.69
Log: bump version to 6.0.69

chore: bump version to 6.0.69

---

src/dde-control-center/frame/plugin/DccListViewBackground.qml

feat: DccListViewBackground add backgroundColor property

---

dcc-old/src/plugin-bluetooth/window/bluetoothdevicemodel.cpp

Bug: https://pms.uniontech.com/bug-view-275675.html Log:

fix: Unknown bluetooth device name not handled

---

include/dccrepeater.h
src/dde-control-center/frame/dccrepeater.cpp

- fix member not init
- add invokeAble function `resetModel`

chore: add resetModel and init member

---

src/dde-control-center/frame/dccrepeater.cpp
src/plugin-datetime/qml/ComboLabel.qml
src/plugin-datetime/qml/LangAndFormat.qml

dccRepeater langformart tweak

---

src/plugin-datetime/operation/datetimemodel.h
src/plugin-datetime/qml/DateTimeSettingDialog.qml
src/plugin-datetime/qml/TimeAndDate.qml

- 实时更新日期
- 设置日期时『日』根据『年』『月』设置最大天数（防止出现 2月30日）
- 允许设置空的自定义 ntp 地址 :)
Bug: https://pms.uniontech.com/bug-view-278637.html

fix: date not changed after time set

---

debian/changelog

chore: Bump version to 6.0.70

---

src/plugin-commoninfo/qml/BootPage.qml

Log: Fix init boot menu popup polikt-agent window
BUg: https://pms.uniontech.com/task-view-364169.html

Fix: Fix init boot menu popup polikt-agent window

---

dcc-old/src/frame/mainmodule.cpp
dcc-old/src/interface/pagemodule.cpp
dcc-old/src/plugin-display/window/multiscreenwidget.cpp
dcc-old/src/plugin-display/window/multiscreenwidget.h
dcc-old/src/plugin-personalization-dock/window/dockplugin.cpp
dcc-old/src/plugin-personalization/window/personalizationdesktopmodule.cpp
dcc-old/src/plugin-personalization/window/personalizationdesktopmodule.h
dcc-old/src/widgets/itemmodule.cpp

- Adjust the spacing of the homepage sidebar
- Adjust the item spacing of PageModule
- Optimize the height change logic of the dock plugin list
Bug:
https://pms.uniontech.com/bug-view-280097.html
https://pms.uniontech.com/bug-view-279975.html

fix: adapt to compact mode

---

src/dde-control-center/frame/plugin/DccGroupView.qml

in Group
- remove `topInset` and `bottomInset`
- corners tweak

chore: menu item support in group

---

src/dde-control-center/frame/plugin/DccEditorItem.qml

ItemViewport to set icon radius

feat: DccEditorItem support iconRadius/iconSize

---

debian/changelog

fix: adapt to compact mode
Log: bump version to 6.0.71

chore: bump version to 6.0.71

---

debian/changelog

release 6.0.72
Log: bump version to 6.0.72

chore: bump version to 6.0.72

---

qml/DccWindow.qml
src/dde-control-center/frame/plugin/DccItem.qml

fix: Specify the control that uses DTK

---

src/plugin-personalization/CMakeLists.txt

chore: build option tweak

---

debian/control
src/plugin-personalization/operation/treelandworker.cpp
src/plugin-personalization/operation/treelandworker.h

chore: add dialogs dep and package treeland header file

---

dcc-old/src/dcc-agent/main.c
dcc-old/src/plugin-update/window/mirrorswidget.cpp

Modify the scrollbar spacing in the mirror source list
Log:
Bug: https://pms.uniontech.com/bug-view-279291.html

fix: Modify the scrollbar spacing in the mirror source list

---

dcc-old/src/plugin-keyboard/operation/shortcutmodel.cpp
src/plugin-keyboard/operation/shortcutmodel.cpp

Log: Display zoom screen shortcuts in control center

feat: Display zoom screen shortcuts in control center

---

src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/operation/personalizationworker.h
src/plugin-personalization/operation/qrc/personalization.qrc
src/plugin-personalization/operation/qrc/texts/download-more_84px.svg
src/plugin-personalization/qml/IconThemeGridView.qml
src/plugin-personalization/qml/ThemeSelectView.qml
src/plugin-personalization/qml/WindowEffectPage.qml

- 增加缺失的下载更多按钮
- 修复光标主题图标主题背景色异常
- 修复界面上紧凑模式不显示
Log:
Task: https://pms.uniontech.com/task-view-364175.html Bug: https://pms.uniontech.com/bug-view-284271.html

fix: Fix some personalized bugs

---

debian/changelog

release 6.0.73
Log: bump version to 6.0.73

chore: bump version to 6.0.73

---

src/plugin-datetime/operation/datetimedbusproxy.cpp

chore: format dbus interface name changed

---

src/plugin-datetime/operation/keyboard/keyboarddbusproxy.cpp
src/plugin-datetime/operation/keyboard/keyboarddbusproxy.h
src/plugin-datetime/operation/keyboard/keyboardwork.cpp
src/plugin-datetime/qml/datetime.qml
src/plugin-keyboard/qml/keyboard.qml

- datetime only need `LangSelector`, remove `Keybinding`, `wm`, `KeyboardLayout`
- test LangSelector1.Locales to avoid service blocked
- test Keybinding1.NumLockState to avoid service blocked

chore: donot show keyboard if Keybinding dbus not exists

---

dcc-old/src/plugin-personalization/operation/personalizationdbusproxy.cpp
dcc-old/src/plugin-personalization/operation/personalizationdbusproxy.h
dcc-old/src/plugin-personalization/operation/personalizationworker.cpp
dcc-old/src/plugin-personalization/operation/personalizationworker.h
dcc-old/src/plugin-personalization/window/personalizationthememodule.cpp
dcc-old/src/plugin-personalization/window/widgets/roundcolorwidget.cpp
dcc-old/src/plugin-personalization/window/widgets/roundcolorwidget.h

add active colors in dark theme
Bug: https://pms.uniontech.com/bug-view-283171.html
Log:

fix: active color is incorrect in dark theme

---

dcc-old/src/dcc-agent/main.c

Default use of the new version of Control Center
Log:

feat: Default use of the new version of Control Center

---

src/dde-control-center/pluginmanager.cpp
src/dde-control-center/pluginmanager.h
src/plugin-bluetooth/qml/Adapters.qml
src/plugin-bluetooth/qml/BlueToothDeviceListView.qml
src/plugin-bluetooth/qml/main.qml

Log: Solve the problem of abnormal display of Bluetooth module
Bug: https://pms.uniontech.com/bug-view-283379.html

Fix: Solve the problem of abnormal display of Bluetooth module

---

src/plugin-personalization/qml/WindowEffectPage.qml

as title
Bug: https://pms.uniontech.com/bug-view-286305.html

fix: When adjusting transparency, there will be a cyclic jump

---

src/plugin-systeminfo/operation/systeminfodbusproxy.cpp
src/plugin-systeminfo/operation/systeminfodbusproxy.h
src/plugin-systeminfo/operation/systeminfowork.cpp
src/plugin-systeminfo/qml/NativeInfoPage.qml

Log: get timezone form freedesktop timedate dbus
Bug: https://pms.uniontech.com/bug-view-282825.html
Bug: https://pms.uniontech.com/bug-view-282823.html

Fix: Solve system timezone Unavailable

---

debian/changelog
debian/control

release 6.0.75
Log: bump version to 6.0.75

chore: bump version to 6.0.75

---

misc/configs/org.deepin.dde.control-center.power.json
src/plugin-power/operation/powerdbusproxy.cpp
src/plugin-power/operation/powerdbusproxy.h
src/plugin-power/operation/powermodel.cpp
src/plugin-power/operation/powermodel.h
src/plugin-power/operation/powerworker.cpp
src/plugin-power/operation/powerworker.h
src/plugin-power/qml/BatteryPage.qml
src/plugin-power/qml/CustomComboBox.qml
src/plugin-power/qml/GeneralPage.qml
src/plugin-power/qml/PowerPlansListview.qml

add scheduled shutdown
Log:
Bug:
- https://pms.uniontech.com/bug-view-281959.html
- https://pms.uniontech.com/bug-view-281949.html
- https://pms.uniontech.com/bug-view-281937.html
- https://pms.uniontech.com/bug-view-281599.html
- https://pms.uniontech.com/bug-view-281583.html
- https://pms.uniontech.com/bug-view-282057.html
- https://pms.uniontech.com/bug-view-281607.html
- https://pms.uniontech.com/bug-view-281589.html
- https://pms.uniontech.com/bug-view-281585.html
- https://pms.uniontech.com/bug-view-281593.html

fix(dccNew-power): supplement feature and fix issues

---

src/dde-control-center/pluginmanager.cpp
src/dde-control-center/pluginmanager.h

Multiple creation issues with modifying plugin objects
Log:

fix: Multiple creation issues with modifying plugin objects

---

CMakeLists.txt
examples/plugin-example/qml/ExamplePage3.qml
examples/plugin-example/qml/main.qml
src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h
src/dde-control-center/frame/plugin/DccSettingsObject.qml
src/dde-control-center/searchmodel.cpp

fix: Add DccSetingsObject

---

src/plugin-keyboard/qml/keyboard.qml

fix: modify keyboard name

---

src/dde-control-center/main.cpp
src/dde-control-center/pluginmanager.cpp

The thread pool for analysis is stuck
Log:

fix: The thread pool for analysis is stuck

---

src/plugin-touchscreen/qml/TouchScreen.qml

Fix the issue where the touch screen monitor name can be selected.
Log: Fix the issue where the touch screen monitor name can be selected.
pms: BUG-275119

fix: Touch screen monitor name can be selected.

---

src/plugin-notification/qml/main.qml

Fix issue where app notification interface occasionally displays items out of order
Log: Fix issue where app notification interface occasionally displays items out of order

fix: Display disorder in the notification module.

---

src/plugin-power/qml/power.qml

as title
Log:
pms: Task-365811

feat(power): add Dbus judgment

---

src/plugin-mouse/qml/mouse.qml
src/plugin-sound/qml/sound.qml

Hide modules that do not exist in dbus
Log: Hide modules that do not exist in dbus

feat: Hide modules that do not exist in dbus

---

src/plugin-personalization/operation/personalizationinterface.cpp
src/plugin-personalization/operation/personalizationinterface.h
src/plugin-personalization/qml/WindowEffectPage.qml

hide some function on wayland
pms: Task-364175

feat(personalization): add wayland judgement

---

debian/changelog

chore: bump version to 6.0.76.2

---

src/dde-control-center/frame/dccobject.cpp
src/dde-control-center/pluginmanager.cpp
src/plugin-wacom/qml/wacom.qml

1.Add DCI search path
2.wacom is not visible by default
pms: Task-364175

fix: Add DCI search path

---

src/dde-control-center/pluginmanager.cpp

fix: loading plugin crashed

---

src/plugin-datetime/operation/regionproxy.cpp
src/plugin-datetime/qml/ComboLabel.qml

- Combobox enable hover(DccEditorItem hoverEnabled may should changed)
- CN format tweak remove `aphh:mm`

chore: time date tweak

---

src/dde-control-center/frame/plugin/DccEditorItem.qml
src/dde-control-center/frame/plugin/DccItem.qml
src/dde-control-center/frame/plugin/DccItemBackground.qml

The hoverEnabled of DccItem defaults to true
pms: Task-361721

fix: The hoverEnabled of DccItem defaults to true

---

src/plugin-datetime/qml/TimeAndDate.qml

fix: ntp server list can not scroll

---

src/plugin-personalization/operation/keyfile.cpp
src/plugin-personalization/operation/keyfile.h
src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/operation/personalizationworker.h
src/plugin-personalization/operation/treelandworker.cpp
src/plugin-personalization/operation/treelandworker.h
src/plugin-personalization/operation/utils.hpp
src/plugin-personalization/qml/FontSizePage.qml
src/plugin-personalization/qml/ThemeSelectView.qml
src/plugin-personalization/qml/WindowEffectPage.qml
src/plugin-personalization/qml/main.qml

feat: Treeland adaptation of personalized modules

---

dcc-old/src/plugin-datetime/operation/regionproxy.cpp
src/plugin-datetime/operation/datetimemodel.cpp
src/plugin-datetime/operation/datetimemodel.h
src/plugin-datetime/operation/datetimeworker.cpp
src/plugin-datetime/operation/datetimeworker.h
src/plugin-datetime/operation/langregionmodel.cpp
src/plugin-datetime/operation/languagelistmodel.cpp
src/plugin-datetime/operation/regionproxy.cpp
src/plugin-datetime/operation/zoneinfo.h
src/plugin-datetime/operation/zoneinfomodel.cpp
src/plugin-datetime/operation/zoneinfomodel.h
src/plugin-datetime/qml/SearchableListViewPopup.qml
src/plugin-datetime/qml/TimeAndDate.qml
src/plugin-datetime/qml/TimezoneDialog.qml

- 修复 model 和 worker 循环调用的问题
- 用户时区列表改成 DccRepeater 的方式
- ap/Ap == > AP
pms: Bug-286943

fix: system timezone setting error

---

src/plugin-keyboard/operation/shortcutmodel.cpp

fix: zoom shortcut filter tweak

---

src/dde-control-center/frame/dccobject.cpp
src/dde-control-center/frame/dccobject_p.h

Create a new object when calling getSectionItem

fix: Create a new object when calling getSectionItem

---

src/plugin-personalization/operation/personalizationdbusproxy.cpp
src/plugin-personalization/operation/personalizationdbusproxy.h
src/plugin-personalization/operation/personalizationinterface.cpp
src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/operation/personalizationworker.h
src/plugin-personalization/operation/treelandworker.cpp

fix: Personalization module starts slowly in Treeland

---

src/plugin-personalization/operation/personalizationdbusproxy.cpp
src/plugin-personalization/operation/personalizationdbusproxy.h
src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/operation/personalizationworker.h
src/plugin-personalization/qml/ColorAndIcons.qml

设置活动色前需要先设置activeColors
pms: TASK-365811

fix: Setting activity color invalid

---

src/plugin-datetime/operation/datetimemodel.cpp
src/plugin-datetime/operation/datetimemodel.h
src/plugin-datetime/operation/datetimeworker.cpp
src/plugin-datetime/operation/keyboard/keyboarddbusproxy.h
src/plugin-datetime/qml/LangAndFormat.qml
src/plugin-datetime/qml/LangsChooserDialog.qml

add Busyindicator to indicate setting state
pms: Bug-286647

fix: language set failed

---

.obs/workflows.yml

feat: Update workflows.yml

---

src/plugin-deepinid/qml/deepinid.qml

update deepinid description
Log: as title

fix: update deepinid description

---

src/plugin-personalization/qml/FontCombobox.qml

使用modelData去拿数据
pms: Task-36871

fix: font Combobox is empty

---

src/plugin-display/CMakeLists.txt

fix(build): display module arm64 build failed

---

.obs/workflows.yml

fix: Update workflows.yml

---

src/plugin-update/qml/main.qml

Modify update description
Log: Modify update description
pms: TASK-367053

fix: Modify update description

---

src/plugin-datetime/qml/DateTimeSettingDialog.qml
src/plugin-datetime/qml/LangAndFormat.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

chore: init ts files

---

src/plugin-power/qml/BatteryPage.qml
translations/dde-control-center_zh_CN.ts

chore: update power translations

---

translations/dde-control-center_zh_CN.ts

Update translations for Bluetooth, General, System Information, Sound, etc.
Log: Update translations for Bluetooth, General, System Information, Sound, etc.
pms: TASK-367053

feat: Update translations for Bluetooth, General, System Information

---

src/plugin-accounts/qml/AccountSettings.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

update datetime,region and language, acccount translations

chore: update datetime/accounts translations

---

src/plugin-personalization/operation/personalizationinterface.cpp
src/plugin-personalization/operation/personalizationinterface.h
src/plugin-personalization/qml/InterfaceEffectListview.qml
src/plugin-personalization/qml/ThemeSelectView.qml
src/plugin-personalization/qml/main.qml
src/plugin-power/qml/main.qml
src/plugin-power/qml/power.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

as title
pms: TASK-364175, TASK-362041

chore: update power and personalization translations

---

src/plugin-deepinid/qml/LoginPage.qml
src/plugin-notification/qml/main.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

Update display,notification,deepinid,wacom,touchscreen translation

feat: Update display,notification,deepinid,wacom,touchscreen translation

---

src/dde-control-center/controlcenterdbusadaptor.cpp
src/dde-control-center/controlcenterdbusadaptor.h
src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h
src/dde-control-center/frame/dccobject.cpp
src/dde-control-center/pluginmanager.h

Modifying DBus cannot redirect properly
pms: BUG-361721
pms: BUG-288713

fix: Modifying DBus cannot redirect properly

---

src/plugin-sound/qml/AudioServerSetting.qml
src/plugin-sound/qml/soundMain.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

update audio framework translations
Log: update audio framework translations

feat: update audio framework translations

---

src/plugin-power/qml/GeneralPage.qml

fix(power): The sliding bar scale value is incorrect

---

src/plugin-datetime/qml/TimeAndDate.qml

use SearchableListViewPopup loader to show custom timezone datas 
pms: Bug-286759

fix: system/custom timezone datas affect each other

---

src/plugin-commoninfo/qml/commonInfoMain.qml

hidden developer mode
Log: hidden developer mode
pms: BUG-281701

fix: hidden developer mode

---

src/plugin-personalization/qml/ColorAndIcons.qml

chore(personalization): update activeColor list

---

src/plugin-datetime/qml/datetime.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

display name and description name tweak

chore: update date and time translations

---

src/plugin-sound/qml/sound.qml
src/plugin-systeminfo/qml/systemInfoMain.qml

add sound description
Log: add sound description

feat: add sound description

---

src/dde-control-center/dccmanager.cpp
src/plugin-defaultapp/qml/defaultapp.qml
src/plugin-display/qml/display.qml
src/plugin-notification/qml/notification.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

Update menu item description
pms: Task-361721

feat: Update menu item description

---

src/plugin-personalization/operation/personalizationmodel.cpp
src/plugin-personalization/operation/personalizationmodel.h
src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/operation/personalizationworker.h
src/plugin-personalization/qml/WallpaperPage.qml

Using data from the backend
pms: TASK-290095

fix(personnalization): screen select combobox is empty

---

src/plugin-keyboard/qml/Shortcuts.qml
src/plugin-keyboard/qml/keyboardMain.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

chore: udpate keyboard shortcut translations

---

misc/DdeControlCenterPluginMacros.cmake
src/dde-control-center/CMakeLists.txt

Translation processing contains too many files
pms: Task-361721

feat: Modify translation processing errors

---

CMakeLists.txt

fix: wrong lib install path

---

misc/configs/org.deepin.dde.control-center.accounts.json
src/plugin-bluetooth/operation/bluetoothadaptersmodel.cpp
src/plugin-bluetooth/qml/blueTooth.qml
src/plugin-sound/qml/SpeakerPage.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

update bluetooth translation
Log: update bluetooth translation
pms: BUG-283323, Bug-292411

Fix: update bluetooth translation

---

qml/DccWindow.qml

chore: dcc focus tweak

---

src/plugin-sound/operation/sounddbusproxy.cpp
src/plugin-sound/operation/sounddbusproxy.h
src/plugin-sound/operation/soundmodel.cpp
src/plugin-sound/operation/soundmodel.h
src/plugin-sound/operation/soundworker.cpp
src/plugin-sound/operation/soundworker.h
src/plugin-sound/qml/SpeakerPage.qml

add audio Mono
Log: add audio Mono

feat: add audio Mono

---

src/plugin-deepinid/qml/deepinid.qml

set displayName to "deepin ID"
pms: Bug-291175

fix: modify deepinid module display name

---

src/plugin-keyboard/qml/KeyboardLayout.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

【如需添加或切换键盘布局，请同时在输入法管理中添加对应的输入法以确保生效】
Add the corresponding input method in Input Method Management to ensure the keyboard layout works when added or switched.

chore: add keboard layout tips

---

src/plugin-datetime/qml/LangAndFormat.qml
src/plugin-datetime/qml/TimeAndDate.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

chore: update datetime/language translations

---

src/plugin-keyboard/qml/KeyboardLayout.qml
src/plugin-keyboard/qml/keyboard.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

chore: keyboard translations tweak

---

src/plugin-update/operation/updatemodel.cpp
src/plugin-update/operation/updatemodel.h
src/plugin-update/operation/updatework.cpp
src/plugin-update/operation/updatework.h
src/plugin-update/qml/UpdateControl.qml

Fix incorrect page status after the update is completed
Log: Fix incorrect page status after the update is completed
pms: BUG-292075

fix: Fix incorrect page status after the update is completed

---

src/dde-control-center/dccmanager.cpp
src/dde-control-center/pluginmanager.cpp

ShowPage with command does not display actively
Log:

fix: ShowPage with command does not display actively

---

translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

add update translation
Log: add update translationcompleted
pms: BUG-292075

fix: add update translation

---

src/plugin-personalization/qml/ColorAndIcons.qml
src/plugin-power/operation/powerinterface.cpp
src/plugin-power/operation/powerinterface.h
src/plugin-power/qml/BatteryPage.qml
src/plugin-power/qml/GeneralPage.qml
src/plugin-power/qml/PowerPage.qml

chore: hide some module on treeland

---

debian/changelog

chore: bump version to 6.0.77

---

src/plugin-datetime/qml/TimeAndDate.qml

- ntp server edit force focus on Completed
- edit visible on ntp enbale
- edit icon remove flat property

chore: date time tweak

---

src/plugin-systeminfo/operation/systeminfointeraction.cpp
src/plugin-systeminfo/operation/systeminfointeraction.h
src/plugin-systeminfo/operation/systeminfowork.cpp
src/plugin-systeminfo/operation/systeminfowork.h
src/plugin-systeminfo/qml/UserExperienceProgramPage.qml

Change User Experience Program pop-up window to modal
Log: Change User Experience Program pop-up window to modal
pms: BUG-290033

fix: Change User Experience Program pop-up window to modal

---

src/plugin-accounts/operation/accountscontroller.cpp
src/plugin-accounts/qml/AccountSettings.qml
src/plugin-accounts/qml/EditActionLabel.qml

- add fullname check
- remove empty string
- show alert text
pms: Bug-292943

fix: set fullname not checked

---

src/plugin-personalization/qml/WallpaperSelectView.qml

feat: wallpaper module optimization

---

src/plugin-accounts/operation/accountscontroller.cpp
src/plugin-accounts/operation/accountscontroller.h
src/plugin-accounts/operation/accountsworker.cpp
src/plugin-accounts/operation/usermodel.cpp
src/plugin-accounts/operation/usermodel.h
src/plugin-accounts/qml/AccountSettings.qml
src/plugin-accounts/qml/LoginMethod.qml

pms：Bug-292467， Bug-292949， Bug-292543

fix: online user password can be changed / user type changed not work

---

src/plugin-commoninfo/operation/commoninfomodel.cpp
src/plugin-commoninfo/operation/commoninfomodel.h
src/plugin-commoninfo/operation/commoninfowork.cpp
src/plugin-commoninfo/qml/DevelopModePage.qml

Change User DevelopMode license pop-up window to modal
Log: Change User DevelopMode license pop-up window to modal
pms: BUG-290077

fix: Change User DevelopMode license pop-up window to modal

---

src/plugin-bluetooth/qml/BlueToothDeviceListView.qml
src/plugin-bluetooth/qml/BluetoothCtl.qml
src/plugin-sound/qml/SoundDevicemanagesPage.qml
src/plugin-sound/qml/soundMain.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

update sound and bluetooth description
Log: update sound and bluetooth descriptionmodal
pms: BUG-293617

fix: update sound and bluetooth description

---

src/plugin-datetime/qml/datetime.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

- fix typo
- 地区 ==> 区域
- 时间日期 ==> 时间和日期
pms: Bug-293905， Bug-293981

chore: Date and time, Language and region translations tweak

---

qml/DccWindow.qml
src/plugin-accounts/operation/accountscontroller.cpp
src/plugin-accounts/operation/accountscontroller.h
src/plugin-accounts/operation/usermodel.cpp
src/plugin-accounts/operation/usermodel.h
src/plugin-accounts/qml/LoginMethod.qml

- fix spinbox focus can not clear
- 使用 timer 1 秒之后才出发设置,优化操作体验
- 设置密码中途取消或者出错恢复原来设置
pms: Bug-292701
pms: Bug-292707

Account bug fix(spinbox focus && passwordage )

---

src/plugin-mouse/operation/mousemodel.cpp
src/plugin-mouse/operation/mousemodel.h
src/plugin-mouse/qml/Touchpad.qml

Added logic to disable touchpad functionality when inputting
pms: BUG-284881

fix: Disabling touchpad function during input is ineffective

---

src/plugin-sound/operation/soundmodel.cpp
src/plugin-sound/operation/soundmodel.h
src/plugin-sound/operation/soundworker.cpp
src/plugin-sound/operation/soundworker.h
src/plugin-sound/qml/MicrophonePage.qml
src/plugin-sound/qml/SpeakerPage.qml

fix Inserting and unplugging sound devices, abnormal display in device selection box
Log: fix Inserting and unplugging sound devices, abnormal display in device selection box
pms: BUG-291981

fix: fix Inserting and unplugging sound devices, abnormal display in 

---

src/plugin-accounts/operation/accountscontroller.cpp
src/plugin-accounts/operation/accountscontroller.h
src/plugin-accounts/qml/AccountSettings.qml

groups settings only show in uos (?_?)
pms: Bug-293977

fix: groups settings visible in deepin

---

src/plugin-bluetooth/qml/BlueToothDeviceListView.qml

When the theme is in dark mode Background color inquiry
Log: When the theme is in dark mode Background color inquiry
pms: BUG-292509

fix: When the theme is in dark mode Background color inquiry

---

src/plugin-sound/operation/soundworker.cpp

Hide Pulseaudio under Treeland
Log: Hide Pulseaudio under Treeland
pms: BUG-294583

fix: Hide Pulseaudio under Treeland

---

src/plugin-sound/qml/MicrophonePage.qml
src/plugin-sound/qml/SpeakerPage.qml

Upon entering/returning to the sound interface, you will hear sound effects
Log: Upon entering/returning to the sound interface, you will hear sound effects
pms: BUG-291831

fix: Upon entering/returning to the sound interface, you hear sound effects

---

src/plugin-mouse/operation/mousemodel.cpp
src/plugin-mouse/operation/mousemodel.h
src/plugin-mouse/qml/Touchpad.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

Modify the touchpad switch control logic
pms: BUG-294279

fix: The touchpad switch is invalid

---

qml/DccWindow.qml
qml/SecondPage.qml
qml/plugins_v1.0/device/device.qml
qml/plugins_v1.0/system/system.qml
src/dde-control-center/dccmanager.cpp
src/plugin-accounts/qml/accounts.qml
src/plugin-deepinid/qml/deepinid.qml
src/plugin-personalization/qml/personalization.qml
src/plugin-power/qml/power.qml

1.Disable homepage
2.Update weight

feat: Disable homepage

---

src/plugin-display/operation/dccscreen.cpp

In copy mode, the resolution setting has not been confirmed
pms: BUG-293329

fix: In copy mode, the resolution setting has not been confirmed

---

src/plugin-sound/operation/soundmodel.cpp

sound data not init
Log: sound data not init
pms: BUG-291831

fix: sound data not init

---

src/plugin-accounts/operation/accountlistmodel.cpp
src/plugin-accounts/operation/accountlistmodel.h
src/plugin-accounts/operation/accountscontroller.cpp
src/plugin-accounts/operation/accountscontroller.h
src/plugin-accounts/operation/accountsworker.cpp
src/plugin-accounts/qml/AccountSettings.qml
src/plugin-accounts/qml/accountsMain.qml

- use listview instead of dccrepeater
- add model instead of stringlist 
pms: Bug-292919

chore: add group model and group listview

---

src/plugin-power/qml/BatteryPage.qml
src/plugin-power/qml/GeneralPage.qml
src/plugin-power/qml/powerMain.qml

chore(power): hide some module on treeland

---

src/plugin-sound/operation/soundmodel.cpp
src/plugin-sound/qml/SpeakerPage.qml

inPutPortComboEnable data not init
Log: inPutPortComboEnable data not init
pms: BUG-291831

fix: inPutPortComboEnable data not init

---

src/plugin-personalization/operation/personalizationdbusproxy.cpp
src/plugin-personalization/operation/personalizationdbusproxy.h
src/plugin-personalization/operation/x11worker.cpp
src/plugin-personalization/operation/x11worker.h
src/plugin-personalization/qml/WallpaperSelectView.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

- 全部设置修改为设置桌面
- 修复设置锁屏不生效
pms: BUG-295017
pms: BUG-294993
pms: BUG-294645
pms: BUG-294587

fix: all settings should be set as desktop settings

---

src/plugin-accounts/operation/accountlistmodel.cpp

if fullname is not empty show fullname
pms: Bug-292931

fix: fullname not show in accounts list

---

src/plugin-deepinid/operation/deepinidworker.cpp

Differentiate between community and professional editions
pms: Bug-292385

fix: web settings failed on the professional version

---

debian/changelog

chore: bump version to 6.0.78

---

dcc-old/src/dcc-agent/main.c

default dcc is old dcc at v23
Log:

chore: default dcc is old dcc at v23

---

dcc-old/src/plugin-datetime/operation/regionproxy.cpp
src/plugin-datetime/operation/regionproxy.cpp

fix: long date formats error

---

src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h

After the DBus jump, it was overwritten by the initialization jump
Log:
pms: BUG-289699

fix: Failed to modify DBus jump issue

---

src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/operation/personalizationworker.h
src/plugin-personalization/operation/treelandworker.cpp
src/plugin-personalization/operation/treelandworker.h

Pixel size not converted to point size.
pms: BUG-294655

fix: font size incorrect when set global theme

---

src/plugin-personalization/qml/IconThemeGridView.qml
src/plugin-personalization/qml/ThemeSelectView.qml
src/plugin-personalization/qml/WallpaperSelectView.qml

fix(personalization): image is unclear

---

debian/changelog

chore: bump version to 6.1.0

---

src/plugin-sound/operation/soundworker.cpp

Before playing sound effects rebuild QSoundEffect
Log: Before playing sound effects rebuild QSoundEffect
pms: BUG-292375

fix: Before playing sound effects rebuild QSoundEffect

---

src/dde-control-center/dccmanager.cpp

The homepage modification caused an error in the jump logic
Log:
pms: BUG-289699

fix: Modify control center jump error

---

src/plugin-sound/qml/SpeakerPage.qml

hide mono Audio under pipewire
Log: hide mono Audio under pipewire
pms: BUG-294171

fix: hide mono Audio under pipewire

---

src/dde-control-center/frame/plugin/DccLabel.qml
src/plugin-accounts/qml/AccountSettings.qml
src/plugin-accounts/qml/LoginMethod.qml

set opacity of disabled item icon
https://github.com/linuxdeepin/dtkdeclarative/pull/435
https://github.com/linuxdeepin/dtkdeclarative/pull/433

fix: disabled lable and combobox opacity not changed

---

dcc-old/src/plugin-accounts/window/avatarlistwidget.cpp

fix: emoji icons hide

---

dcc-old/src/plugin-accounts/window/avatarlistwidget.cpp

 fix: emoji icons hide

---

dcc-old/src/plugin-personalization/window/personalizationthememodule.cpp

update color of roundWidget
pms: BUG-295685

fix: wrong color of roundWidget

---

src/plugin-sound/operation/sounddbusproxy.cpp

send Audio Mono Changed SIGNAL
Log: send Audio Mono Changed SIGNAL
pms: BUG-292137

fix: send Audio Mono Changed SIGNAL

---

debian/changelog

release 6.1.1
Log: bump version to 6.1.1

chore: bump version to 6.1.1

---

src/plugin-update/operation/updatemodel.cpp

add init action Button Text
Log: add init action Button Text
pms: BUG-296777

fix: add init action Button Text

---

src/plugin-datetime/qml/RegionsChooserWindow.qml

fix: region chooser window color and position error

---

src/plugin-datetime/qml/RegionFormatDialog.qml

fix: RegionFormatDialog view background missing

---

src/plugin-accounts/qml/accountsMain.qml

使用一个item 加 listview 加载，高度最多显示 10 个账户，可以滚动
自测超过 150 个账户不卡顿
pms: Bug-292891

chore: account view loading speed optimized

---

src/plugin-personalization/operation/personalizationmodel.cpp
src/plugin-personalization/operation/personalizationmodel.h
src/plugin-personalization/operation/x11worker.cpp
src/plugin-personalization/operation/x11worker.h

use default if value is invalid
pms: BUG-289525

fix: option to set the 'titlebarHeight' for Combbox is empty

---

dcc-old/src/plugin-accounts/window/avatarlistframe.cpp
dcc-old/src/plugin-accounts/window/avatarlistwidget.cpp

change Type::Cartoon to Type::Dimensional
pms: BUG-295675

fix: crash when saving avatar

---

src/dde-control-center/frame/plugin/DccMenuEditorItem.qml
src/dde-control-center/frame/plugin/DccMenuItem.qml
src/plugin-accounts/qml/LoginMethod.qml
src/plugin-accounts/qml/accountsMain.qml
src/plugin-datetime/qml/LangAndFormat.qml

add theme/mode/palette to support dark mode

fix: arrow button error in dark mode

---

src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h

Deleting data too early will cause crashes
Log:
pms: BUG-295205

fix: Modify exit crash issue

---

src/plugin-bluetooth/qml/BlueToothDeviceListView.qml
src/plugin-bluetooth/qml/BluetoothCtl.qml

Adjust the bluetooth module UI
Log: Adjust the bluetooth module UI
pms: BUG-297117

fix: Adjust the bluetooth module UI

---

src/plugin-sound/operation/soundDeviceModel.cpp
src/plugin-sound/operation/soundDeviceModel.h
src/plugin-sound/operation/soundeffectsmodel.cpp
src/plugin-sound/operation/soundeffectsmodel.h
src/plugin-sound/operation/soundmodel.cpp
src/plugin-sound/operation/soundmodel.h
src/plugin-sound/operation/soundworker.cpp
src/plugin-sound/qml/DeviceListView.qml
src/plugin-sound/qml/MicrophonePage.qml
src/plugin-sound/qml/SpeakerPage.qml

Adjust sound combobox mode data
Log: Adjust sound combobox mode data
pms: BUG-291893

fix: Adjust sound combobox mode data

---

src/plugin-display/operation/dccscreen.cpp
src/plugin-display/operation/dccscreen.h
src/plugin-display/operation/displaymodule.cpp
src/plugin-display/operation/displaymodule.h
src/plugin-display/operation/private/dccscreen_p.h
src/plugin-display/operation/private/displaymodule_p.h
src/plugin-display/qml/displayMain.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

Add the function of modifying screen scale
pms: BUG-295635

feat: Add the function of modifying screen scale

---

qml/DccWindow.qml

chore: do not fullscreen on space key pressed

---

src/plugin-bluetooth/qml/BlueToothDeviceListView.qml

Adjust bluetooth more button size
Log: Adjust bluetooth more button size
pms: BUG-297109

fix: Adjust bluetooth more button size

---

src/plugin-commoninfo/qml/BootPage.qml

delete boot menu background color
Log: delete boot menu background color
pms: BUG-297215

fix: delete boot menu background color

---

src/plugin-defaultapp/operation/category.cpp
src/plugin-defaultapp/operation/categorymodel.cpp
src/plugin-defaultapp/operation/defappworker.cpp
src/plugin-defaultapp/operation/mimedbusproxy.cpp
src/plugin-defaultapp/operation/mimedbusproxy.h
src/plugin-defaultapp/qml/DetailItem.qml

Add default program functionality
pms: BUG-292937

fix: Add default program functionality

---

debian/changelog

release 6.1.6
Log: bump version to 6.1.6

chore: bump version to 6.1.6

---

src/plugin-deepinid/qml/DeepinIDAccountSecurity.qml
src/plugin-deepinid/qml/DeepinIDUserInfo.qml

feat: Temporarily hide account and security modules

---

src/plugin-update/qml/UpdateList.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

update translations
Log: update translations
pms: TASK-362119

feat: update translations

---

src/plugin-update/qml/UpdateList.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

add update module translations
Log: add update module translations
pms: TASK-362119

feat: add update module translations (#2003)

---

src/plugin-deepinid/operation/deepinidworker.cpp

fix: Determine that the system activation state is abnormal

---

src/plugin-datetime/operation/datetimemodel.cpp

Taiwan -> Taiwan China
pms: BUG-368711

feat:  override icu database

---

src/plugin-update/operation/updatework.cpp
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

System update completed Send notifications
Log: System update completed Send notifications
pms: BUG-362119

fix: System update completed Send notifications

---

debian/changelog

release 6.1.7
Log: bump version to 6.1.7

chore: bump version to 6.1.7

---

debian/changelog

release 6.1.8
Log: bump version to 6.1.8

chore: bump version to 6.1.8

---

src/plugin-mouse/qml/GestureGroup.qml

GestureGroup page not find combo,Change to itemCtl.content
Log: fix touchpad finger animation not update
pms: BUG-302551

fix: touchpad finger animation not update

---

src/plugin-mouse/operation/gesturemodel.cpp
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

update touchpad translation
Log: update touchpad translation
pms: BUG-302551

fix: update touchpad translation

---

src/plugin-bluetooth/operation/bluetoothadapter.cpp

add bluetooth device not update model
Log: add bluetooth device not update model
pms: BUG-283867

fix: add bluetooth device not update model

---

src/plugin-bluetooth/qml/BlueToothDeviceListView.qml

bluetooth moudle change button to toolbutton
Log: bluetooth moudle change button to toolbutton
pms: BUG-299285

fix: bluetooth moudle change button to toolbutton

---

src/plugin-power/qml/BatteryPage.qml
translations/dde-control-center_zh_CN.ts

as title
pms: BUG-293855 BUG-293831

fix: Incorrect setting of suspend mode to hibernate mode

---

src/plugin-bluetooth/qml/OtherDevice.qml

modify bluetooth moudel redo icon path
Log: modify bluetooth moudel redo icon path
pms: BUG-300061

fix: modify bluetooth moudel redo icon path

---

src/plugin-update/qml/UpdateControl.qml

modify update actionBtn width
Log: modify update actionBtn width
pms: BUG-299365

fix: modify update actionBtn width

---

src/dde-control-center/pluginmanager.cpp
src/dde-control-center/pluginmanager.h

Plugin status updates are processed in the main thread through signaling

fix: Plugin status updates are processed in the main thread through signaling

---

src/plugin-bluetooth/qml/BluetoothCtl.qml

modify Bluetooth moudle edit button style
Log: modify Bluetooth moudle edit button style
pms: BUG-288639
pms: BUG-296187

fix: modify Bluetooth moudle edit button style

---

src/plugin-update/qml/UpdateList.qml

delete update moudel list item implicitHeight
Log: delete update moudel list item implicitHeight
pms: BUG-301003

fix: delete update moudel list item implicitHeight

---

translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

Update display module translation
pms: TASK-368965

feat: Update display module translation

---

src/plugin-personalization/operation/personalizationinterface.cpp
src/plugin-personalization/operation/personalizationinterface.h
src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/operation/personalizationworker.h
src/plugin-personalization/operation/treelandworker.cpp
src/plugin-personalization/operation/treelandworker.h
src/plugin-personalization/qml/personalizationMain.qml

as title
pms: BUG-293055 BUG-294645

feat: Provide interfaces for setting wallpapers and themeType

---

debian/changelog

as title
Log: bump version ot 6.1.9

chore: bump version to 6.1.9

---

src/plugin-keyboard/qml/ShortcutSettingDialog.qml

Adjust ShortcutSettingDialog layout and margins
pms: BUG-303317

fix: The bottom button is not fully displayed

---

src/dde-control-center/frame/plugin/DccEditorItem.qml
src/dde-control-center/frame/plugin/DccItemBackground.qml
src/plugin-accounts/operation/accountscontroller.cpp
src/plugin-accounts/operation/accountscontroller.h
src/plugin-accounts/qml/LoginMethod.qml
src/plugin-deepinid/operation/deepinidworker.cpp

Only the administrator account can modify the password of other accounts
Bug: pms-300215

fix: standardUser can change other account passwords

---

src/plugin-accounts/operation/accountscontroller.cpp
src/plugin-accounts/operation/accountscontroller.h
src/plugin-accounts/qml/AccountSettings.qml
src/plugin-accounts/qml/AutoLoginWarningDialog.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

"Auto Login can be enabled for only one account
Bug: pms-298635

fix: multiple accounts can be enabled for automatic login

---

src/plugin-update/qml/updateMain.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

update moudle translation
Log: update moudle translation
pms: TASK-367053

feat: update moudle translation

---

src/plugin-bluetooth/qml/BlueToothDeviceListView.qml
src/plugin-bluetooth/qml/BluetoothCtl.qml

update Bluetooth list ui
Log: update Bluetooth list ui
pms: BUG-304359

fix: update Bluetooth list ui

---

translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

chore(personalization): update translate

---

src/plugin-personalization/operation/wallpaperworker.cpp

Adapt to this commit: https://github.com/linuxdeepin/dde-daemon/commit/569ed80d400c35785781ef83f6b85347eff98916
pms: BUG-294645

chore: update custom solidwallpapers path

---

qml/Crumb.qml
qml/DccWindow.qml
qml/SecondPage.qml
src/dde-control-center/frame/plugin/DccItemBackground.qml
src/dde-control-center/frame/plugin/DccMenuEditorItem.qml
src/dde-control-center/frame/plugin/DccMenuItem.qml
src/dde-control-center/frame/plugin/DccRightView.qml
src/dde-control-center/frame/plugin/DccSettingsView.qml
src/dde-control-center/frame/plugin/SearchBar.qml

Add tab key navigation interaction function
pms: BUG-303539

feat: Add tab key navigation interaction function

---

src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/operation/screensaverprovider.cpp
src/plugin-personalization/operation/utils.hpp
src/plugin-personalization/qml/ScreenSaverPage.qml
src/plugin-personalization/qml/WallpaperPage.qml

- Separate processing is the case for picture screensaver
- Delete an unnecessary time interval on auto change wallpapers
pms: TASK-36417

fix: can not click setting button when setting picture screensaver

---

src/plugin-personalization/operation/personalizationinterface.cpp

feat: Support selecting monitor when setting wallpaper

---

src/plugin-dock/operation/dccdockexport.cpp

chore(dock): update include

---

translations/dde-control-center_zh_CN.ts

chore(wallpaper): update translate

---

src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/operation/personalizationworker.h
src/plugin-personalization/operation/screensaverprovider.cpp
src/plugin-personalization/operation/wallpaperprovider.cpp
src/plugin-personalization/operation/wallpaperprovider.h

fix: unlock when not locked

---

src/plugin-commoninfo/operation/commoninfomodel.cpp
src/plugin-commoninfo/operation/commoninfomodel.h
src/plugin-commoninfo/operation/commoninfoproxy.cpp
src/plugin-commoninfo/operation/commoninfoproxy.h
src/plugin-commoninfo/operation/commoninfowork.cpp
src/plugin-commoninfo/qml/DevelopModePage.qml

fix develop mode status issue
Log: fix develop mode status issue
pms: BUG-290035

fix: fix develop mode status issue

---

src/plugin-authentication/qml/authenticationMain.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

Add character rule verification when modifying biological data names
pms: BUG-304563

fit: No character rule verification

---

src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h
src/plugin-privacy/qml/privacy.qml

feat: hide privacy on non uos

---

src/plugin-display/qml/displayMain.qml

Modify the display rules of the Identify button
pms: BUG-304007

fit: Modify the display rules of the Identify button

---

src/plugin-authentication/operation/biometricauthcontroller.cpp

Unable to obtain the name correctly

fix: first thumb name is empty

---

src/plugin-commoninfo/qml/DevelopModePage.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

fix update commonInfo translation
Log: update commonInfo translation
pms: BUG-292651

fix: update commonInfo translation

---

src/plugin-display/qml/displayMain.qml

Except for 0 errors
pms: BUG-304143

fit: No response after switching to only the secondary screen

---

src/plugin-power/qml/GeneralPage.qml

chore(power): Unhide the auto shutdown module on treeland

---

src/plugin-display/qml/displayMain.qml

Modify the display logic of the monitor title
pms: BUG-304485

fit: Modify the display logic of the monitor title

---

src/plugin-personalization/operation/wallpaperprovider.cpp
src/plugin-personalization/operation/wallpaperprovider.h

- Add cache to wallpaper thumbnail
- Terminate the search for image data upon exit
pms: BUG-305663

fix: Occasionally crash when exiting

---

src/plugin-systeminfo/operation/systeminfowork.cpp
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

update User Experience Program text
Log: update User Experience Program text
pms: BUG-292359

fix: update User Experience Program text

---

src/plugin-update/operation/updatework.cpp
src/plugin-update/qml/UpdateControl.qml

update moudle add reday state
Log: update moudle add reday state
pms: BUG-292359

fix: update moudle add reday state

---

src/plugin-personalization/qml/ScreenSaverPage.qml
src/plugin-personalization/qml/WallpaperSelectView.qml

add enableContextMenu property to control
pms: BUG-305817

fix: The preview image of the screensaver can shown menu

---

debian/changelog

bump version to 6.1.12
Log: bump version to 6.1.12

chore: bump version to 6.1.12

---

debian/changelog
debian/control

chore: add dde-control-center-dock conflict

---

src/plugin-display/operation/private/concatscreen.cpp

Fix overlapping issue in the control center display schematic adjustment
pms: BUG-305447

fix: Fix overlapping issue in the control center display schematic adjustment

---

src/plugin-personalization/qml/WindowEffectPage.qml

chore: hide compact mode

---

src/plugin-systeminfo/operation/systeminfowork.cpp
src/plugin-systeminfo/operation/systeminfowork.h

change system version info to Authorization Property data
Log: change system version info to Authorization Property data
pms: BUG-305659

fix: change system version info to Authorization Property data

---

misc/configs/org.deepin.dde.control-center.power.json
src/plugin-power/operation/powerworker.cpp
src/plugin-power/qml/BatteryPage.qml
src/plugin-power/qml/PowerPage.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

- Adjust the scale value
- Use DccTitleObject
- Add extra prompt text to slider
- Adjust the order
pms: BUG-281619
pms: BUG-281623

feat(power): Adjust and optimize the UI

---

src/plugin-commoninfo/qml/commonInfoMain.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

update developerMode translation
Log: update developerMode translation
pms: BUG-306255

fix: update developerMode translation

---

src/plugin-personalization/operation/personalizationinterface.cpp

No notification to QML, status has been changed
pms: BUG-292735

fix: appearance theme can not change by property changed

---

src/plugin-display/operation/displaymodule.cpp
src/plugin-display/operation/private/displaydbusproxy.h
src/plugin-display/operation/private/displayworker.cpp
src/plugin-display/qml/displayMain.qml

Add eye protection mode
pms: BUG-295301
pms: BUG-292043

fix: Add eye protection mode

---

src/plugin-update/operation/updatework.cpp

delete checkupdate error message
Log: delete checkupdate error message
pms: BUG-306603

fix: delete checkupdate error message

---

debian/changelog

as title
Log: bump version to 6.1.14

chore: bump version to 6.1.14

---

.reuse/dep5
src/plugin-notification/qml/notificationMain.qml
translations/dde-control-center.ts
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

Add application notification title
Log: Add application notification title
pms: BUG-300627

fix: Missing application notification title

---

src/plugin-commoninfo/qml/BootPage.qml

Change username to root
Log: Change username to root
pms: BUG-301297
pms: BUG-307181

fix: Change username to root

---

debian/changelog

release 6.1.15
Log: bump version to 6.1.15

chore: bump version to 6.1.15

---

src/plugin-bluetooth/qml/BlueToothDeviceListView.qml
src/plugin-bluetooth/qml/BluetoothCtl.qml

add Bluetooth name and icon margin
Log: add Bluetooth name and icon margin
pms: BUG-303443

fix: add Bluetooth name and icon margin

---

src/plugin-personalization/operation/model/wallpapermodel.cpp
src/plugin-personalization/operation/model/wallpapermodel.h
src/plugin-personalization/operation/personalizationworker.cpp
src/plugin-personalization/operation/personalizationworker.h
src/plugin-personalization/operation/wallpaperprovider.cpp
src/plugin-personalization/operation/wallpaperprovider.h
src/plugin-personalization/qml/WallpaperPage.qml
src/plugin-personalization/qml/WallpaperSelectView.qml

- The selected wallpaper does not allow users to delete it
- Do not export pointers managed by C++ to QML，QML's GC will parse this pointer
pms: BUG-308339

fix: occasionally crashes when switching wallpapers on multiple screens

---

debian/changelog

as title
Log: bump version to 6.1.17

chore: bump version to 6.1.17

---

src/plugin-sound/qml/DeviceListView.qml

change sound list model enabled
Log: change sound list model enabled
pms: BUG-298759

fix: change sound list model enabled

---

src/plugin-commoninfo/operation/commoninfowork.cpp

develop moudel add get debug level
Log: develop moudel add get debug level
pms: BUG-307923

fix: develop moudel add get debug level

---

src/dde-control-center/main.cpp
src/dde-control-center/pluginmanager.cpp

Terminate causes thread deadlock
pms: BUG-307781

fix: Modify Control Center Exit Deadlock Issue

---

qml/DccWindow.qml
qml/SecondPage.qml
src/dde-control-center/dccmanager.cpp
src/dde-control-center/dccmanager.h
src/dde-control-center/frame/plugin/DccEditorItem.qml
src/dde-control-center/frame/plugin/DccMenuEditorItem.qml
src/dde-control-center/frame/plugin/DccMenuItem.qml
src/plugin-systeminfo/qml/NativeInfoPage.qml

Mouse event overwritten
pms: BUG-305889

fix: Modifying cursor style issues

---

src/plugin-power/operation/powerinterface.cpp

fix: no hide 'Show the shutdown Interface' option on lid close

---

src/plugin-personalization/operation/model/wallpapermodel.h
src/plugin-personalization/qml/WallpaperSelectView.qml

When using rowCount(), qml does not know that the number of wallpapers has changed
pms: BUG-305729
pms: BUG-305999

fix: the number of wallpapers displayed has not been updated

---

.reuse/dep5
.tx/transifex.yaml
misc/DdeControlCenterPluginMacros.cmake
qml/plugins_v1.0/device/device.qml
qml/plugins_v1.0/system/system.qml
src/plugin-display/qml/displayMain.qml
src/plugin-notification/qml/notification.qml
src/plugin-personalization/qml/personalizationMain.qml
src/plugin-power/qml/power.qml
src/plugin-sound/qml/sound.qml
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_en.ts
translations/dde-control-center_en_US.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

fix: add transifex config
pms: BUG-307977

fix: add transifex config

---

qml/Crumb.qml
qml/DccWindow.qml
src/dde-control-center/navigationmodel.cpp

Modify Crumb style
pms: BUG-308419

fix: Modify Crumb style

---

src/plugin-power/qml/GeneralPage.qml
src/plugin-power/qml/PowerPlansListview.qml

- Adjust the hierarchical order of some modules
- Adjust the font size of the performance mode description
- Set the automatic shutdown settings dialog box as a modal window
- Optimize the logic of selecting items in the automatic shutdown settings dialog box
pms: BUG-304795
pms: BUG-290823
pms: BUG-298607
pms: BUG-291061
pms: BUG-290995
pms: BUG-304101
pms: BUG-304807

fix(power): ui optimization

---

src/plugin-power/qml/BatteryPage.qml
src/plugin-power/qml/GeneralPage.qml
src/plugin-power/qml/PowerPlansListview.qml
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_en.ts
translations/dde-control-center_en_US.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

as title
pms: BUG-293827
pms: BUG-298657
pms: BUG-298651
pms: BUG-298661

chore(power): update translate

---

qml/DccWindow.qml
qml/SecondPage.qml
src/dde-control-center/frame/plugin/DccItemBackground.qml
src/dde-control-center/searchmodel.cpp

Adjust the ListView UI
pms: BUG-308643

fix: Adjust the ListView UI

---

debian/changelog

chore: bump version to 6.1.18 update changelog

---

src/plugin-update/operation/updatemodel.cpp
src/plugin-update/operation/updatemodel.h
src/plugin-update/operation/updatework.cpp
src/plugin-update/operation/updatework.h

add update moudle check error tips
Log: add update moudle check error tips
pms: BUG-300997

fix: add update moudle check error tips

---

src/plugin-accounts/qml/AccountSettings.qml
src/plugin-bluetooth/operation/bluetoothadaptersmodel.cpp
src/plugin-commoninfo/qml/commonInfoMain.qml
src/plugin-personalization/qml/WallpaperPage.qml
src/plugin-personalization/qml/personalizationMain.qml
src/plugin-power/qml/BatteryPage.qml
src/plugin-power/qml/PowerPlansListview.qml
src/plugin-sound/qml/sound.qml

Many thanks in advance for reviewing this PR.

Fix minor typos

---

src/plugin-bluetooth/operation/bluetoothadaptersmodel.cpp
src/plugin-update/qml/UpdateList.qml
translations/dde-control-center_az.ts
translations/dde-control-center_bo.ts
translations/dde-control-center_ca.ts
translations/dde-control-center_en.ts
translations/dde-control-center_en_US.ts
translations/dde-control-center_es.ts
translations/dde-control-center_fi.ts
translations/dde-control-center_fr.ts
translations/dde-control-center_hu.ts
translations/dde-control-center_it.ts
translations/dde-control-center_ja.ts
translations/dde-control-center_ko.ts
translations/dde-control-center_nb_NO.ts
translations/dde-control-center_pl.ts
translations/dde-control-center_pt_BR.ts
translations/dde-control-center_ru.ts
translations/dde-control-center_uk.ts
translations/dde-control-center_zh_CN.ts
translations/dde-control-center_zh_HK.ts
translations/dde-control-center_zh_TW.ts

注：此更新导致的中文翻译文案变更会在 Transifex 平台进行填充，会在后续的 PR 合入。

fix: fix typo and update ts files

---

qml/DccWindow.qml

Modify the style of the return key
pms: BUG-308659

fix: Modify the style of the return key

---

src/dde-control-center/frame/plugin/SearchBar.qml
src/dde-control-center/searchmodel.cpp
src/dde-control-center/searchmodel.h

Modify search list keyboard interaction
pms: BUG-308757

fix: Modify search list keyboard interaction

---

src/plugin-commoninfo/qml/DevelopModePage.qml

Fix search no results
Log: Fix search no results
pms: BUG-307797

fix: Fix search no results

---

src/plugin-datetime/qml/LangsChooserDialog.qml

- Repositioned ScrollBar outside ListView area using anchor positioning
- Changed ScrollBar width from 7px to 10px for better visibility
- Modified container layout to prevent ScrollBar from affecting ListView width
- Updated rightMargin to -6 to position ScrollBar at the right edge
- Ensured ListView maintains full width alignment with SearchEdit
Log: adjust ScrollBar position and width for better visual alignment in language selection dialog
pms: BUG-330387

fix: adjust ScrollBar position and width in LangsChooserDialog

---

src/plugin-accounts/qml/AccountSettings.qml

Adjust the display effects of the user group interface.
Log: Adjust the display effects of the user group interface.

fix: Adjust the display effects of the user group interface.
