- src/dialogs/CMakeLists.txt
lib/dde-control-center/reboot-reminder-dialog -> lib/dde-control-center
> fix(update): reboot-reminder-dialog install path error

- src/frame/modules/display/displaywidget.cpp
- src/frame/modules/display/displaywidget.h
仅当使用扩展模式或者自定设置时显示为每个显示器指定缩放比例的选项
> fix: hide option for individual scaling unless extend or custom monitor configuration is in use.

- src/frame/modules/sound/soundmodel.cpp
- src/frame/modules/sound/soundmodel.h
- src/frame/modules/sound/soundworker.cpp
There is no such value in the map, which will cause the enumeration of 0 to be conflicted.
see: https://github.com/linuxdeepin/internal-discussion/issues/1160
> fix(Sound): skip not need values

- src/frame/CMakeLists.txt
Use target_link_libraries instead of CMAKE_EXE_LINKER_FLAGS. In some cmake system, CMAKE_EXE_LINKER_FLAGS could set -lcrypt before target file.
> Fix crypt can not find in some cmake system

- src/frame/modules/display/rotatedialog.cpp
https://github.com/linuxdeepin/internal-discussion/issues/1458
> fix: rotate dialog postion is wrong in 2D mode

- src/frame/modules/network/accesspointwidget.cpp
https://github.com/linuxdeepin/internal-discussion/issues/1411
> fix(network): refresh loading icon not align center

- CMakeLists.txt
- debian/rules
- src/frame/CMakeLists.txt
- src/frame/tests/display_test.h
> add display unit-test

- src/frame/modules/keyboard/shortcutwidget.cpp
fixed a toplevel window when entering the shortcut page
https://github.com/linuxdeepin/internal-discussion/issues/1937
> fix(shortcut): don't clear group widget

- src/frame/modules/network/sections/secret8021xsection.cpp
网络模块设置ca证书时改为使用uri格式，且byte array末尾添加 '\0'。修复需要ca证书的wifi链接失败问题。
> fix: format CA certificate uri for NetworkManager

- src/frame/modules/display/recognizedialog.cpp
build failures under Qt 5.15
Log: build failures under Qt 5.15
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
> fix: build failures under Qt 5.15

- src/frame/modules/systeminfo/systeminfowork.cpp
CPU Max MHz表示的是板载最大频率，并不符合逻辑，应该使用Current Speed
Log: 修复系统信息处理器信息不正确问题
Bug: https://pms.uniontech.com/bug-view-124665.html
Influence: 系统信息-关于本机-处理器
> fix: cpu 频率使用 current speed

- src/frame/window/modules/commoninfo/developermodedialog.cpp
wayland 下显示前设置过位置的（testAttribute(Qt::WA_Moved)）窗口会在
kwayland-shell 中调整位置，DAbstractDialog::showEvent 会默认设置居中
重载了showEvent 却不调用基类方法不可取。
Log:
Influence: wayland developerModeDialog posion
Bug: https://pms.uniontech.com/bug-view-123527.html
Change-Id: Iee0743912cd64883f85caaebda1f2e46cfbb3ae7
> fix: wayland 开发者模式对话框位置不居中

- src/frame/CMakeLists.txt
Fix https://github.com/linuxdeepin/developer-center/issues/3264
The compiler needs to search headers of wayland and xkbcommon in these two directories. Without these two directories in src/frame/CMakeLists.txt, the build will not be success.
> Fix: Add include directories for wayland and xkbcommon

- configs/org.deepin.dde.control-center.personalization.json
- src/frame/modules/personalization/personalizationmodel.cpp
- src/frame/modules/personalization/personalizationmodel.h
- src/frame/modules/personalization/personalizationwork.cpp
- src/frame/modules/personalization/personalizationwork.h
- src/frame/window/dconfigwatcher.cpp
- src/frame/window/dconfigwatcher.h
- src/frame/window/modules/personalization/personalizationgeneral.cpp
- src/frame/window/modules/personalization/personalizationgeneral.h
- src/frame/window/modules/personalization/personalizationmodule.cpp
- src/frame/window/utils.h
1.添加新功能：“窗口移动时启用透明特效”
2.英文宽度太长，修改过长使用...，宽度变大后显示全
3.增加搜索关联
4.添加gsettings控制
Log: 新需求-“窗口移动时启用透明特效”
Influence: 新需求
Task: https://pms.uniontech.com/task-view-154469.html
Change-Id: I6776d8fd6fe155823b38246c4f2d6b018856f41f
> feat: 个性化增加“窗口移动时启用透明特效”

- src/reset-password-dialog/resetpassworddialog.cpp
原因：重置密码隐藏后一直显示重置密码弹窗，
未考虑确认后的正常隐藏情况。
修改：添加一个判断
Log: 修复重置密码确认后一直显示重置密码弹窗问题
Bug: https://pms.uniontech.com/bug-view-151529.html
Influence: 重置密码
Change-Id: I5263258cd98f697abfac9b9215c1738ca7b78f1b
(cherry picked from commit b8097fe94841763eb4940f20ee13e1d78adbffd0)
> fix: 重置密码确认后一直显示重置密码弹窗

- src/reset-password-dialog/resetpassworddialog.cpp
关闭重置密码确认对话框最小化和关闭按钮
Log: 修复重置密码确认对话框最小化和关闭按钮问题
Bug: https://pms.uniontech.com/bug-view-151535.html
Influence: 重置密码
Change-Id: Ic641be844e097d7434b4ea44420406da4ca4007c
> fix: 重置密码确认对话框最小化和关闭按钮

- src/frame/modules/notification/model/sysitemmodel.cpp
- src/frame/modules/notification/model/sysitemmodel.h
- src/frame/modules/notification/notificationworker.cpp
- src/frame/window/modules/notification/systemnotifywidget.cpp
- src/frame/window/modules/notification/systemnotifywidget.h
- tests/dde-control-center/notification/ut_systemnotifywidget.cpp
通知-移除“在任务栏显示图标”选项,在任务栏设置中有同样的功能
Log: 移除通知中“在任务栏显示图标”的选项
Task: https://pms.uniontech.com/task-view-174011.html
Influence: 控制中心通知
Change-Id: I8bc81065c2a2e07401c2f090d1cfe876a86c05aa
> feat: 通知-移除“在任务栏显示图标”选项

- src/frame/window/modules/datetime/currencyformat.cpp
- src/frame/window/modules/datetime/currencyformat.h
- src/frame/window/modules/datetime/formatsetting.cpp
- src/frame/window/modules/datetime/numberformat.cpp
- src/frame/window/modules/datetime/numberformat.h
因为货币正数和货币负数的位置不变，在更新货币符号不会触发示例变化
因此需要把货币符号发生变化信号关联示例更新函数
Log: 同步更新示例
Influence: 数据同步
Task: https://pms.uniontech.com/task-view-154485.html
Change-Id: I11789aa4d4a16d4d27d44a060ce8c09b31ebe175
> fix: 货币符号发生变化更新示例

- src/frame/window/modules/update/updatecontrolpanel.cpp
- src/frame/window/modules/update/updatectrlwidget.cpp
- src/frame/window/modules/update/updatectrlwidget.h
- src/frame/window/modules/update/updatesettingitem.cpp
- src/frame/window/modules/update/updatesettingitem.h
当用户没有自动分区安装系、未安装ab-recovery或者是缺少某些更新文件的时候，弹窗告知用户系统无法备份，是否要继续升级。
Log: 增加无法备份时弹窗提示用户的功能
Task: https://pms.uniontech.com/task-view-158163.html
Influence: 无法备份时进行更新的场景
Change-Id: Id65daf991ff7541a9220aae5a8fabf3ebc519ae6
> feat: 无法备份时弹窗提示用户

- src/frame/CMakeLists.txt
- src/frame/window/modules/accounts/accountsdetailwidget.cpp
- src/frame/window/modules/accounts/accountsdetailwidget.h
- src/frame/window/modules/accounts/accountsmodule.cpp
- src/frame/window/modules/accounts/accountsmodule.h
- src/frame/window/modules/accounts/usergroupspage.cpp
- src/frame/window/modules/accounts/usergroupspage.h
放开用户组编辑的限制，使用单独的页面去显示用户组，供用户去修改
Log: 实现用户组编辑功能
Influence: 控制中心账户模块用户组编辑功能
Task: https://pms.uniontech.com/task-view-154497.html
Change-Id: Iaa124e2736fe3df3b6649ee5a0bfdc92d5480553
> feat(accounts): 桌面专业版账户模块支持用户组编辑

- src/frame/window/modules/personalization/personalizationgeneral.cpp
初始化的时候设置移动窗口显示透明效果的状态
Log: 初始化设置窗口移动显示透明效果状态
Task: https://pms.uniontech.com/task-view-176955.html
Influence: 个性化开启移动显示透明效果后，切换切面再切回去
Change-Id: I943f8c3a6d57fdf9b227b19357188f2d702e6627
> fix: 初始化的时候设置个性化-移动窗管显示透明效果

- src/frame/window/modules/sound/speakerpage.cpp
当初始化蓝牙模式为不显示时，在切换声音二级菜单时，会导致蓝牙模式无法显示。
Log: 修复正常环境下蓝牙模式被隐藏问题
Bug: https://pms.uniontech.com/bug-view-152793.html
Influence: 声音
Change-Id: I909ca17e0e49f7d46230b385e3334497f3fc8a24
> fix(audio): 修复正常环境下蓝牙模式被隐藏问题

- src/frame/window/modules/datetime/numberformat.cpp
- src/frame/window/modules/datetime/numberformat.h
本地翻译内容获取不到的时候，数据为"Space"，而外部数据为"空格"
导致两个值不匹配，因此按照之前的逻辑不会显示为" "
Log: 增加兼容性，处理所有非, . '的数据，均显示成" "
Influence: 时间格式显示
Task: https://pms.uniontech.com/task-view-176989.html
Change-Id: I99e69dba746835a5dff98e74c9f2c34bfd43eba0
> fix: 兼容tr("Space")与"空格"数据不匹配的情况

- src/frame/window/modules/sound/soundmodule.cpp
- src/frame/window/modules/sound/soundmodule.h
打开声音界面后切换界面时，widget已经被释放。
Log: 修复非声音界面端口变化时崩溃问题
Bug: https://pms.uniontech.com/bug-view-152815.html
Influence: 声音
Change-Id: I60dd8c326232c48a01c47aff0dcf6d5a88f64694
> fix(audio): 修复非声音界面端口变化时崩溃问题

- src/frame/window/mainwindow.cpp
- src/frame/window/modules/accounts/accountsdetailwidget.cpp
- src/frame/window/modules/accounts/usergroupspage.cpp
1.调整各级页面的显示宽度，使得各级页面衔接更美观
2.账户页面中的“账户设置”左边间隔调整为20，与相应控件的文字对齐
3.用户组页面调整控件布局，优化显示效果
Log: 解决控制中心四级页面和二级页面衔接效果不美观的问题
Bug: https://pms.uniontech.com/bug-view-153201.html
Influence: 控制中心各级页面的切换
Change-Id: I4d1f29ff401a8accfc1d34bc3221a177566faaa2
> fix: 控制中心四级页面和二级页面衔接效果不美观

- src/frame/window/modules/update/updatectrlwidget.cpp
取消按钮应该是normal而不是recommend
Log: 修复升级警告弹窗按钮样式错误的问题
Bug: https://pms.uniontech.com/bug-view-153019.html
Influence: 升级警告弹窗样式
Change-Id: I552c2920eb67b5172e84acdbb70821dd77e2105b
> fix: 升级警告弹窗按钮样式错误

- src/frame/modules/power/powermodel.cpp
- src/frame/modules/power/powermodel.h
- src/frame/modules/power/powerworker.cpp
- src/frame/window/modules/power/generalwidget.cpp
- src/frame/window/modules/power/generalwidget.h
- src/frame/window/modules/power/powermodule.cpp
在不支持性能模式的机器上隐藏对应设置项
关联相关搜索数据，已经和性能模式关联的其他设置项目
Log: 优化性能模式
Influence: 性能模式
Bug: https://pms.uniontech.com/bug-view-152811.html
Change-Id: I94b04b5048076545eee9d14bc609298271a639cf
> fix: 在不支持性能模式的机器上隐藏对应设置项

- src/frame/window/mainwindow.cpp
打开帮助手册时使用模块的name()的属性进行跳转的，但是网络账户的模块名称cloudsync，但是帮助手册是根据社区版或专业版显示Deepin
ID或是UOS ID,跳转字段不匹配，无法自动跳转
Log: 修复打开帮助手册时无法直接跳转到UOS ID模块页面
Task: https://pms.uniontech.com/task-view-180573.html
Influence: UOS ID模块自动跳转帮助手册对应页面
> fix: 修复打开帮助手册时无法直接跳转到UOS ID模块页面

- src/frame/CMakeLists.txt
Log: Use as-needed to enhance compatibility with linker
Signed-off-by: Han Gao <rabenda.cn@gmail.com>
> fix: use as-needed instead of as-need

- src/frame/window/modules/update/updatecontrolpanel.cpp
- src/frame/window/modules/update/updatewidget.cpp
更新升级模块界面焦点策略设置为Click，切换状态后会界面会失去焦点，自动转到搜素栏问题。因此切换状态时需要手动设置下焦点
Log: 修复点击下载并安装时焦点自动跳转到搜素栏问题
Bug: https://pms.uniontech.com/bug-view-152961.html
Influence: 点击下载并安装时焦点不会自动跳转到搜素栏
> fix: 修复点击下载并安装时焦点自动跳转到搜素栏问题

- src/frame/window/modules/authentication/facewidget.cpp
- src/frame/window/modules/authentication/fingerwidget.cpp
- src/frame/window/modules/authentication/iriswidget.cpp
修复修改指纹/人脸名称后焦点自动跳转到搜索栏问题
Log: 修复修改指纹/人脸名称后焦点自动跳转到搜索栏问题
Bug: https://pms.uniontech.com/bug-view-152889.html
Influence: 焦点不会自动跳转到搜索栏
> fix: 修复修改指纹/人脸名称后焦点自动跳转到搜索栏问题

- src/frame/window/modules/commoninfo/commoninfomodule.cpp
- src/frame/window/modules/commoninfo/commoninfowork.cpp
- src/frame/window/modules/commoninfo/commoninfowork.h
由于取消了埋点服务,使用com.deepin.daemon.EventLog服务获取/设置用户体验计划的开关
Log:
Task: https://pms.uniontech.com/task-view-174027.html
Influence: 用户体验计划开关
Change-Id: I3b607e8b91804dbb5673541a66ab3ab86de5f25a
> feat: 修改获取用户体验计划开关的方式

- src/frame/modules/update/updatework.cpp
- src/frame/window/modules/update/systemupdateitem.cpp
- src/frame/window/modules/update/updatesettingitem.cpp
1、显示维护版本日志，但是版本号显示大版本号。例如：1052 -> 1050
2、更新日志如果是同版本号，则按发布日期再排序，显示最新的一个。
Log:
Task: https://pms.uniontech.com/task-view-174009.html
Influence: 更新日志
Change-Id: Ic7a24db363a770fa6fb48570da2b5ce388d7ac06
> feat: 替换获取更新日志的方法

- src/frame/modules/bluetooth/device.cpp
当频繁断开和连接蓝牙时，后端会发送对应的属性改变信号，dbus信号处理顺序可能异常，会导致蓝牙连接状态显示异常
因此，如果当前蓝牙设备状态为已连接，后端传递的状态为正在连接中，此操作视为一次异常的信号，不去做更新设备的连接状态的处理
Log: 修复控制中心蓝牙连接状态异常的问题
Influence: 蓝牙设备连接
Bug: https://pms.uniontech.com/bug-view-140075.html
https://pms.uniontech.com/bug-view-148683.html
Change-Id: Iace8694ccfe2b555d9e810318471a39ba1c93bfe
> fix(bluetooth): 控制中心蓝牙连接状态异常

- src/frame/window/modules/sound/soundmodule.cpp
设备管理配置为不显示时，端口变化不影响设备管理的显示。
Log: 设备管理配置为不显示时，端口变化不影响设备管理的显示。
Bug: https://pms.uniontech.com/bug-view-154197.html
Influence: 声音-设备管理
Change-Id: I058955ada376aa2ac839279d9515d1d89c98af65
> fix(audio): 设备管理配置为不显示时，端口变化不影响设备管理的显示。

- src/reset-password-dialog/resetpassworddialog.cpp
在控制中心调用重置密码时，设置界面类型为Tool,此类型在任务栏上不会显示应用图标
Log: 修复通过union id重置密码的弹框在任务栏显示插件图标问题
Bug: https://pms.uniontech.com/bug-view-149387.html
Influence: 在控制中心重置密码时，不会在任务栏显示应用图标
> fix: 在控制中心调用重置密码时，设置界面类型为Tool

- src/frame/window/modules/accounts/modifypasswdpage.cpp
当没有同步模块的文件（deepin-deepinid-daemon）时，说明不支持通过UOS
ID的方式去重置密码
此时不应该显示忘记密码按钮
Log: 解决控制中心UOS ID页面异常显示的问题
Bug: https://pms.uniontech.com/bug-view-154695.html
Influence: 控制中心UOSID页面显示/控制中心忘记密码功能
Change-Id: I19e247228299df39fa2255602bf643bc794bfbce
> fix: 控制中心UOS ID页面异常显示

- translations/dde-control-center_az.ts
- translations/dde-control-center_bo.ts
- translations/dde-control-center_ca.ts
- translations/dde-control-center_it.ts
- translations/dde-control-center_pl.ts
- translations/dde-control-center_sq.ts
- translations/dde-control-center_ug.ts
- translations/reset-password-dialog_pl.ts
更新翻译，使得在藏语和维语下用户体验计划链接为对应语言的链接地址
Log: 解决用户体验计划网页地址错误的问题
Bug: https://pms.uniontech.com/bug-view-155603.html
Influence: 控制中心用户体验计划
Change-Id: I7ccfbe35af4e260d853c94955116b9d1398957ef
> fix: 用户体验计划网页地址错误

- include/widgets/multiselectlistview.h
- src/frame/widgets/multiselectlistview.cpp
修改为控制中心菜单对象鼠标事件只接受左键操作
Log: 修复右键或侧键点击控制中心左侧设置模块和设置项，图标点亮但右侧不切换
Bug: https://pms.uniontech.com/bug-view-155787.html
Influence: 控制中心菜单鼠标左键操作正常，其它按键不应响应
Change-Id: I4f30444f89186f37bc7ba7c3012dbe78f9cda87b
> fix: 右键或侧键点击控制中心左侧设置模块和设置项，图标点亮但右侧不切换

- src/frame/modules/personalization/personalizationwork.cpp
- src/frame/modules/personalization/personalizationwork.h
- src/frame/window/modules/personalization/personalizationgeneral.cpp
优化移动窗口开关状态，以前在关闭特效的时候，切到其他页面再切回去会导致该开关状态变化
现在优化，只有在特效开启的时候才更新该控件状态
Log: 优化移动窗口开关状态
Inlufence: 移动窗口透明特效状态变化
Bug: https://pms.uniontech.com/bug-view-155999.html
Change-Id: I2ccaa9ebea87001f392c6f00f49273e63b72aef6
> fix: 优化移动窗口开关状态

- src/frame/modules/display/monitor.cpp
刷新率判断改成与刷新率列表显示一致
Log: 规避复制模式下无相同刷新率导致显示为空
Bug: https://pms.uniontech.com/bug-view-150065.html
Influence: 显示设置
Change-Id: Ifdd0a8af7062f8d8816976bdca56094c9ccaca2a
> fix: 规避复制模式下无相同刷新率导致显示为空

- src/frame/modules/sound/soundworker.cpp
dbus 同步调用超时
Log: 修复音效服务延时下状态不同步问题
Bug: https://pms.uniontech.com/bug-view-156151.html
Influence: 声音-系统音效
Change-Id: I0cb8c0f89365284665c91a0a9fcde2408f64cf7c
> fix(audio): 修复音效服务延时下状态不同步问题

- src/frame/window/search/searchmodel.cpp
设置非中文语言时搜索数据的图标名称
Log: 修复系统语言为英文控制中心搜索结果下拉框待选项前面没有图标的问题
Bug: https://pms.uniontech.com/bug-view-156677.html
Influence: 搜索下拉框正常显示图标
> fix: 设置非中文语言时的搜索数据的图标名称

- configs/org.deepin.dde.control-center.personalization.json
- src/frame/modules/personalization/personalizationmodel.cpp
- src/frame/modules/personalization/personalizationmodel.h
- src/frame/modules/personalization/personalizationwork.cpp
- src/frame/window/dconfigwatcher.cpp
- src/frame/window/dconfigwatcher.h
因为窗管接口，在关闭特效后返回移动窗口透明的状态存在问题
在dconfig中存储一个配置来记录关闭特效时，窗口移动显示透明的状态
Log: 特效与窗口移动显示透明效果联调
Influence: 特效与窗口移动显示透明效果
Bug: https://pms.uniontech.com/bug-view-156517.html
Change-Id: I57dc2c957532b06fd5a3365a01d757f51f48e78c
> fix: 解决特效与移动窗口显示透明联调问题

- src/frame/modules/display/displayworker.cpp
下拉框还没有收回就开始设置主屏了,延时设置,确保下拉框收回在设置
Log: 修复扩展模式下切换主屏桌面闪现主屏选项框的问题
Bug: https://pms.uniontech.com/bug-view-156389.html
Influence: 设置主屏选项框
Change-Id: I17800cbdcdd7999e3c87a60bc0841ca2d518d325
> fix: 修复扩展模式下切换主屏桌面闪现主屏选项框的问题

- src/frame/window/modules/authentication/fingerdetailwidget.cpp
- src/frame/window/modules/authentication/fingerdetailwidget.h
在每次显示窗口前先判断之前的窗口是否已经存在，存在就先关闭（释放），然后再去弹新的窗口
Log: 解决通过Esc键退出添加指纹窗口后再无法弹出该窗口的问题
Bug: https://pms.uniontech.com/bug-view-156487.html
Influence: 控制中心生物认证模块指纹模块添加
Change-Id: I17259b017cbb59727027f6c976a2908a77f04364
> fix: 通过Esc键退出添加指纹窗口后再无法弹出该窗口

- src/frame/window/modules/display/multiscreenwidget.cpp
- src/frame/window/modules/display/multiscreenwidget.h
- src/frame/window/modules/display/secondaryscreendialog.cpp
已按产品备注修改为副屏窗口不随屏幕参数变化移动位置
Log: 修复副屏的显示设置窗口移动到主屏时设置副屏分辨率后原在主屏的副屏设置窗口会移动到副屏
Bug: https://pms.uniontech.com/bug-view-149435.html
Influence: 控制中心多屏设置后副屏位置不进行自动调整
Change-Id: I55416ab332b0525a001fc2c4515578a6bb4cc968
> fix: 副屏的显示设置窗口移动到主屏时设置副屏分辨率后原在主屏的副屏设置窗口会移动到副屏上

- src/frame/window/modules/update/updatemodule.cpp
- src/frame/window/modules/update/updatesettings.cpp
控制中心新增的模块应该添加翻译注释便于搜索模块检索
Log: 解决内测源模块无法搜索的问题
Bug: https://pms.uniontech.com/bug-view-151135.html
Influence: 国际化和搜索
> fix: 无法在控制中心搜索框搜索到内测源更新模块

- src/frame/window/modules/sound/devicemanagespage.cpp
设备管理界面右侧给了10的间距
Log:
Bug: https://pms.uniontech.com/bug-view-155165.html
Influence: 控制中心-声音-设备管理-输出输入设备列表与右侧间距
> fix: 修改控制中心-声音-设备管理界面右侧间距太宽问题

- src/frame/window/modules/accounts/createaccountpage.cpp
QScrollArea背景色未处理
Log:
Bug: https://pms.uniontech.com/bug-view-155153.html
Influence: 控制中心-帐户-新建帐户-背景底色
> fix: 修改账户-新建账户多了一个背景底问题

- src/frame/window/modules/update/updatesettings.cpp
检查有可能会很快完成，对话框一闪而过会给人一种操作出错的感觉
延迟一秒后再执行检查，可以让人有时间看到对话框，提升用户体验
Log: 优化内测渠道退出的用户体验
> feat: 延迟执行退出内测渠道的检查任务

- src/frame/window/modules/accounts/createaccountpage.cpp
创建账户页面“选填”英文首字母改为大写
Log: 修复控制中心创建账户页面英文显示异常的问题
Influence: 控制中心创建账户页面正常显示
Task: https://pms.uniontech.com/bug-view-145727.html
Change-Id: I359f1acdfebcc90dc5b0a99035156dca9f4a2f82
> fix(account): 控制中心创建账户页面英文显示异常

- src/frame/window/mainwindow.cpp
- src/frame/window/mainwindow.h
处理释放鼠标左键释放事件，进入对应模块
Log: 释放鼠标左键进入对应模块
Influence: 点击鼠标左键，快速移动鼠标
Task: https://pms.uniontech.com/task-view-191289.html
Change-Id: I4455d186c8502c4f65bd45d3dfd2e96c2ba27081
> fix: 点击鼠标左键，快速移动鼠标，释放的时候进入对应模块

- src/frame/modules/authentication/widgets/disclaimersdialog.cpp
- src/frame/modules/authentication/widgets/disclaimersdialog.h
- src/frame/modules/authentication/widgets/disclaimersitem.cpp
- src/frame/window/modules/authentication/addfaceinfodialog.cpp
- src/frame/window/modules/authentication/addfaceinfodialog.h
- src/frame/window/modules/authentication/addfingedialog.cpp
- src/frame/window/modules/authentication/addfingedialog.h
- src/frame/window/modules/authentication/addirisinfodialog.cpp
- src/frame/window/modules/authentication/addirisinfodialog.h
- src/frame/window/modules/authentication/fingedisclaimer.cpp
- src/frame/window/modules/authentication/fingedisclaimer.h
- src/frame/window/modules/authentication/fingerdetailwidget.cpp
- src/frame/window/modules/authentication/irisdetailwidget.cpp
- src/frame/window/modules/authentication/irisdetailwidget.h
- src/frame/window/modules/authentication/loginoptionsmodule.cpp
现象：在录入指纹免责声明界面 按下ESC按键，界面卡死；
原因：没有处理esc按键的情况；
解决方案：关联dialog的finished信号，不需要单独添加信号
Log: 修复指纹录入界面卡死的问题
Bug: https://pms.uniontech.com/bug-view-158893.html
Influence: 生物认证
Change-Id: I81451825937cb1e54e94c75abdece09307e8cdd2
> fix: 指纹录入界面卡死

- src/reset-password-dialog/main.cpp
- src/reset-password-dialog/resetpassworddialog.cpp
- src/reset-password-dialog/resetpassworddialog.h
原因：重置密码被kill后，没有与控制中心通信。
解决：捕捉kill信号，退出前与控制中心通信。
Log: 修复重置密码框被kill后无法再点击进入问题
Bug: https://pms.uniontech.com/bug-view-159321.html
Influence: 账户-重置密码
Change-Id: I9d3b11c277ab59f09555a234e6c17a1553099170
> fix(account): 重置密码框kill后无法再点击进入

- src/reset-password-dialog/main.cpp
传函数作为入参时无需取地址后再传参
Log: 修复重置密码框kill后无法再点击进入
Bug: https://pms.uniontech.com/bug-view-159321.html
Influence: 账户-重置密码
Change-Id: Ic482a1bd0ba7107785a8a1fbfffc256c61a20bdd
> fix: 修复重置密码框kill后无法再点击进入

- src/frame/modules/update/updatework.cpp
如果重新备份不需要走备份流程，继续走下载流程
Log: 提示网络错误后点击刷新按钮，触发了备份进程
Bug: https://pms.uniontech.com/bug-view-155589.html
Influence: 控制中心-更新-重新更新
> fix: 重新更新失败后错误触发备份逻辑

- src/frame/modules/power/powermodel.h
supportCpuGovernors在控制中心model的值写成了balance的值
Log: 修正控制中心获取节能模式的值
Influence: 节能模式是否显示
Bug: https://pms.uniontech.com/bug-view-160227.html
Change-Id: I5601a1eb8e5e5b2fb1426c1059378998f82726e6
> fix: 更新dconfig的supportCpuGovernors的值与实际不匹配

- src/frame/CMakeLists.txt
- src/frame/modules/authentication/widgets/disclaimersdialog.cpp
- src/frame/modules/authentication/widgets/disclaimersdialog.h
- src/frame/modules/authentication/widgets/disclaimersitem.cpp
- src/frame/modules/authentication/widgets/disclaimersitem.h
- src/frame/window/modules/authentication/addfaceinfodialog.cpp
- src/frame/window/modules/authentication/addfaceinfodialog.h
- src/frame/window/modules/authentication/addirisinfodialog.cpp
- src/frame/window/modules/authentication/addirisinfodialog.h
- src/frame/window/modules/authentication/biologicalbasedialog.cpp
- src/frame/window/modules/authentication/biologicalbasedialog.h
- src/frame/window/modules/authentication/fingedisclaimer.cpp
- src/frame/window/modules/authentication/fingedisclaimer.h
现象: 添加指纹时的用户免责声明，打开窗口菜单取消勾选总在最前面，控制中心无法任何操作
修改方案：根据UI设计师的要求，将免责声明弹窗的内容作为控件合并到弹窗中，不作为独立弹窗显示。
Log: 修复取消勾选总在最前面，控制中心无法任何操作的问题
Bug: https://pms.uniontech.com/bug-view-160221.html
Influence: 免责声明标题栏右键菜单
Change-Id: I956b1f3139888082a046cadf7be73f3d86d365c1
> fix: 取消勾选总在最前面，控制中心无法任何操作

- src/frame/window/modules/datetime/datetimemodule.cpp
给格式设置子页面设置父对象
说明:
只有在子页面构造的时候设置父对象才会生效，使用setParent没有效果
Log: 给时间日期-格式设置的3个子页面添加父对象
Influence: 格式设置快速切换
Bug: https://pms.uniontech.com/bug-view-155973.html
Change-Id: I0975fa2c979e990eb6cc9f85ddb04e170dac3237
> fix: 解决时间日期-格式设置在快速切换闪其他窗口的问题

- src/frame/window/modules/display/multiscreenwidget.cpp
- src/frame/window/modules/display/secondaryscreendialog.cpp
延时10ms后再去获取屏幕的位置信息，防止获取到的副屏的位置信息不对导致显示设置窗口显示异常
Log: 修复控制中心切换显示模式时副屏显示设置窗口位置异常的问题
Bug: https://pms.uniontech.com/bug-view-160303.html
Influence: 控制中心显示模式切换
Change-Id: I5118b805b6a3e382c04dfc139b1d14b7b68d2b15
> fix: 控制中心切换显示模式时副屏显示设置窗口位置异常

- src/frame/modules/keyboard/keylabel.cpp
按照社区测试要求，删除键盘的语言-快捷键文字用色会随着活动用色变化的逻辑
Log: 快捷键颜色不改变颜色
Influence: 快捷键数据显示
Bug: https://pms.uniontech.com/bug-view-142957.html
Change-Id: I97bae0a18e5c114fc5684d46c21e93e91ab949e8
> fix: 删除键盘语言快捷键文字随活动用色变化颜色的逻辑

- src/frame/window/modules/display/multiscreenwidget.cpp
仅HDMI屏切换到以HDMI为主屏的扩展模式时，只触发显示模式变化信号，不会触发主屏变化信号，此时只会执行一次initSecondaryScreenDialog 此时获取QApplication::screens数据更新不及时，只获取到一个屏幕，在SecondaryScreenDialog::resetDialog中， m_monitor->getQScreen()为空无法获取副屏数据,导致界面位置不正确
Log: 修复复制模式切到扩展模式(HDMI主屏)或插拔VGA线,副屏显示设置显示在主屏的问题
Bug: https://pms.uniontech.com/bug-view-160303.html
Influence: 副屏显示设置界面显示到正确的位置
> fix: wayland下监听QApplication::screenAdded信号

- src/frame/window/modules/display/displaymodule.cpp
- src/frame/window/modules/display/multiscreenwidget.cpp
由于之前为了规避窗管最大化的问题，导致子窗口被可以主窗口覆盖，现回退相关代码，并延迟刷新子窗口位置，待窗管修复后，回退此操作
Log: 修复控制中心显示模块主窗口覆盖子窗口的问题
Bug: https://pms.uniontech.com/bug-view-154395.html
Influence: 显示模块窗口
Change-Id: I0e10aac2a5eab21206c459bca439f6e630cb4001
> fix: 修复控制中心显示模块主窗口覆盖子窗口的问题

- src/frame/window/modules/keyboard/shortcutsettingwidget.cpp
dde-daemon会删除重复键值的快捷键，而close和media-close键值相同，低版本的dde-daemon未过滤close，导致被置空，升级之后，点击恢复会发出Changed信号， 此时控制中心没有对比type，导致同名快捷键被修改
Log: 修复dde-daemon低于5.14.101-1版本升级重启后,首次操作快捷键[恢复默认]按钮,关闭窗口快捷键显示异常的问题
Bug: https://pms.uniontech.com/bug-view-156565.html
Influence: 快捷键
Change-Id: Ic14d75f54a3271091e134103b452a21dcf05be33
> fix: 修复dde-daemon低于5.14.101-1版本升级重启后,首次操作快捷键[恢复默认]按钮,关闭窗口快捷键显示异常的问题

- src/frame/window/modules/accounts/usergroupspage.cpp
- src/frame/window/modules/accounts/usergroupspage.h
1. 不能点击的sudo置灰色；
2. 仅存在一个管理账户不允许移除sudo权限；
Log: 不能点击的sudo置灰，仅仅存在一个管理账户不能移除sudo权限
Influence: only one sudo account remove sudo
Bug: https://pms.uniontech.com/bug-view-162113.html
Bug: https://pms.uniontech.com/bug-view-162003.html
Change-Id: Ice29913a00bb6e78bb1eca4afe4f1edc244af6c3
> fix(Account): 不能点击的sudo置灰,只存在一个管理账户不能移除sudo权限

- src/frame/window/modules/accounts/usergroupspage.cpp
账户类型有3种：
enum UserType {
StandardUser = 0,
Administrator,
Customized
};
Administrator才是管理员账户，按之前的判断方法会把域管账户也判断成管理员
Log: 修正管理员账户判断方式
Influence: 账户判断
Bug: https://pms.uniontech.com/bug-view-162003.html
Change-Id: Ib349eeaa3fe042122990e248eaddd2cc2e705f4d
> chore: 修正判断管理员账户类型

- src/frame/modules/datetime/timezone_dialog/popup_menu.cpp
- src/frame/modules/datetime/timezone_dialog/popup_menu.h
- src/frame/modules/datetime/timezone_dialog/timezone_map.cpp
- src/frame/modules/datetime/timezone_dialog/timezone_map.h
- src/frame/modules/datetime/timezone_dialog/timezonechooser.cpp
- src/frame/modules/datetime/timezone_dialog/timezonechooser.h
- src/frame/window/modules/datetime/datetimemodule.cpp
1.如果选择的时区与当前时区相同，则不允许点击确定；
2.如果选中的时区出现了多个时区label，也不允许点击确定，需要选择一个后才能点击确定；
3.时区地图上没有label页面也不允许点击确定；
Log: 优化添加时区和设置时区的交互逻辑；
Influence: 时区添加和时区设置
Bug: https://pms.uniontech.com/bug-view-161133.html
Change-Id: I44f361614ca189d7f9393e960a9f6b87abe3c93e
> fix: 优化添加时区和设置时区交互逻辑

- src/frame/window/mainwindow.cpp
- src/frame/window/mainwindow.h
This reverts commit 384eaba93e251e855bd52e9d7f23692a8b10103c.
Log: 回退上述逻辑，使用其他方法
Influence: 点击鼠标左键不放，快速移动鼠标
Bug: https://pms.uniontech.com/bug-view-162933.html
> Revert "fix: 点击鼠标左键，快速移动鼠标，释放的时候进入对应模块"

- src/frame/window/modules/accounts/accountsdetailwidget.cpp
设置头像之后，焦点被返回键捕获，窗口需要设置下焦点
Log: 修复设置头像成功后，控制中心标题栏返回键出现Focus状态的问题
Influence: 控制中心设置头像
Bug: https://pms.uniontech.com/bug-view-162947.html
Change-Id: I00f1cf44c3b4f9ff83dd261ee9d710761f94ea1a
> fix: 修复设置头像成功后，控制中心标题栏返回键出现Focus状态的问题

- src/frame/modules/update/updatework.cpp
- src/frame/window/modules/update/updatesettingitem.cpp
由于网络问题重试默认进入下载并安装流程，并且lastore未提供分类下载的接口，因此网络问题重试需要进入检查更新流程，触发自动下载。另外网络问题导致中断，需要重新检查更新防止仓库更新。
Log: 修复重试时进入下载并安装流程
Bug: https://pms.uniontech.com/bug-view-161177.html
Influence: 更新重试
Change-Id: Ia17bab5a303a8c6bab6b92022ebc23dea20da37f
> fix: 修复重试时进入下载并安装流程

- src/frame/window/modules/display/displaymodule.cpp
由于主屏为空，导致控制中心崩溃
Log: 增加判空处理
Bug: https://pms.uniontech.com/bug-view-159801.html
Influence: 分辨率切换
Change-Id: I7956f507b24a3f63912acd3f6df9eeb3dfd07438
> fix: 增加判空处理

- include/widgets/multiselectlistview.h
- src/frame/widgets/multiselectlistview.cpp
- src/frame/window/mainwindow.cpp
- src/frame/window/mainwindow.h
使用选中信号和鼠标左键释放信号一起确定切换页面的时机
Log: 点击鼠标左键，快速移动鼠标，释放的时候进入对应页面
Influence: 点击鼠标左键，快速移动鼠标
Bug: https://pms.uniontech.com/bug-view-162933.html
Change-Id: I11949cbbfe5434e0a65983973fc9fae561b37b53
> fix: 点击鼠标左键，快速移动鼠标，释放的时候进入对应页面

- src/frame/window/mainwindow.cpp
当改变任务栏大小后，也会发出availableGeometryChanged信号，导致控制中心位置更新
Log: 修复在控制中心-个性化调节任务栏大小，会改变控制中心窗口位置的问题
Bug: https://pms.uniontech.com/bug-view-163043.html
Influence: 控制中心-个性化调节任务栏大小
Change-Id: Iddb2de585eb5b1df392436905b0c6f2ed3aafb70
> fix: 修复在控制中心-个性化调节任务栏大小，会改变控制中心窗口位置的问题

- src/frame/window/modules/display/displaymodule.cpp
由于主屏为空，导致控制中心崩溃，2317dd4c修改导致无法弹窗保存，本提交修改无主屏时，填充模式默认设置为""
Log: 无主屏时，填充模式默认设置为""
Bug: https://pms.uniontech.com/bug-view-159801.html
Influence: 分辨率切换
Change-Id: I04aaf371b595fafbca5a5dbba36a9d60e9668403
> fix: 无主屏时，填充模式默认设置为""

- src/frame/window/modules/commoninfo/developermodewidget.cpp
直接调用startdde的reboot，会导致有关机阻塞时注销；需要调用前端重启，会显示关机阻塞
Log: 修复进入开发者模式后重启时关机阻塞不显示导致注销问题
Bug: https://pms.uniontech.com/bug-view-147587.html
Influence: 进入开发者模式
Change-Id: I6a6f56035a23e94b4c6ba8e1b6d81623602da23c
> fix: 修复进入开发者模式后重启时关机阻塞不显示导致注销问题

- src/frame/window/modules/bluetooth/detailpage.cpp
当用户没有修改蓝牙名称时，显示之前配对的蓝牙设备名称
Log: 修复控制中心蓝牙设备名称显示错误的问题
Bug: https://pms.uniontech.com/bug-view-164595.html
Influence: 控制中心蓝牙设备名称显示
Change-Id: Idd0a4343dfe855f8f04f00c0e5bb68ad5fb49083
> fix: 控制中心蓝牙设备名称显示错误

- src/frame/window/modules/datetime/datesettings.cpp
自定义时间保存按钮位置到下边框间距过大，按设计调整成20像素
Log: 修复自定义时间保存按钮位置问题
Bug: https://pms.uniontech.com/bug-view-164699.html
Influence: 调整自定义时间保存按钮位置到下边框间距为20
> fix: 调整自定义时间保存按钮位置

- src/frame/modules/personalization/personalizationwork.cpp
- src/frame/modules/personalization/personalizationwork.h
1.窗管接口同步调用方式出现问题，不管是否设置成功都返回false，初始化调用isEffectLoaded方法，改用异步方式调用
2.wayland下默认支持特效，不能调用WMSwitcher接口判断
Log: 异步调用窗管接口
Influence: 打开控制中心第一次进入个性化
Bug: https://pms.uniontech.com/bug-view-164453.html
Change-Id: I40381fc6e2fc5afb6c70f7f7a4a47f9d821098e4
> fix: 初始化获取当前是否开启窗口移动时启用透明特效改用异步, 且区分wayland和X11

- src/frame/modules/personalization/personalizationwork.cpp
- src/frame/modules/personalization/personalizationwork.h
- src/frame/window/modules/personalization/personalizationgeneral.cpp
- src/frame/window/modules/personalization/personalizationgeneral.h
- src/frame/window/modules/personalization/personalizationmodule.cpp
虚拟机中以上两种特效不支持，将不支持的功能模块隐藏
Log: 修复【虚拟机】【个性化】点击“移动窗口时启用透明特性”开关无响应，最小化效果为“魔灯”时无魔灯效果的问题
Bug: https://pms.uniontech.com/bug-view-163031.html
Influence: 控制中心特效
Change-Id: I52c8e5f7e9b00f2f0f9d778b9d3290682b5b7cea
> fix: 修复【虚拟机】【个性化】点击“移动窗口时启用透明特性”开关无响应，最小化效果为“魔灯”时无魔灯效果的问题

- src/frame/window/modules/sound/soundeffectspage.cpp
三级列表已经设置间隔为10，列表间隔设置为4即可（整体为14px）
Log: 修复控制中心系统音效列表标题间距显示异常的问题
Bug: https://pms.uniontech.com/bug-view-164789.html
Influence: 控制中心声音模块系统音效正常显示
Change-Id: I0fc754bc5cdc525a37d7cf1c75e008ca29551d37
> fix: 控制中心系统音效列表标题间距显示异常

- src/frame/window/modules/bluetooth/bluetoothmodule.cpp
根据蓝牙“我的设备”的显示状态来确定其是否可以在搜索列表中搜到
Log: 修复控制中心控制中心搜索列表显示错误的问题
Bug: https://pms.uniontech.com/bug-view-164941.html
Influence: 控制中心搜索列表正常显示
Change-Id: Iea8e2e0a54d9c2e8d547bfec57b34287ece38703
> fix: 控制中心搜索列表显示错误

- src/frame/modules/datetime/timezoneitem.cpp
修改系统时区删除按钮图标大小，和系统语言列表中删除按钮大小保持一致
Log: 修复时区列表删除按钮大小不一致问题
Bug: https://pms.uniontech.com/bug-view-164805.html
Influence: 系统时区删除按钮图标大小和系统语言列表中删除按钮大小保持一致
> fix: 修改系统时区删除按钮图标大小

- src/frame/window/modules/datetime/datewidget.cpp
按UI设计要求，将日期时间设置中的年月日字体调整为T8和60%灰度
Log: 按UI设计要求，将日期时间设置中的年月日字体调整为T8和60%灰度
Bug: https://pms.uniontech.com/bug-view-164777.html
Influence: 按UI设计要求，将日期时间设置中的年月日字体调整为T8和60%灰度
> fix: 将日期时间设置中的年月日字体调整为T8和60%灰度

- src/frame/window/mainwindow.cpp
- src/frame/window/mainwindow.h
使用了空指针
Log: 修复仅HDMI切换仅edp-1时控制中心退出的问题
Bug: https://pms.uniontech.com/bug-view-165867.html
Influence: 切换显示模式
Change-Id: I09767be5e54c1b7de8a69d5020b7973db37cdcee
> fix: 仅HDMI切换仅edp-1时控制中心退出

- src/frame/modules/personalization/personalizationwork.cpp
- src/frame/modules/personalization/personalizationwork.h
- src/frame/window/modules/personalization/personalizationgeneral.cpp
- src/frame/window/modules/personalization/personalizationgeneral.h
- src/frame/window/modules/personalization/personalizationmodule.cpp
该修改存在较大问题,对于初始化以及connect信号槽连接时序都不对
因此导致第一次进去无法正常设置状态到界面
Log: 代码回退
Influence: 特效相关设置初始值失效
Bug: https://pms.uniontech.com/bug-view-166339.html This reverts commit 1199d94566c473ed81f9f7001ffc8c7b15f5b088.
> Revert "fix: 修复【虚拟机】【个性化】点击“移动窗口时启用透明特性”开关无响应，最小化效果为“魔灯”时无魔灯效果的问题"

- src/frame/modules/accounts/usermodel.cpp
- src/frame/modules/accounts/usermodel.h
- src/frame/window/modules/accounts/accountsdetailwidget.cpp
- src/frame/window/modules/accounts/accountsmodule.cpp
所有域管账户都不显示用户组，而不是只针对当前登录的用户
Log: 修复控制中心域管账户用户组显示错误的问题
Bug: https://pms.uniontech.com/bug-view-163513.html
Influence: 控制中心用户组显示
Change-Id: Ib0497b267218c6786509774e9d0d53cd07a3456c
> fix: 控制中心域管账户用户组显示错误

- src/frame/window/modules/accounts/accountsdetailwidget.cpp
- src/frame/window/modules/accounts/accountsmodule.cpp
域账户的相关信息（密码有效期，是否为管理员，重置密码，修改全名）等操作都是由域管服务器统一管理的
通过控制中心去修改相关信息，会造成本地账户的信息与域管信息不同步，会造成很多问题，故因此这些配置选项
Log: 修复控制中心域账户界面显示异常的问题
Bug: https://pms.uniontech.com/bug-view-166345.html
Influence: 控制中心账户页面正常显示
Change-Id: Ia40931a804bdce4a6b77efdc1f12a9d01e9c7b28
> fix: 控制中心域账户界面显示异常

- src/frame/window/search/searchmodel.cpp
- src/frame/window/search/searchmodel.h
- src/frame/window/search/searchwidget.cpp
- src/frame/window/search/searchwidget.h
1.搜索数据长度>315像素的时候，后面数据显示成...
2.鼠标点击或者键盘选中enter后，将...数据再恢复成真实数据，设置到搜索框并跳转
Log: 优化搜索数据过长显示问题
Influence: 搜索
Bug: https://pms.uniontech.com/bug-view-164951.html
Change-Id: I255cbeaa8a5d3aa34920b0c4f286692623343390
> fix: 解决搜索数据过长显示不下的问题

- .gitignore
- src/frame/modules/accounts/removeuserdialog.cpp
按设计要求，删除操作的危险行为，不管活动色是什么，删除按钮文字改为用红色的
Log: 修复控制中心删除账户时的提示框删除字体颜色的问题
Task: https://pms.uniontech.com/task-view-208027.html
Influence: 账户删除按钮字体颜色
Change-Id: I58b71e684270ef90046818caa02f0235c71f44e7
> fix: 修复控制中心删除账户时的提示框删除字体颜色的问题

- src/frame/window/protocolfile.cpp
该问题可能为打包环境的问题（打包前后通过dtk获取的系统类型不一样）
针对上述问题，如果新版欧拉的协议文件和老的版本协议文件都找不到，则用服务器版本的版本协议文件
Log: 修复欧拉(1050e)控制中心最终用户许可协议显示异常的问题
Task: https://pms.uniontech.com/task-view-207089.html
Influence: 控制中心系统信息正常显示
Change-Id: I2bc747342ec1a879d3ddaad10bc06ae3fc461e25
> fix: 欧拉(1050e)控制中心最终用户许可协议显示异常

- src/frame/window/modules/bluetooth/detailpage.cpp
当修改了蓝牙配对的设备名称时，更新下输入框的提示
Log: 修复控制中心蓝牙名称输入框提示错误的问题
Bug: https://pms.uniontech.com/bug-view-166613.html
Influence: 控制中心蓝牙名称正常显示
Change-Id: Id408319262cc73ee93cd555caae4a3ce11b4167a
> fix: 控制中心蓝牙名称输入框提示错误

- src/frame/window/mainwindow.cpp
原因：其他发行版不支持更新模块，没有初始化更新模块，点击之后调用了对应的方法，导致崩溃
解决方案：其他发行版不支持更新，模块不应该显示出来
Log: 修复社区版-其他发行版【debian】点击更新模块，控制中心闪退的问题
Bug: https://pms.uniontech.com/bug-view-160653.html
Influence: 更新模块显示
Change-Id: I96fe1effd2bb7cd083b5bd5cf42273d93bf18399
> fix: 修复社区版-其他发行版【debian】点击更新模块，控制中心闪退的问题

- src/frame/modules/keyboard/customedit.cpp
当用户编辑自定义快捷键名称时，如果名称与已有快捷键名称重复，置灰保存按钮
Log: 修复控制中心自定义快捷键名称显示异常的问题
Bug: https://pms.uniontech.com/bug-view-110160.html
Influence: 控制中心快捷键显示
Change-Id: I0275f65e5fab41e8c808f2345caf8f0a4829466d
> fix: 控制中心自定义快捷键名称显示异常

- src/frame/window/modules/accounts/accountsdetailwidget.cpp
域管用户不绑定securityQuestions配置选项，即使用户修改了配置，也不显示该安全问题页面
Log: 修复账户页面安全问题显示异常的问题
Bug: https://pms.uniontech.com/bug-view-166345.html
Influence: 控制中心账户页面正常显示
Change-Id: Id7234a4fe2f5d510eb9b7d21f029045674946848
> fix: 域管用户账户页面安全问题显示异常

- src/frame/window/modules/accounts/accountsdetailwidget.cpp
- src/frame/window/modules/accounts/accountsdetailwidget.h
- src/frame/window/modules/accounts/usergroupspage.cpp
1.开启等保三级后，只有系统管理员(sysadm)有权限修改用户组页面；
2.针对原来的管理员账户，需要隐藏sudo和root组选项，与账户页面二级页面账户类型和三级页面账户设置/管理员保持一致
Log: 实现等保三级账户页面显示
Task: https://pms.uniontech.com/task-view-212851.html
Influence: 控制中心账户页面正常显示
Change-Id: I1eb7987c32397bb4e7bb6a7c7c2dd69cffc46666
> feat: 实现等保三级账户页面显示

- src/frame/window/modules/keyboard/keyboardlayoutwidget.cpp
按UI设计要求调整控制中心键盘语言-键盘布局左右边距分别为10像素
Log: 修复键盘搜索列表左右边距问题
Bug: https://pms.uniontech.com/bug-view-171879.html
Influence: 控制中心键盘语言-键盘布局左右边距分别为10像素
> fix: 调整控制中心键盘语言-键盘布局左右边距

- src/frame/modules/datetime/datetimemodel.cpp
- src/frame/modules/datetime/datetimemodel.h
- src/frame/modules/datetime/datetimework.cpp
- src/frame/modules/datetime/datetimework.h
- src/frame/modules/datetime/timezone_dialog/timezone_map.cpp
- src/frame/modules/datetime/timezone_dialog/timezone_map.h
- src/frame/modules/datetime/timezone_dialog/timezonechooser.cpp
按UI设计要求，将时区地图中选择的坐标标识圆点颜色替换成系统活动色
Log: 修复修改系统时区主题适配问题
Bug: https://pms.uniontech.com/bug-view-171885.html
Influence: 图中选择的坐标标识圆点颜色替换成系统活动色
> fix: 将时区地图中选择的坐标标识圆点颜色替换成系统活动色

- src/frame/window/modules/commoninfo/commoninfomodule.cpp
页面顺序初始化错误，导致无法正确跳转
Log: 修复控制中心，搜索进入开发者模式异常问题
Bug: https://pms.uniontech.com/bug-view-169845.html
Influence: 正常搜索并跳转进入开发者模式页面
> fix: 修复搜索"进入开发者模式"并跳转时打开错误页面的问题

- src/frame/window/modules/bluetooth/bluetoothwidget.cpp
在每次去更新页面时，重新设置一下蓝牙页面的焦点
Log: 修复控制中心取消蓝牙配对焦点跳转异常的问题
Bug: https://pms.uniontech.com/bug-view-172115.html
Influence: 取消蓝牙配对时焦点不会自动跳转到搜索栏
Change-Id: Icb7cfa8c848a40580369d2ad63873e2120d02773
> fix: 控制中心取消蓝牙配对焦点跳转异常

- src/frame/modules/display/monitor.cpp
屏幕获取错误
Log: 修复KLUA切换扩展模式，副屏显示窗口显示在主屏的问题
Bug: https://pms.uniontech.com/bug-view-170621.html Influence: 控制中心显示模块
Change-Id: If41a7bd299821e024f5a1640f30a0bb298f79856 (cherry picked from commit 1133e5f18f8d1acc61d4adb76736f1e2d5252424)
> fix: 修复KLUA切换扩展模式，副屏显示窗口显示在主屏的问题

- src/frame/CMakeLists.txt
- src/frame/window/modules/display/brightnesswidget.cpp
- src/frame/window/modules/display/brightnesswidget.h
- src/frame/window/modules/display/colortempwidget.cpp
- src/frame/window/modules/display/colortempwidget.h
- src/frame/window/modules/display/displaymodule.cpp
- src/frame/window/modules/display/multiscreenwidget.cpp
- src/frame/window/modules/display/multiscreenwidget.h
优化设置项顺序以及提供友好提示
Log: 显示-多屏拓展模式设置顺序调整
Task: https://pms.uniontech.com/task-view-212931.html
Influence: 调整主屏设置窗口的设置项顺序，并添加新文案
> fix: 显示-多屏拓展模式设置顺序调整

- src/frame/modules/power/powermodel.h
- src/frame/window/modules/power/usebatterywidget.cpp
- src/frame/window/modules/power/useelectricwidget.cpp
电源按钮新增选项
Log: 电源-修改按电源按钮时-“无任何操作”的响应事件并新增选项
Task: https://pms.uniontech.com/task-view-212911.html
Influence: 电源选项
> feat: 电源-修改按电源按钮时-“无任何操作”的响应事件并新增选项

- src/frame/modules/datetime/timezone_dialog/timezone_map.cpp
- src/frame/modules/datetime/timezone_dialog/timezonechooser.cpp
时区选择界面主题和地图颜色相反,浅色主题时，选择界面为白色透明，地图区域为黑色透明；而深色主题时，选择界面为黑色透明，地图区域为白色透明
Log: 修复系统时区主题适配问题
Bug: https://pms.uniontech.com/bug-view-171885.html
Influence: 浅色主题时，选择界面为白色透明，地图区域为黑色透明；而深色主题时，选择界面为黑色透明，地图区域为白色透明
> fix: 时区选择界面主题和地图颜色相反

- src/frame/modules/datetime/timezone_dialog/timezone_map.cpp
- src/frame/modules/datetime/timezone_dialog/timezone_map.h
时区选择弹窗界面根据控制中心深浅主题变化而变化,原方案是替换颜色处理，但是在图形边缘有像素点替换不干净，形成了边框的效果，修改成重新使用活动色绘 制原点方式处理。
Log: 时区选择弹窗界面根据控制中心深浅主题变化而变化
Bug: https://pms.uniontech.com/bug-view-171885.html
Influence: 时区选择弹窗界面根据控制中心深浅主题变化而变化
> fix: 时区选择弹窗界面根据控制中心深浅主题变化而变化

- src/frame/modules/sound/soundworker.cpp
- src/frame/modules/sound/soundworker.h
sources 属性和 default_source 属性变换信号存在时序问题，
可能 meter 建立的指向的是先前的 default_source，后面才收到
default_source 变换信号。
Log: 修复概率无反馈音量问题
Bug: https://pms.uniontech.com/bug-view-174101.html
Influence: 声音-输入-反馈
> fix(audio): 修复概率无反馈音量问题

- src/frame/window/modules/accounts/usergroupspage.cpp
当更新用户组时，不更新该选项的使能状态，只更新其选中状态
Log: 修复控制中心sudo用户组显示存在问题的问题
Bug: https://pms.uniontech.com/bug-view-176063.html
Influence: 控制中心用户组正常显示
Change-Id: If7fd136f308e1f9345abffdbf6aa18d1d5194ba3
> fix: 控制中心sudo用户组显示存在问题

- src/frame/window/modules/keyboard/systemlanguagewidget.cpp
- src/frame/window/modules/keyboard/systemlanguagewidget.h
根据当前状态设置添加系统语言按钮焦点策略
Log: 修复切换系统语言，系统语言+按钮展示Focus状态问题
Bug: https://pms.uniontech.com/bug-view-175149.html
Influence: 切换系统语言，系统语言+按钮不显示Focus状态
> fix: 根据当前状态设置添加系统语言按钮焦点策略

- src/frame/window/modules/display/refreshratewidget.cpp
可显示刷新率为空时,置灰相关UI
Log: 规避复制模式无相同刷新率显示
Bug: https://pms.uniontech.com/bug-view-124357.html
Influence: 刷新率显示
Change-Id: I6f265843c067c0ac6429191151595c40c071209c
> fix: 规避复制模式无相同刷新率显示

- src/frame/modules/keyboard/shortcutitem.cpp
禁用快捷键名称显示控件的html标签解析功能
Log: 修复添加快捷键-名称未屏蔽富文本转义问题
Bug: https://pms.uniontech.com/bug-view-175179.html
Influence: 禁用快捷键名称显示控件的html标签解析功能
> fix(shortcut): 禁用快捷键名称显示控件的html标签解析功能

- src/frame/modules/keyboard/customitem.cpp
调整自定义快捷键显示项的边距，加高快捷键输入框高度
Log: 修复自定义快捷键创建页面中的“快捷键”输入框高度显示太小问题
Bug: https://pms.uniontech.com/bug-view-175607.html
Influence: “快捷键”输入框高度加高
> fix: 调整自定义快捷键显示项的边距，加高快捷键输入框高度

- src/frame/modules/sound/soundmodel.cpp
- src/frame/modules/sound/soundmodel.h
sw架构不支持麦克风功能，在方法内进行判断，避免在每个调用的地方都进行判断。
Log:
Task: https://pms.uniontech.com/task-view-226391.html
Influence: sw打包 & sw架构声音模块
Change-Id: I7b1c301ad2809cefc3793fdd0124df1d60415ac8
> fix: sw架构打包失败

- src/frame/modules/datetime/timezone_dialog/timezone_map.cpp
- src/frame/modules/datetime/timezone_dialog/timezonechooser.cpp
- src/frame/modules/datetime/timezone_dialog/timezonechooser.h
1、使用系统统一的窗口关闭按钮
2、搜索框请使用透明度
3、定位tips背景的小尖角与矩形连接处颜色一致，没有黑线
4、取消确认按钮距离底部20px
Log: 修复添加时区页面样式问题
Bug: https://pms.uniontech.com/bug-view-171901.html
Influence: 修复添加时区页面样式问题
> fix: 修复添加时区页面样式问题

- configs/org.deepin.dde.control-center.json
- src/frame/window/mainwindow.cpp
根据配置，选择是否加载控制中心同步模块，默认为true（专业版代码判断，不加载，军用版走专门配置）
Log: 增加配置是否加载同步模块
Task: https://pms.uniontech.com/task-view-229173.html
Influence: 同步模块
Change-Id: If00c4447d255982854126c4c748d54f4436d2c43
> feat: 增加配置是否加载同步模块

- src/frame/window/modules/keyboard/customcontent.cpp
经产品确认，增加红色背景
Log: 修复自定义快捷键名称重复无提示的问题
Bug: https://pms.uniontech.com/bug-view-174803.html
Influence: 自定义快捷键
Change-Id: If32c3f776132c394d739bd8ab5942a31eaa9ef40
> fix: 修复自定义快捷键名称重复无提示的问题

- src/frame/modules/keyboard/customedit.cpp
- src/frame/modules/keyboard/customedit.h
自定义快捷键修改名称(名称不冲突)、命令或者键值都可以保存
Log: 修复自定义快捷键编辑页面，修改命令和快捷键后无法保存的问题
Bug: https://pms.uniontech.com/bug-view-175615.html
Influence: 自定义快捷键
Change-Id: Idd1b70b25fe5b4b5982bc4d939a127536f328fe9
> fix: 修复自定义快捷键编辑页面，修改命令和快捷键后无法保存的问题

- src/frame/window/modules/authentication/faceinfodialog.cpp
- src/frame/window/modules/authentication/faceinfodialog.h
按ESC后,控制中心未停止录入
Log: 人脸录入优化
Bug: https://pms.uniontech.com/bug-view-177309.html
Influence: 人脸录入
Change-Id: Iaba70a1fccaf413e8e1cc344883e85f3049899c1
> fix: 修复录入人脸通过鉴权后按Esc，人脸依旧会录入问题

- src/frame/window/modules/accounts/accountsdetailwidget.cpp
增加复制成功提示，关闭后开启起一个新的对话框，避免操作过快提示语不会消失
Log:
Bug: https://pms.uniontech.com/bug-view-175965.html
Influence: 对话框关闭再开启，重新new一个对话框对象
Change-Id: I4d2f66056764fd04a8a9c47ec548a174bf69c6c5
> fix: 显示密钥对话框关闭后，在开启起一个新的对话框

- src/frame/modules/accounts/accountsworker.cpp
- src/frame/modules/accounts/accountsworker.h
- src/frame/window/modules/accounts/accountsmodule.cpp
- src/frame/window/modules/accounts/modifypasswdpage.cpp
开启安全密钥，忘记密码也需要开启重置密码框
说明：在关闭的时候能打开非控制中心操作，这个问题在另一个bug处理
Log:
Influence: 开启安全密钥，点击忘记密码
Bug: https://pms.uniontech.com/bug-view-177051.html
Change-Id: I3bf8111240b2c5be1bf1bb563ec43a79c785a4a6
> fix: 开启安全密钥，点击忘记密码也能打开重置密码框

- src/frame/window/modules/accounts/modifypasswdpage.cpp
- src/frame/window/modules/accounts/modifypasswdpage.h
前一次结果错误时，设置m_isBindCheckError为True,再次检查时无法重置m_isBindCheckError状态，此时UBID为 空时无法提示用户绑定UOS ID
Log: 修复网络连接正常时无法提示用户绑定UOS ID问题
Bug: https://pms.uniontech.com/bug-view-154195.html
Influence: 网络恢复正常时可以正常提示用户绑定UOS ID
> fix: 检查结果为空时需要提示用户绑定UOS ID

- src/reset-password-dialog/resetpassworddialog.cpp
- src/reset-password-dialog/resetpassworddialog.h
- src/reset-password-dialog/resetpasswordworker.cpp
- src/reset-password-dialog/resetpasswordworker.h
开启安全密钥，重置密码页面显示安全密钥修改密码；
关闭安全密钥，重置密码页面不显示安全密钥修改密码；
Log:
Influence: 开启安全密钥，点击忘记密码
Bug: https://pms.uniontech.com/bug-view-177051.html
Change-Id: I87f90cb390dd91189ebb218e1390f409a0daa0b3
> fix: 开启/关闭安全密钥开关，决定是否在reset-password-dialog是否显示安全密钥

- src/frame/modules/authentication/charamangerworker.cpp
当某个生物识别设备type未0时（即拔出设备后），不应屏蔽所有生物识别模块
Log: 修复当人脸识别设备正常时，接入虹膜识别设备后，控制中心生物识别模块消失
Influence: 控制中心生物识别模块
Bug: https://pms.uniontech.com/task-view-231313.html
Change-Id: I3072787ec0291854e0add7e8f2cbacfbaa6b33ee
> fix: 修复当人脸识别设备正常时，接入虹膜识别设备后，控制中心生物识别模块消失

- src/frame/modules/authentication/charamangerworker.cpp
当某个生物识别设备type未0时，不应屏蔽所有生物识别模块
Log: 修复当人脸识别设备正常时，接入虹膜识别设备后，控制中心生物识别模块消失
Influence: 控制中心生物识别模块
Bug: https://pms.uniontech.com/task-view-231313.html Change-Id: I3072787ec0291854e0add7e8f2cbacfbaa6b33ee (cherry picked from commit 8d19858e64844e3a5bc85f0051c11068c5bd0686)
> fix: 修复当人脸识别设备正常时，接入虹膜识别设备后，控制中心生物识别模块消失 (#1171)

- src/develop-tool/CMakeLists.txt
解决控制中心编译找不到DtkCore
Log: 控制中心github编译找不到DtkCore
Influence: github编译
Bug: https://pms.uniontech.com/bug-view-178821.html
Change-Id: Id347a5569b38b6bdbd1892c22c14b92c50c4b885
> chore: dde-control-center build failed

- src/frame/window/modules/mouse/mousemodule.cpp
搜索加入触控板选项
Log: 修复控制中心搜索“触控板”无触控板开关选项的问题
Bug: https://pms.uniontech.com/bug-view-178947.html
Influence: 触控板搜索
Change-Id: Ib19a53e7df94724d011caf05c4b04aa444778dcf
> fix: 修复控制中心搜索“触控板”无触控板开关选项的问题

- src/frame/window/mainwindow.cpp
按UI设计的要求，一级侧边导航栏不需要保留上下边距
Log: 修复侧边栏滚动区域过小问题
Bug: https://pms.uniontech.com/bug-view-179559.html
Influence: 一级侧边导航栏不需要保留上下边距
> fix: 一级侧边导航栏不需要保留上下边距

- src/frame/modules/authentication/fingermodel.h
- src/frame/modules/authentication/fingerworker.cpp
- src/frame/window/modules/authentication/addfingedialog.cpp
- src/frame/window/modules/authentication/addfingedialog.h
- src/frame/window/modules/authentication/fingerdetailwidget.cpp
未处理claim失败导致控制中心卡死
Log: 指纹录入失败处理
Bug: https://pms.uniontech.com/bug-view-179805.html
Influence: 指纹录入
Change-Id: I5503d8996f98eaa2380199f0f8982806bd939fd4
> fix: 修复禁用USB指纹仪后再次添加指纹，控制中心直接挂死问题

- src/frame/modules/personalization/personalizationmodel.cpp
- src/frame/modules/personalization/personalizationmodel.h
- src/frame/modules/personalization/personalizationwork.cpp
- src/frame/modules/personalization/personalizationwork.h
- src/frame/window/modules/personalization/personalizationgeneral.cpp
- src/frame/window/modules/personalization/personalizationgeneral.h
- src/frame/window/modules/personalization/personalizationmodule.cpp
1、个性化增加滚动条设置.
2、重新调整布局，避免关闭特效后滚动条设置项和窗口特效开关之间的间隔过大
Log: 个性化增加滚动条设置
Task: https://pms.uniontech.com/task-view-212919.html
Influence: 个性化增加滚动条设置
> feat: 个性化增加滚动条设置

- configs/org.deepin.dde.control-center.personalization.json
- src/frame/window/modules/personalization/personalizationgeneral.cpp
- src/frame/window/modules/personalization/personalizationmodule.cpp
1、增加滚动条显示策略功能是否可用的dconfig配置
2、处理滚动条显示策略的搜索数据
Log: 个性化增加滚动条设置
Task: https://pms.uniontech.com/task-view-212919.html
Influence: 个性化增加滚动条设置
> feat: 个性化增加滚动条设置,添加dconfig和处理搜索数据

- src/frame/window/modules/accounts/accountsdetailwidget.cpp
如果当前登录的账户是域用户，置灰修改密码按钮
Log: 控制中心置灰LDAP账户修改密码选项
Task: https://pms.uniontech.com/task-view-235581.html
Influence: 控制中心LDAP账户页面显示
Change-Id: I3d158e9cedae7530c094848bb2ff90621cea5c73
> feat: 控制中心置灰LDAP账户修改密码选项

- src/frame/window/modules/authentication/addirisinfodialog.cpp
- src/frame/window/modules/authentication/irisdetailwidget.cpp
调用录入前需要隐藏回话,返回后再继续展示
Log: 虹膜录入优化
Bug: https://pms.uniontech.com/bug-view-181933.html
Influence: 虹膜录入
Change-Id: I57b7860940f618718537d58e51af02b4af982e3d
> fix: 修复添加虹膜时点击下一步，添加虹膜数据弹框未消失问题

- src/frame/window/modules/keyboard/systemlanguagewidget.cpp
m_langListview在setEnabled(false)后m_langListview会失去焦点，此时焦点会自动跳转到其他部件， 需要手动处理下焦点
Log: 修复添加系统语言时，勾选新增系统语言后焦点偏移到返回按钮上问题
Bug: https://pms.uniontech.com/bug-view-180165.html
Influence: 焦点不会偏移到返回按钮上
> fix: 选择系统语言后需要处理界面焦点

- CMakeLists.txt
Log: update plugin is only used for deepin, so disable it
Change-Id: I816dd3d23fd585993f1ef1f4dd575681dc1f788f
> chore: add option to disable update plugin

- src/frame/main.cpp
将初始化 module 放在 DBus 导出之前
Log: 修复 GetModules 接口冷启动时返回空列表
> fix: 修复 GetModules 接口冷启动时返回空列表

- src/plugin-power/window/usebatterymodule.cpp
关联了错误的配置选项，导致修改对应选项未生效
Log: 修复控制中心电池管理的设置丢失的问题
resolve: https://github.com/linuxdeepin/developer-center/issues/3768
Influence: 控制中心电池管理/任务栏电池信息显示
> fix: 控制中心电池管理的设置丢失

- CMakeLists.txt
- archlinux/PKGBUILD
- src/plugin-keyboard/operation/keyboardwork.cpp
- src/plugin-keyboard/window/keyboardmodule.cpp
- src/plugin-keyboard/window/keyboardmodule.h
Log: add option DISABLE_LANGUAGE
deepin上的language选项有时候会调用dpkg,除了对后端修改以外，源码中本来就有宏禁用这一选项，然而原本的宏根本没有作用，所以对应的修改了下
resolve: https://github.com/linuxdeepin/developer-center/issues/3733
> chore: fix DCC_DISABLE_LANGUAGE option

- src/plugin-keyboard/window/kblayoutsettingwidget.cpp
- src/plugin-keyboard/window/keyboardmodule.cpp
- src/plugin-keyboard/window/systemlanguagewidget.cpp
这个flag在控制中心里面是没有意义的。本来这个页面就不应该嵌套，但是设计上在title加了和下面有关联的信号，那就很难办了。。所以还是直接移除flag
resolve: https://github.com/linuxdeepin/developer-center/issues/3725
> fix: the size of scrollarea will not adjust to window

- src/plugin-accounts/window/accountsmodule.cpp
when the plugin cannot read account , then it will coredump
Log: fix coredump when cannot read account
> fix: coredump when cannot read account

- src/frame/mainmodule.cpp
从子模块返回主页时，没有恢复sidenav的宽度，导致标题栏阴影宽度未恢复
close linuxdeepin/developer-center#3586
> fix: sidenav width not restore when return to home

- src/frame/mainmodule.cpp
resolve: https://github.com/linuxdeepin/developer-center/issues/3885
使用count可以修复，empty是递归查找子layout是否是空，而这里需要删除所有子layout
> fix: fix mutipage appear

- src/plugin-bluetooth/operation/bluetoothdevice.h
resolve: https://github.com/linuxdeepin/developer-center/issues/3730
原因是收到了headset的icon值没有设置成headset的图标
> headset not show as headset in bluetooth

- src/frame/pluginmanager.cpp
- src/frame/pluginmanager.h
set 5 sec timeout for if plugin cannot construct
resolve: https://github.com/linuxdeepin/developer-center/issues/3949
遇到了插件初始化无法完成的问题。。如果是真同步的话 -d就永远启动不了了。所以添加超时检查
> feat: use a timeout to load sync plugin

- src/plugin-display/operation/displayworker.cpp
- src/plugin-display/operation/machine.cpp
- src/plugin-display/operation/machine.h
- src/plugin-display/operation/machinedbusproxy.cpp
- src/plugin-display/operation/machinedbusproxy.h
- src/plugin-display/window/collaborativelinkwidget.cpp
需要绑定PropertiesChanged去更新对应的界面显示
Log: 修复控制中心跨端协同连接方向显示异常的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/3703
Influence: 控制中心显示界面跨端协同
> feat: 控制中心跨端协同连接方向显示异常

- src/frame/main.cpp
Before I want to add registerJournalAppender, but I also have do registerConsoleAppender, then console is registered twice, this will append to console twice, make the log unreadable, this pr fix it
Log: fix appendconsole add twice
> fix: appendconsole add twice

- src/plugin-accounts/window/avatarlistframe.cpp
- src/plugin-accounts/window/avatarlistframe.h
- src/plugin-accounts/window/avatarlistview.cpp
- src/plugin-accounts/window/avatarlistview.h
- src/plugin-accounts/window/avatarlistwidget.cpp
- src/plugin-accounts/window/avatarlistwidget.h
1. 用户自定义头像保存路径改由dde-system-daemon去保存, 防止登录界面获取不到用户头像
2. 修改用户自定义头像的保存逻辑(默认替换原来的头像)
Log: 修复控制中心用户头像显示异常的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/4041
Influence: 控制中心账户头像显示
> fix: 控制中心用户头像显示异常

- archlinux/PKGBUILD
- src/plugin-accounts/window/avatarlistframe.cpp
- src/plugin-accounts/window/avatarlistframe.h
- src/plugin-accounts/window/avatarlistview.cpp
- src/plugin-accounts/window/avatarlistview.h
- src/plugin-accounts/window/avatarlistwidget.cpp
- src/plugin-accounts/window/avatarlistwidget.h
多用户时,每个用户只显示当前用户定义的图片
Log: 优化控制中心用户头像显示
Resolve: https://github.com/linuxdeepin/developer-center/issues/4041
Influence: 控制中心账户头像显示
> chore: 优化控制中心用户头像显示

- src/plugin-accounts/window/avatarlistframe.cpp
- src/plugin-accounts/window/avatarlistframe.h
- src/plugin-accounts/window/avatarlistview.cpp
- src/plugin-accounts/window/avatarlistview.h
- src/plugin-accounts/window/avatarlistwidget.cpp
- src/plugin-accounts/window/createaccountpage.cpp
新建用户时, 从系统头像中随机选择一张, 不从头像列表中去选择,防止数据异常导致程序崩溃
Log: 修复控制中心新建用户时闪退的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/4107
Influence: 控制中心账户创建
> fix: 控制中心新建用户时闪退

- src/plugin-accounts/window/avatarlistframe.cpp
- src/plugin-accounts/window/avatarlistview.cpp
- src/plugin-accounts/window/avatarlistwidget.cpp
1. 默认头像路径(一个软链接)和实际头像路径不一样, 需要替换成实际的头像路径
2. 用户设置头像成功后关闭窗口
Log: 优化控制中心账户头像设置
Influence: 控制中心账户头像正常设置和显示
> chore: 优化账户头像设置

- src/frame/pluginmanager.cpp
- src/frame/pluginmanager.h
use eventloop, it will enter eventloop before load dbus, so back to thread sleep, and some plugin maybe take loog time to load, set notify time to 10 second
Log: adjust plugin load logic
> fix: plugin load with -d cannot load dbus in time

- src/frame/pluginmanager.cpp
Log: adjust logic of plugin load
> chore: when all plugins is loaded, but watcher is not finished

- src/frame/pluginmanager.cpp
Log: check qm file first then load translate
> fix: qt warning for non exist qm file

- src/plugin-update/operation/common.h
- src/plugin-update/operation/updatemodel.h
- src/plugin-update/operation/updatework.cpp
- src/plugin-update/window/updatectrlwidget.cpp
- src/plugin-update/window/updateplugin.cpp
- src/plugin-update/window/widgets/updatesettingitem.cpp
sync enum in common.h
the ModelUpdatesStatus is used to print log, should always be sync with
UpdateStatus in common.h, but seems it has long time no update, make
there is something error with the log, and there exists some typo both
in UpdateStatus and UpdateStatus, so also fix the typo
> sync enum in common.h

- src/plugin-commoninfo/window/commoninfomodule.cpp
wrong condition, should be no '!'
Log: show developmode when not deepin
> fix: when not deepin it still show developmode

- src/interface/hlistmodule.cpp
resolve: https://github.com/linuxdeepin/developer-center/issues/4443
if there is no qmouse event handle, it will fallback to xcb , then it can be draged
> fix Hlistmoduletitlebar cannot drag

- src/plugin-power/window/usebatterymodule.cpp
- src/plugin-power/window/useelectricmodule.cpp
in dde-daemon, there is 6 choices about ppower when lid is closed and etc, in dde-control-center, there is only 5, one is missing
Log: add missing choices in power plugin
resolve: https://github.com/linuxdeepin/developer-center/issues/4469
翻译需要同步dde-daemon那边的
> fix(power): missing choices in power plugin

- CMakeLists.txt
- misc/org.deepin.dde.ControlCenter1.service
- misc/org.deepin.dde.ControlCenter1.service.in
Log: avoid use hardcode path in dbus services
> chore: avoid use hardcode path in dbus services

- src/interface/hlistmodule.cpp
- src/interface/tabview.cpp
- src/interface/tabview.h
allow tabview can be drag, not use stretch, because stretch will make scrollarea display abnormal
Log: override mouseMoveEvent in tabview
> chore(tabview): tabview mouse event override

- src/widgets/accessibleinterface.cpp
it seems create a QList before into main function, with some cmake variables, the d pointer will be nullptr, so now use a function to create a new qlist when first start to solve the problem
Log:
> fix(coredump): coredump on opensuse

- src/plugin-power/window/usebatterymodule.cpp
设置UseBatteryModule displayName
Log: 修复控制中心电源模块使用电池显示为空的问题
Influence: 控制中心电源模块正常显示
Resolve: https://github.com/linuxdeepin/developer-center/issues/4781
> fix: 控制中心电源模块使用电池显示为空

- src/plugin-keyboard/window/systemlanguagewidget.cpp
Disable it's parent widget instead of children widgets.
Issue: https://github.com/linuxdeepin/developer-center/issues/4700
> fix: Wrong focus when switching keyboard's language

- tests/plugin-mouse/ut_touchpadsettingwidget.cpp
Log: because before classname is changed
> fix: failed test

- src/plugin-display/window/collaborativelinkwidget.cpp
when collaboration is disabled, the combobox need also disabled
resolve: https://github.com/linuxdeepin/developer-center/issues/4874
Log:
> fix(collaboration): when combobox need be disabled

- src/plugin-display/window/collaborativelinkwidget.cpp
init enable state
如果初始化时本来就是未打开的情况，combobox也应该是disabled, 这个时候connection还未连接
> chore: init device Comboox enable state

- CMakeLists.txt
- src/plugin-display/window/collaborativelinkwidget.cpp
- src/plugin-display/window/collaborativelinkwidget.h
DFileChooserEdit need a QFileChooser, so just exec a dialog when needed
Log:
> chore: not init filedialog in constructor

- src/frame/listview.cpp
when caculate the lenght of the left listview, before the final spacing is deleted, now not delete it
Log:
> chore: not delete length of the final spacing

- src/plugin-update/operation/updatework.cpp
> fix: machineid is remembered when joining testing

- src/plugin-authentication/window/widgets/disclaimersdialog.cpp
Issue: https://github.com/linuxdeepin/developer-center/issues/5636 Log:
> fix: light theme text in disclaimer is not clear

- src/plugin-commoninfo/window/bootwidget.cpp
- src/plugin-commoninfo/window/bootwidget.h
- src/plugin-commoninfo/window/commonbackgrounditem.cpp
- src/plugin-commoninfo/window/commoninfolistview.cpp
- src/plugin-commoninfo/window/commoninfolistview.h
set the listview size is the same as item count, and put it in the center.
And in commonbackgrounditem, not resize the image directly, keep the full shape of the origin image, final clip the center part as the shown image
Log:
Issue 没有找到。。我记得有的，而且我也不太爽这个地方
> fix: listview is not in the center of the widget

- CMakeLists.txt
- debian/rules
- src/plugin-datetime/operation/datetimedbusproxy.cpp
- src/plugin-datetime/operation/datetimedbusproxy.h
- src/plugin-datetime/operation/datetimeworker.cpp
- src/plugin-datetime/window/widgets/timezone.cpp
- src/plugin-datetime/window/widgets/timezone_map.cpp
> feat: can set special timezone when on deepin

- src/plugin-commoninfo/window/bootwidget.cpp
移除了："判断当前默认启动项是否在启动列表中，如果不在则直接返回" 的代码
Issue: https://github.com/linuxdeepin/developer-center/issues/5863
Log: 修复当前默认启动项不在控制中心-通用-启动菜单列表中时，无法通过点击修改默认启动项的问题
> fix: can not change boot entry when current boot entry is not in the boot list

- src/plugin-power/operation/powerdbusproxy.cpp
- src/plugin-power/operation/powerdbusproxy.h
- src/plugin-power/operation/powermodel.cpp
- src/plugin-power/operation/powermodel.h
- src/plugin-power/operation/powerworker.cpp
- src/plugin-power/operation/powerworker.h
- src/plugin-power/window/generalmodule.cpp
- translations/dde-control-center_en.ts
- translations/dde-control-center_zh_CN.ts
> feat: support balance_performance

- src/plugin-defaultapp/operation/defappworker.cpp
Finding result should be compared to cend to see if successful. Or
it would be a invalid iterator.
Log: fix crash when setting default application
> fix: crash when setting default application

- src/plugin-accounts/window/accountsmodule.cpp
- src/plugin-update/window/widgets/updatecontrolpanel.cpp
plugin create widget without parent and show will take focus
Issue: https://github.com/linuxdeepin/developer-center/issues/5693
> fix: mainwindow lost focus when switch module

- src/frame/mainmodule.cpp
- src/interface/moduledatamodel.cpp
- src/plugin-update/operation/updatework.cpp
update state when we got succeed status
moduleDataChanged ==> dataChanged ==> update(index)
Issue: https://github.com/linuxdeepin/developer-center/issues/5795
> fix: red point/badge not clear

- src/plugin-commoninfo/operation/commoninfomodel.cpp
- src/plugin-commoninfo/operation/commoninfomodel.h
- src/plugin-commoninfo/operation/commoninfoproxy.cpp
- src/plugin-commoninfo/operation/commoninfoproxy.h
- src/plugin-commoninfo/operation/commoninfowork.cpp
- src/plugin-commoninfo/operation/commoninfowork.h
- src/plugin-commoninfo/window/commoninfomodule.cpp
- src/plugin-commoninfo/window/commoninfomodule.h
- src/plugin-commoninfo/window/plymouthdisplay.cpp
- src/plugin-commoninfo/window/plymouthdisplay.h
- translations/dde-control-center_en.ts
- translations/dde-control-center_zh_CN.ts
计划是不在设置缩放时候设置plymouth, 将这个操作从startdde移除，控制中心单独做个模块去直接调用。不应该在设置屏幕缩放时候去设置动画跑一遍内核命令，当前行为感觉会对其他发行版的用户造成困扰
> chore: split plymouth scale setting

- src/plugin-update/operation/updatedbusproxy.cpp
- src/plugin-update/operation/updatedbusproxy.h
- src/plugin-update/operation/updatemodel.cpp
- src/plugin-update/operation/updatemodel.h
- src/plugin-update/operation/updatework.cpp
it will exist when it thought it should, and once upgrade, it will be invoked just once
Issue: https://github.com/linuxdeepin/developer-center/issues/6443 Log:
> fix: atom upgrade status should not store

- CMakeLists.txt
- debian/changelog
> chore: new tag, to 6.0.36

- src/plugin-datetime/window/timezonemodule.cpp
don't updateZones after removing a timezone unless the edit done
Issue: https://github.com/linuxdeepin/developer-center/issues/6410
> fix: Unable to delete timezone continuously

- src/frame/mainwindow.cpp
> when a modal window exists, do not switch pages

- src/plugin-accounts/operation/accountsworker.cpp
Issue: https://github.com/linuxdeepin/developer-center/issues/6874 Log:
> fix: dde-lock restart after set password status

- src/plugin-update/window/updatectrlwidget.cpp
- src/plugin-update/window/updatectrlwidget.h
- src/plugin-update/window/updateplugin.cpp
- src/plugin-update/window/updatewidget.cpp
- src/plugin-update/window/updatewidget.h
- translations/dde-control-center_en.ts
- translations/dde-control-center_zh_CN.ts
Version info for update widget and update ctrl widget is not consistent.
Use version info from model instead.
Log: fix version info data source not consistent
Issue: https://github.com/linuxdeepin/developer-center/issues/7253
> fix: version info data source not consistent

- src/frame/listview.cpp
- src/frame/listview.h
hover 不仅仅有viewport中的那几个事件，还有 checkMouseMove，这里直接用
QAbstractItemViewPrivate 中记录的 hover index
Issue: https://github.com/linuxdeepin/developer-center/issues/7119
> fix: hover index not repaint

- CMakeLists.txt
- debian/dde-control-center.install
- misc/org.deepin.dde-grand-search.dde-control-center-setting.conf
- src/frame/mainwindow.cpp
add grand search daemon config file
Issue: https://github.com/linuxdeepin/developer-center/issues/7333
> fix: grand search can not search dcc modules

- src/plugin-commoninfo/operation/commoninfowork.cpp
* 加入 deepin-logo、deepin-hidpi-logo 支持
Issues: linuxdeepin/developer-center#6249
> fix: the plymouth page displays incorrectly

- src/frame/mainwindow.cpp
hide back button when show root module
> feat: hide back button when show root module

- src/plugin-power/operation/powerdbusproxy.cpp
set the parameter to BlockWithGui when calling the dbus interface
Issue: https://github.com/linuxdeepin/developer-center/issues/7171
> fix: ui flash when switching power subpage

- src/plugin-power/operation/powerdbusproxy.cpp
set the parameter to BlockWithGui when calling the dbus interface
Issue: https://github.com/linuxdeepin/developer-center/issues/7171
> fix: flash appears when switching beteen  power's subpages

- src/frame/pluginmanager.cpp
> chore: No more notifications when loading plugin timeout

- CMakeLists.txt
This commit updates the ICU components in the CMakeLists.txt file. Previously,
only the 'i18n' component was being found using find_package for ICU. This
update includes the 'uc' component as well to ensure that all necessary ICU
components are found and linked correctly during the build process.
By adding 'ICU::uc' to the list of components, we ensure that the DateTime
plugin can make use of the required ICU functionalities without any issues.
> Update CMakeLists.txt to include 'ICU::uc' component for dcc-datetime-plugin

- src/plugin-datetime/window/widgets/regionformatdialog.cpp
- src/plugin-datetime/window/widgets/regionformatdialog.h
Parentheses are considered as control characters in regular expression.
Use wildcard filter in this case.
Log: fix cannot search parenthese
Issue: https://github.com/linuxdeepin/developer-center/issues/6002
> fix: cannot search parenthese

- src/plugin-datetime/operation/datetimeworker.cpp
- src/plugin-keyboard/operation/keyboardwork.cpp
- src/plugin-keyboard/operation/keyboardwork.h
env LC_TIME is always zh_CN.UTF-8, though LANG=en_US.UTF-8. 
long date format of QLocale::system() is acquired by the value of LC_TIME. 
use the QLocale::system().name() to construct the locale
Issue:https://github.com/linuxdeepin/developer-center/issues/7648
> fix: wrong long date format

- src/frame/window/modules/keyboard/shortcutsettingwidget.cpp
- src/frame/window/modules/keyboard/systemlanguagewidget.cpp
- src/frame/window/modules/mouse/touchpadsettingwidget.cpp
Log: the length of the touchpad backgroud box is inconsistend.
> fix: misalignment issues in some UI aspects of the control center

- src/frame/window/modules/keyboard/kblayoutsettingwidget.cpp
- src/frame/window/modules/keyboard/shortcutsettingwidget.cpp
- src/frame/window/modules/keyboard/systemlanguagewidget.cpp
Log: 调整控制中心键盘和语言模块下的键盘布局,系统语言,快捷键下方的增加按钮的位置,与控制中心默认程序模块和时间日期模块的增加按钮一致
> fix: 调整控制中心一些模块增加按钮的位置

- src/plugin-datetime/window/widgets/regionformatdialog.cpp
initialize the data before dialog is shown
Issue: https://github.com/linuxdeepin/developer-center/issues/8248
> fix: data of datetime is unintialized

- src/plugin-update/window/updatectrlwidget.cpp
- 备份更新弹窗固定大小，中文不会换行
- 下载更新按钮取消固定大小，随文字变化
- 去掉当需下载的大小为0时重新检查按钮禁用的逻辑
Issue:
- https://github.com/linuxdeepin/developer-center/issues/8756 
- https://github.com/linuxdeepin/developer-center/issues/8754
> fix: ui issues with update modules

- debian/changelog
* chore: use GenericName if X-Deepin-Vendor is 'deepin' (linuxdeepin/developer -center#6692)
> chore: bump version to 6.0.56

- src/plugin-commoninfo/operation/commoninfowork.cpp
- src/plugin-commoninfo/window/developermodewidget.cpp
- translations/dde-control-center_zh_CN.ts
- translations/dde-control-center_zh_HK.ts
- translations/dde-control-center_zh_TW.ts
Issue: https://github.com/linuxdeepin/developer-center/issues/8998
Log: Add translations for dde-control-center in plymouth notifications
> feat: Add translations for dde-control-center in plymouth notifications

- src/plugin-personalization-dock/window/dockplugin.cpp
Issue: https://github.com/linuxdeepin/developer-center/issues/8995
Log: Refresh dock plugins list when switch composite status
> fix: Refresh dock plugins list when switch composite status

- src/plugin-accounts/window/avatarlistframe.cpp
- src/plugin-accounts/window/avatarlistframe.h
- src/plugin-accounts/window/avatarlistwidget.cpp
requestSaveCustomAvatar signal receiver is only custom page object
Issue: https://github.com/linuxdeepin/developer-center/issues/9513
> fix: crash when selecting custom avatar

- src/plugin-notification/window/notificationmodule.cpp
moduleName cannot be translated
Log: as title
Influence: module can jump normally
> fix: module object name setting error

- src/plugin-keyboard/operation/shortcutmodel.cpp
Remove the shortcut keys super+A and super+W, as the 1070 kwin does not have their functions
Issue: https://github.com/linuxdeepin/developer-center/issues/9599
> fix: remove some shortcuts

- src/plugin-personalization-dock/window/dockplugin.cpp
connect to view instead of leftaction which has nothing to do with view's life span.
Issue: https://github.com/linuxdeepin/developer-center/issues/9883
Log: Fix crash when switching Light/Dark theme or Compisite status
> fix: Fix crash when switching Light/Dark theme

- src/plugin-datetime/window/widgets/datewidget.cpp
Stylesheet was set, so that, it is unable to respond to the theme change events.
Issue: https://github.com/linuxdeepin/developer-center/issues/10058
Log: Datetime labels cannot adapt to theme type changes
> fix: Datetime labels cannot adapt to theme type changes

- src/plugin-personalization-dock/window/dockplugin.cpp
min size:37.
Log: as title
Issue: https://github.com/linuxdeepin/developer-center/issues/10069
Influence: can adjust dock's min size
> fix: dock panel min size error

- src/plugin-sound/window/advancedsettingmodule.cpp
log: To switch the audio architecture, you need to first determine whether the architecture has been selected.
issue: https://github.com/linuxdeepin/developer-center/issues/10373
> fix: Fixed repeated click to switch audio schema

- src/plugin-personalization-dock/window/dockplugin.cpp
dock item status not updated
Bug: https://pms.uniontech.com/bug-view-271593.html
Log: need click twice to set hidden dock plugin visible
> fix: need click twice to set hidden dock plugin visible

- src/plugin-power/operation/powerdbusproxy.cpp
- src/plugin-power/operation/powerdbusproxy.h
- src/plugin-power/operation/powermodel.cpp
- src/plugin-power/operation/powermodel.h
- src/plugin-power/operation/powerworker.cpp
- src/plugin-power/operation/powerworker.h
- src/plugin-power/window/generalmodule.cpp
Hide powersave mode option if it is unsupported
Bug: https://pms.uniontech.com/bug-view-272203.html
Log: powersave mode is shown on unsupported platform
> fix: powersave mode is shown on unsupported platform

- include/dccrepeater.h
- src/dde-control-center/CMakeLists.txt
- src/dde-control-center/frame/dccrepeater.cpp
- src/dde-control-center/frame/plugin/src/dccqmlplugin.cpp
```qml
DccObject {
name: "Repeater"
parentName: "KeyboardLayout"
weight: 20
pageType: DccObject.Item
page: DccGroupView {
}
DccRepeater {
model: 3
delegate: DccObject {
name: "KeyboardLayoutItem" + index
parentName: "Repeater"
weight: 20 + index * 10
pageType: DccObject.Item
hasBackground: true
page: Label {
font.pointSize: 12
text: "keyboard layout" + index
}
}
}
}
```
> feat:  add dccrepeater

- dcc-old/src/plugin-personalization/window/personalizationdesktopmodule.cpp
This reverts commit fd30c4f82215a7519cd5be53d049d706c9aa8ae7.
> Revert "feat: hide compact mode"

- src/plugin-commoninfo/operation/commoninfomodel.cpp
- src/plugin-commoninfo/operation/commoninfomodel.h
- src/plugin-commoninfo/operation/commoninfowork.cpp
- src/plugin-commoninfo/operation/commoninfowork.h
- src/plugin-commoninfo/qml/BootPage.qml
- src/plugin-commoninfo/qml/main.qml
Log: Get the image path through the backend
Task: https://pms.uniontech.com/task-view-364169.html
> fix: Fixed the problem of obtaining the path of the boot menu theme

- debian/control
Resolve compilation issues
Log: As title.
> chore: Add 'qt6-declarative-private-dev' dependency in control

- dcc-old/src/plugin-datetime/window/timesettingmodule.cpp
- dcc-old/src/plugin-update/window/mirrorswidget.cpp
- dcc-old/src/plugin-update/window/mirrorswidget.h
- dcc-old/src/plugin-update/window/updatesettingsmodule.cpp
- dcc-old/src/plugin-update/window/updatesettingsmodule.h
1. Modify the style of the image source list widget
2. The mirror source list widget remains persistent
Log:
Bug: https://pms.uniontech.com/bug-view-277543.html 
Bug: https://pms.uniontech.com/bug-view-276725.html 
Bug: https://pms.uniontech.com/bug-view-276719.html
> fix: Modify the style of the image source list widget

- dcc-old/src/plugin-personalization/operation/personalizationworker.cpp
- dcc-old/src/plugin-personalization/window/personalizationthememodule.cpp
After setting the compact mode, the new font setting range will be displayed
Bug: https://pms.uniontech.com/bug-view-278551.html Log:
> fix: compact mode does not have control to adjust font settings range

- src/plugin-datetime/qml/DateTimeSettingDialog.qml
currentDate 修改会影响 spinbox 的 value, 导致部分修改不生效
最大最小年份，前后30年
Bug: https://pms.uniontech.com/bug-view-278637.html
> fix: date time set failed

- dcc-old/src/plugin-bluetooth/window/bluetoothdevicemodel.cpp
Bug: https://pms.uniontech.com/bug-view-279283.html
Log: Missing corresponding icon for bluetooth headset devices
> fix: Missing corresponding icon for bluetooth headset devices

- src/plugin-bluetooth/operation/bluetoothadapter.cpp
- src/plugin-bluetooth/operation/bluetoothadaptersmodel.cpp
- src/plugin-bluetooth/qml/Adapters.qml
- src/plugin-bluetooth/qml/BlueToothDeviceListView.qml
- src/plugin-bluetooth/qml/BluetoothCtl.qml
- src/plugin-bluetooth/qml/MyDevice.qml
- src/plugin-bluetooth/qml/OtherDevice.qml
Log: When the text is too long to exceed the window width, use omission display
Bug: https://pms.uniontech.com/bug-view-283979.html
Bug: https://pms.uniontech.com/bug-view-284071.html
> Fix: Fix the issue of excessively long Bluetooth names

- src/plugin-datetime/operation/datetimedbusproxy.cpp
- src/plugin-datetime/operation/datetimemodel.cpp
- src/plugin-datetime/operation/datetimemodel.h
- src/plugin-datetime/operation/datetimeworker.cpp
- src/plugin-datetime/operation/langregionmodel.cpp
- src/plugin-datetime/operation/langregionmodel.h
- src/plugin-datetime/operation/regionproxy.cpp
- src/plugin-datetime/operation/regionproxy.h
- src/plugin-datetime/qml/ComboLabel.qml
- src/plugin-datetime/qml/LangAndFormat.qml
- src/plugin-datetime/qml/TimeAndDate.qml
- 选择语言和区域之后更新所有格式
- 选择货币格式后更新货币数字（正负）
- 选择数字分组格式后更新数字分组
- 修复 label 对齐问题
- 修改长日期短时间日期顺序，先短后长
- 修复 24/12 小时制不对
- 更新时间日期在属性中更新
- 修复am/pm没翻译的bug
- 
Bug: https://pms.uniontech.com/bug-view-282897.html, https://pms.uniontech.com/bug-view-282871.html
> Fix timedate bug

- debian/control
> chore: Add version dependencies for libdtk6gui-dev

- debian/changelog
- src/plugin-personalization/qml/IconThemeGridView.qml
- src/plugin-personalization/qml/ThemeSelectView.qml
Replace Dciicon with Image, Dciicon will update the icon when the theme icon changes, which may cause crashes. First, switch to Image, and then follow Dciicon's crash problem
Log:
> fix: Crashes when switching icon themes

- CMakeLists.txt
- src/dde-control-center/CMakeLists.txt
- src/dde-control-center/frame/CMakeLists.txt
- src/dde-control-center/frame/plugin/CMakeLists.txt
- src/plugin-bluetooth/CMakeLists.txt
- src/plugin-commoninfo/CMakeLists.txt
- src/plugin-commoninfo/operation/commoninfomodel.cpp
- src/plugin-datetime/CMakeLists.txt
- src/plugin-defaultapp/CMakeLists.txt
- src/plugin-keyboard/CMakeLists.txt
- src/plugin-mouse/CMakeLists.txt
- src/plugin-personalization/CMakeLists.txt
- src/plugin-personalization/operation/model/wallpapermodel.h
- src/plugin-power/CMakeLists.txt
- src/plugin-sound/CMakeLists.txt
- src/plugin-systeminfo/CMakeLists.txt
- src/plugin-touchscreen/CMakeLists.txt
- src/plugin-wacom/CMakeLists.txt
- Specify Qt6
- Cancel explicit linking to dde control center
Log:
> chore: The new version of the dcc specifies the use of only Qt6

- src/plugin-datetime/operation/datetimemodel.cpp
- src/plugin-datetime/operation/regionproxy.cpp
- src/plugin-datetime/qml/TimeAndDate.qml
- dcc 显示的日期根据 『短日期』+『空格』+『周/星期』
- 去掉一个退出是警告
- 修复一个长时间选项减少的问题（重复过滤了，可能是 @FeiWang1119  手抖了：）
Bug: https://pms.uniontech.com/bug-view-282993.html
> fix: shortDate/longtime format error

- src/plugin-personalization/operation/treelandworker.cpp
Only call the protocol when the attribute truly changes
Log:
> feat: Prevent personalized circular binding on Treeland environment

- misc/org.deepin.dde.control-center.desktop
控制中心desktop名和wmclass不匹配，增加一个字段来正确标注控制中心的wmclass,让任务栏正确显示控制中心的打开状态
Bug: Task-368711
> feat: add the StartupWMClass field to the desktop file

- src/plugin-personalization/operation/treelandworker.cpp
- src/plugin-personalization/qml/FontSizePage.qml
向Treeland设置的字体大小约定为10倍的原始大小，用于间接存储存储浮点数
> fix: font size error

- src/plugin-mouse/qml/main.qml
Hide menu without touchpad
Log: Hide menu without touchpad
pms: BUG-290497
> fix: Hide menu without touchpad

- src/plugin-keyboard/qml/keyboard.qml
> chore: keyboard visble tweak

- src/plugin-datetime/operation/datetimeworker.cpp
初次安装完系统后只选择了语言，区域格式没有初始化
所以首次打开控制中心区域格式时初始化，防止出现空白选项
主要是货币格式默认是 ￥
pms: Bug-28617
> fix: region format init failed

- src/plugin-sound/operation/soundmodel.cpp
- src/plugin-sound/operation/soundworker.cpp
- src/plugin-sound/qml/SoundDevicemanagesPage.qml
have no input device,there are input titles and prompt texts
Log: The testing machine does not have an input device, and there are input titles and prompt texts in the device management interface
> fix: have no input device,there are input titles and prompt texts

- src/plugin-personalization/operation/personalizationmodel.cpp
- src/plugin-personalization/operation/personalizationmodel.h
- src/plugin-personalization/operation/personalizationworker.cpp
- src/plugin-personalization/operation/personalizationworker.h
- src/plugin-personalization/operation/x11worker.cpp
- src/plugin-personalization/operation/x11worker.h
- src/plugin-personalization/qml/WindowEffectPage.qml
- 迁移部分kwin-x11的逻辑到x11woker
- 标题栏高度不再支持dtk应用
- 删除部分不需要的逻辑（比如是否开启特效）
> feat(personalization): move some x11 logic to x11worker

- src/plugin-accounts/qml/AccountSettings.qml
- src/plugin-accounts/qml/AvatarSettingsDialog.qml
- hide CustomAvatarEmpatyArea on AvatarChanged
- autoLogin / nopasswdLogin switch button loop bind property
pms: Bug-292619, Bug-292671, Bug-292673
> fix: CustomAvatarEmpatyArea not hide/switchbutton loop bind

- src/plugin-personalization/operation/treelandworker.cpp
没有调用commit协议，Qt6程序默认显示合成器提供的光标，直接调用协议即可控制
遗留问题: Qt5 应用无法做到实时变化
pms: TASK-365811
> fix: cursor theme setting does not take effect in treeland

- src/plugin-accounts/operation/accountscontroller.cpp
- src/plugin-accounts/operation/accountscontroller.h
- src/plugin-accounts/qml/AccountSettings.qml
- src/plugin-accounts/qml/accountsMain.qml
- 将其他账户的 `AccountSettings` 移动到外部，减少 `dccobject` 的数量
- 当前账户被删除时返回账户首页
- 增加 `groups` 缓存，优化加载速度，放置频繁排序，新增/修改/删除分组时更新
> chore: Optimize accounts and groups loading speed

- translations/dde-control-center.ts
- translations/dde-control-center_az.ts
- translations/dde-control-center_bo.ts
- translations/dde-control-center_ca.ts
- translations/dde-control-center_es.ts
- translations/dde-control-center_fi.ts
- translations/dde-control-center_fr.ts
- translations/dde-control-center_hu.ts
- translations/dde-control-center_it.ts
- translations/dde-control-center_ja.ts
- translations/dde-control-center_ko.ts
- translations/dde-control-center_nb_NO.ts
- translations/dde-control-center_pl.ts
- translations/dde-control-center_pt_BR.ts
- translations/dde-control-center_ru.ts
- translations/dde-control-center_uk.ts
- translations/dde-control-center_zh_CN.ts
- translations/dde-control-center_zh_HK.ts
- translations/dde-control-center_zh_TW.ts
update sound translation
Log: update sound translation
pms: BUG-292509
> fix: update sound translation

- src/plugin-systeminfo/operation/systeminfomodel.cpp
- src/plugin-systeminfo/operation/systeminfomodel.h
- src/plugin-systeminfo/qml/NativeInfoPage.qml
professional edition hide Graphics Platform
Log: professional edition hide Graphics Platform
pms: BUG-282833
> fix: professional edition hide Graphics Platform

- src/dde-control-center/dccmanager.cpp
- src/dde-control-center/dccmanager.h
- src/plugin-mouse/qml/mouse.qml
- src/plugin-sound/qml/SpeakerPage.qml
Hide mouse under Treeland and show mono Audio
Log: Hide mouse under Treeland and show mono Audio
pms: BUG-291831
> fix: Hide mouse under Treeland and show mono Audio

- src/dde-control-center/pluginmanager.cpp
After the DBus jump, it was overwritten by the initialization jump
Log:
pms: BUG-289699
> fix: Failed to modify DBus jump issue

- dcc-old/src/plugin-accounts/window/avatarlistframe.cpp
- dcc-old/src/plugin-accounts/window/avatarlistwidget.cpp
change Type::Cartoon to Type::Dimensional
pms: BUG-295675
> fix: crash when saving avatar

- src/plugin-datetime/qml/TimezoneClock.qml
Temporarily disable animations
TODO: only enable animation on add timezone
> chore: disable timezone clock animation

- src/plugin-keyboard/operation/keyboardcontroller.cpp
modify failed when new shortcut accels(Supper+X) contains old shortcut accels(Supper) requestRestore is only emitted when "press" is false, to handle self-conflicts 
pms: Bug-289101
> fix: shortcut modify failed

- src/plugin-accounts/qml/AccountSettings.qml
- src/plugin-accounts/qml/CustomAvatarEmpatyArea.qml
- src/plugin-datetime/qml/LangAndFormat.qml
- src/plugin-datetime/qml/TimeAndDate.qml
- translations/dde-control-center_zh_CN.ts
- button size tweak
- fix translation missing
- label text AlignHCenter
pms: Bug-297099, Bug-297053
> button size  && CustomAvatarEmptyArea text align tweak

- src/plugin-personalization/qml/WindowEffectPage.qml
The default value of window effects causes these items to not display.
> fix: abnormal hiding of some items on Treeland

- src/plugin-commoninfo/operation/commoninfowork.cpp
Change the appName to org.deepin.dde.control-center and keep the appIcon empty
pms: Bug-297659
> fix: the icon for sending system notifications is incorrect

- src/plugin-datetime/operation/datetimemodel.cpp
Error in modifying the setting area
pms: BUG-299233
> fix: Error in modifying the setting area

- src/dde-control-center/dccmanager.cpp
- src/dde-control-center/dccmanager.h
The dconfig save will wait for the event loop and cannot be saved after the event loop exits
> fix: Modify the issue of dconfig saving crashing and freezing

- src/plugin-accounts/qml/PasswordModifyDialog.qml
add currentPwdVisible to PasswordModifyDialog
pms: BUG-300191
> fix: Incorrect password modification function for other accounts

- src/plugin-privacy/operation/privacysecuritymodel.cpp
- src/plugin-privacy/operation/privacysecurityworker.cpp
Not handling strings enclosed in quotation marks
pms: TASK-372065
> fix(privacy): some applications that have been abnormally excluded

- src/plugin-personalization/operation/treelandworker.cpp
Using the values of the dde-appearance module
pms: BUG-294895
> fix: the opacity has abnormally reached its maximum value in treeland

- src/dde-control-center/dccmanager.cpp
- src/plugin-authentication/qml/authentication.qml
- If the parent object has not been fully loaded after the plugin is loaded, it cannot be added to the object tree
- Support displaying and hiding after hot plugging
pms: TASK-372265
> fix: biometric authentication sometimes not displaying

- src/dde-control-center/dccmanager.cpp
- src/dde-control-center/frame/dccobject.cpp
The current object was not set to null ptr in a timely manner
pms: BUG-303491
> fit: Modifying the unplugged network card caused a crash issue

- src/plugin-personalization/qml/FontCombobox.qml
Optimize the width of the dropdown menu to display as fully as possible, and add a logic to display tooltips for names that are not fully displayed in the subsequent dtk
> fix: font combobox displays incomplete font names

- src/dde-control-center/dccmanager.cpp
Modify the disappearance issue of the network interface
> fix: Modify the disappearance issue of the network interface

- src/plugin-authentication/operation/charamangermodel.h
- src/plugin-authentication/operation/charamangerworker.cpp
- src/plugin-authentication/qml/AddFaceinfoDialog.qml
- src/plugin-authentication/qml/AddFingerDialog.qml
Hide the authentication dialog box to prevent multiple clicks on the next step
pms: BUG-304535
> fix: Continuous calls to the enroll interface may not initiate enroll

- src/plugin-accounts/operation/accountscontroller.cpp
- src/plugin-accounts/qml/AccountSettings.qml
Failed to monitor online user status updates
This allows the deletion of logged-in users
pms: BUG-303551
> fix: Can delete logged-in users

- src/dde-control-center/dccmanager.cpp
The issue of intercepting mouse events while modifying the ComboBox
pms: BUG-305889
> fix: The issue of intercepting mouse events while modifying the ComboBox

- src/plugin-authentication/qml/AddIrisDialog.qml
- src/plugin-authentication/qml/authenticationMain.qml
1. Changed visibility condition for success button from dccData.enrollIrisTips.addStage to dccData.irisController.addStage to fix incorrect property reference
2. Reduced maximum iris enrollment limit from 10 to 5 to match system capabilities
3. Fixed dialog loader indentation and structure to ensure proper component loading behavior
fix: 更新虹膜注册UI和最大限制
1. 将成功按钮的可见性条件从 dccData.enrollIrisTips.addStage 改为 dccData.irisController.addStage 以修复错误的属性引用
2. 将最大虹膜注册限制从10减少到5以匹配系统能力
3. 修复对话框加载器的缩进和结构以确保正确的组件加载行为
pms: BUG-334387
pms: BUG-334385
> fix: update iris enrollment UI and max limit

- src/dde-control-center/frame/plugin/DccItem.qml
- src/plugin-personalization/qml/WindowEffectPage.qml
Changed DccItem.qml to use t6 font from DTK fontManager for consistent typography
Removed explicit font assignment from WindowEffectPage.qml to use default font settings
These changes ensure better visual consistency across the control center interface
style: 更新控制中心字体样式
修改 DccItem.qml 使用 DTK fontManager 的 t6 字体以保持排版一致性
移除 WindowEffectPage.qml 中的显式字体设置以使用默认字体配置
这些更改确保控制中心界面具有更好的视觉一致性
pms: BUG-310875
> style: update font styles in control center
